- lib/taskana-core/src/main/java/pro/taskana/TaskMonitorService.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskMonitorServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/model/Report.java
- lib/taskana-core/src/main/java/pro/taskana/model/ReportLine.java
- lib/taskana-core/src/main/java/pro/taskana/model/ReportLineItem.java
- lib/taskana-core/src/main/java/pro/taskana/model/ReportLineItemDefinition.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/TaskMonitorMapper.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TaskMonitorServiceImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskMonitorServiceImplIntAutocommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskMonitorServiceImplIntExplicitTest.java
- In this first step just the total counts of tasks are considered. The next step would be to subdivide the amount of tasks in different ages.
- New models:  Report, ReportLine, ReportLineItem and ReportLineItemDefintion.
- A Report is created in the TaskMonitorService with workbaskets and states as parameters. The count of tasks in the respective workbaskets are calculated by the TaskMonitorMapper. The total sum of all tasks is calculated in the TaskMonitorService.
- Unit and integration tests are updated.
> TSK-110: Generate workbasket level report for total count of tasks

- lib/taskana-core/src/main/java/pro/taskana/Attachment.java
- lib/taskana-core/src/main/java/pro/taskana/TaskService.java
- lib/taskana-core/src/main/java/pro/taskana/impl/AttachmentImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/AttachmentMapper.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/ClassificationMapper.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/TaskMapper.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/WorkbasketMapper.java
- lib/taskana-core/src/test/java/acceptance/AbstractAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/CreateTaskAccTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TaskQueryImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TaskServiceImplTest.java
Task and Attachment load Classification afterwards and match them manually.
getClassificationById is not used anymore and attributes are matching the real properties now.
> TSK-141: Get Classification by Key+Domain in extra Query.

- lib/taskana-core/src/main/java/pro/taskana/TaskMonitorService.java
- lib/taskana-core/src/main/java/pro/taskana/impl/DaysToWorkingDaysConverter.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskMonitorServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/model/Report.java
- lib/taskana-core/src/main/java/pro/taskana/model/ReportLine.java
- lib/taskana-core/src/main/java/pro/taskana/model/ReportLineItemDefinition.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideCategoryReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideWorkbasketLevelReportAccTest.java
- lib/taskana-core/src/test/java/pro/taskana/database/TestDataGenerator.java
- lib/taskana-core/src/test/java/pro/taskana/impl/DaysToWorkingDaysConverterTest.java
- Create a converter that converts days to working days by using a table
- The table should exist all day if no changes are required
- Create tests for this converter
- Modify the existing report functions to count the age in working days
- Update test and sample data
- Remove empty lines from the WorkbasketLevelReport
> TSK-228: Replace days by working days in the reports

- lib/taskana-core/src/main/java/pro/taskana/configuration/TaskanaEngineConfiguration.java
- lib/taskana-core/src/main/java/pro/taskana/impl/DaysToWorkingDaysConverter.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskMonitorServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideCategoryReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideClassificationReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideCustomFieldValueReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideDetailedClassificationReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideWorkbasketLevelReportAccTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/DaysToWorkingDaysConverterTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TaskMonitorServiceImplTest.java
- Consider fix holidays like Christmas and movable holidays like Easter
- Calculate Easter Sunday with Gauss' formula and determine the other movable holidays with this day
- Make holidays configurable
- Add tests for all holidays
- Adapt existing acceptance and unit tests
> TSK-271: Add custom holiday support to the monitor

- lib/taskana-core/src/main/java/pro/taskana/ClassificationService.java
- lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/classification/CreateClassificationAccTest.java
- lib/taskana-core/src/test/java/acceptance/classification/UpdateClassificationAccTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/ClassificationServiceImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/ClassificationServiceImplIntAutoCommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/ClassificationServiceImplIntExplicitTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/ClassificationController.java
Changed ClassificationService.create() and update():
--> Throwing an Exception when no matching classification for the ParentClassificationId can be found.
update()
- removed insert, when classificationToUpdate does not ExistAlready (throwing notFoundException)
- removed getClassification in the end because it´s getting the same current classification again. Tests should approve that mapper.update() does work.
> TSK-341: No Exception when Classification-parent for ID does not exist

- lib/taskana-core/src/main/java/pro/taskana/TaskMonitorService.java
- lib/taskana-core/src/main/java/pro/taskana/impl/DaysToWorkingDaysConverter.java
- lib/taskana-core/src/main/java/pro/taskana/impl/DetailedClassificationReport.java
- lib/taskana-core/src/main/java/pro/taskana/impl/Report.java
- lib/taskana-core/src/main/java/pro/taskana/impl/ReportLineItemDefinition.java
- lib/taskana-core/src/main/java/pro/taskana/impl/SelectedItem.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskMonitorServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/mappings/TaskMonitorMapper.java
- lib/taskana-core/src/test/java/acceptance/monitoring/GetTaskIdsOfCategoryReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideCategoryReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideClassificationReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideCustomFieldValueReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideDetailedClassificationReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideWorkbasketLevelReportAccTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/DaysToWorkingDaysConverterTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TaskMonitorServiceImplTest.java
- Add methods to determine task ids of classification report 
- Add acceptance and unit tests
- Check all TaskMonitorService methods if input parameters are null and throw an exception if necessary
> TSK-264: Determine task ids for report line items of category report

- rest/taskana-rest-spring-example/src/test/java/pro/taskana/rest/AccessIdValidationControllerTest.java
- rest/taskana-rest-spring-example/src/test/java/pro/taskana/rest/GenenalExceptionHandlingTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/AccessIdController.java
- Remove required = false annotation since parameter it's required indeed
- Remove null check since requiring parameter will do that
- Add test for check BadRequest with an invalid parameter lenght
> TSK-531 Access id validation failing refinement

- web/src/environments/environment.prod.ts
- Since url are defined in rest API there is no need to define the production url in we app.
> TSK-455 Remove demo url from web app

- lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationServiceImpl.java
- Error message on validating service level is more descriptive adding some examples of how to use the ISO-8601 format.
> TSK-590 Add more descriptive error message on service level error.

- rest/taskana-rest-spring-example/src/main/java/pro/taskana/ldap/LdapCacheTestImpl.java
- rest/taskana-rest-spring-example/src/test/java/pro/taskana/rest/AccessIdValidationControllerTest.java
- rest/taskana-rest-spring-example/src/test/java/pro/taskana/rest/GenenalExceptionHandlingTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/ldap/LdapCache.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/AccessIdController.java
- web/src/app/administration/access-items-management/access-items-management.component.html
- web/src/app/administration/access-items-management/access-items-management.component.scss
- web/src/app/administration/access-items-management/access-items-management.component.ts
- web/src/app/shared/services/access-ids/access-ids.service.ts
- web/src/app/shared/sort/sort.component.scss
- web/src/app/shared/type-ahead/type-ahead.component.html
- web/src/app/shared/type-ahead/type-ahead.component.scss
- web/src/assets/_colors.scss
- web/src/assets/_site.scss
- Create new endpoint to get the groups associated to an access id (validating the access id)
- Show in the popup the group associated to access id (only for a user)
- TypeAhead is red when the access id is invalid.
- The delete button is on bottom right position (just activated for the user)
- Disable delete button for groups
- Remove the dots of the lists
> TSK-714 - Improve all workbasket access items for a user screen

- rest/taskana-rest-spring-example/src/test/java/pro/taskana/rest/ClassificationDefinitionControllerIntTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/ClassificationDefinitionController.java
The aim is to keep the parent-child relations which exists in the File, while the classification-ids are replaced.
To do this, we first save the parent key of a child, insert all classifications without parent information and finally update the parent information for all existing childs.
> TSK-744: Make Import of Parent-Child-Classifications possible

- rest/taskana-rest-spring-example/src/main/resources/static/environments/data-sources/environment-information.json
- web/src/app/services/startup-service/startup.service.ts
Default url of rest api is window.host property, if there is a environment-information.json file with a overriden url web application will use the one defined in the file.
> TSK-777 Set default rest url to window.host

- web/src/app/history/services/task-query/task-query.service.ts
- web/src/app/history/task-query/task-query.component.html
- web/src/app/history/task-query/task-query.component.scss
- web/src/app/history/task-query/task-query.component.ts
- web/src/app/models/query-parameters.ts
- web/src/app/models/task-history-event.ts
- web/src/app/shared/date-picker/date-picker.component.ts
- web/src/app/shared/pipes/date-time-zone/date-time-zone.pipe.ts
- web/src/app/shared/util/query-parameters.ts
- web/src/app/shared/util/taskana.date.ts
Reorders the columns and add the "created"-Instant (works as timestamp).
Default ordering is by "created" ascending.
A translation for the date-query is still missing.
It should be translated into a "TimeInterval"-Entity of the History-Service
> TSK-844: Reorder columns in history view and sort by "created"-value

- rest/taskana-rest-spring-test/src/test/java/pro/taskana/rest/ClassificationDefinitionControllerIntTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/ClassificationDefinitionController.java
When uploading an existing child-classification where the parent was removed, the parent-properties were not updated and the updated classification was still a child.
> TSK-859: make unlinking child from parent through import possible

- lib/taskana-core/src/main/java/pro/taskana/configuration/DbSchemaCreator.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskanaEngineImpl.java
- lib/taskana-core/src/test/java/acceptance/AbstractAccTest.java
- lib/taskana-core/src/test/java/acceptance/report/AbstractReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/workbasket/DeleteWorkbasketAccTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskServiceImplIntAutocommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskServiceImplIntExplicitTest.java
Removed 
- SQL Errors produced by checking if table exists. Now printed only in DEBUG mode
- wrong usages of DBCleaner (printed Errors in log)
- printed stackTrace for expected Error in DeleteWorkbasketAccTest
> TSK-860: Beautify the build log by correcting DB operations

- rest/taskana-rest-spring-example/src/main/resources/application.properties
- rest/taskana-rest-spring-wildfly-example/src/main/resources/application.properties
- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/TaskanaRestExceptionHandler.java
- web/src/app/administration/components/import-export/import-export.component.ts
This commit increases the maximum size for the Upload to 10 MB.
For bigger files a new ExceptionHandler is added, which returns a PayloadTooLarge-Status.
This Status is received by the Import-Export-Component and shows an own Message.
But most browers (eg. Chrome, Firefox, Opera) automatically stop sending an upload file when the servers maximum file size is reached.
Due to this feature no response is received (although the server sends it) and an network-error is thrown.
In this case the Import-Export-Module now shows a special message when the upload is aborted because of an error.
> TSK-861: Throw error when File upload aborted

- rest/taskana-rest-spring-test/src/main/asciidoc/rest-api.adoc
Corrected 3 Typos and replace Link where no FieldDescription is possible (because only a Boolean is returned)
> TSK-898: Rest Documentation missing example snippets

- lib/taskana-core/src/main/java/pro/taskana/CallbackState.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/task/CallbackStateAccTest.java
-Added a new CallbackState which is needed when a task was claimed by TASKANA
-Added ruleset logic to determine if the public API is allowed to set the desired CallbackState
-Added acceptance test for the ruleset logic
> TSK-909 - Claim task in camunda if task is claimed in TASKANA

- web/src/app/administration/access-items-management/access-items-management.component.html
- web/src/app/administration/access-items-management/access-items-management.component.ts
- web/src/app/administration/workbasket/master/workbasket-list-toolbar/workbasket-list-toolbar.component.html
- web/src/app/administration/workbasket/master/workbasket-list-toolbar/workbasket-list-toolbar.component.ts
- web/src/app/administration/workbasket/master/workbasket-list.component.html
- web/src/app/administration/workbasket/master/workbasket-list.component.spec.ts
- web/src/app/administration/workbasket/master/workbasket-list.component.ts
- web/src/app/workplace/taskmaster/task-list-toolbar/task-list-toolbar.component.html
- web/src/app/workplace/taskmaster/task-list-toolbar/task-list-toolbar.component.ts
- web/src/app/workplace/taskmaster/task-master.component.html
- web/src/app/workplace/taskmaster/task-master.component.ts
It used to be possible that initial sorting of the list and initial check in dropdown sorting menu differ. That's why a property is added which centralizes the initial sorting.
In the workplace tasklist, sorting and checkbox differed and an error occured when changing the ascending order to descending order with initial sorting. This problem is fixed.
> TSK-1046 Changed default sorting in workbasket list to Name

- web/src/app/workplace/components/task-master/task-master.component.html
There still was an occurance of taskana-code i the workplace component, which caused errors, when trying to load it. This small fix just removed the unneccessary code.
> Fixup for artifact in Workplace, which broke it

- web/src/app/administration/components/classification-details/classification-details.component.html
- web/src/app/shared/components/number-picker/number-picker.component.html
- web/src/app/shared/components/number-picker/number-picker.component.scss
- web/src/app/shared/components/number-picker/number-picker.component.ts
- web/src/theme/_forms.scss
Please use a priority of 0 as default instead of leaving that field empty. Was what the issue called for
My solution is different:
The buttons now work as expected: even when there is no value assigned the buttons initialize it and count up/down from 0. Additionally the input for the priority now only accepts numbers  and is required for every classification.
> TSK-1069 The number picker now only accepts numbers and can be made required

- web/src/app/shared/components/pagination/pagination.component.html
- web/src/app/shared/components/pagination/pagination.component.scss
After typing other values than numbers into the pagination "select page" function, the page reloads, the workbaskets are gone and the Error message "There was error, please contact with your administrator" with the content "BAD_REQUEST page must be a integer value." appears.
This issue has been fixed by adjusting the input type of the input and then removing of the arrows, because they covered most of the input
> TSK-1127 Changed input of Pagination to type number and removed arrows

- web/package-lock.json
- web/src/app/shared/components/popup/dialog-pop-up.component.html
- web/src/app/shared/components/popup/dialog-pop-up.component.spec.ts
The removal of classifications and workbaskets did not work, because the confirmation did not return the correct callback, but instead the string "callback".
This has been fixed now.
> TSK-1205 Fixed problem with the callback of confirmation dialogs

- qa/hooks/commit-msg
Added a small git hook, that validates git commits.
It checks, if commits do follow the structure "TSK-1274: This is an example"
It also validates, that the referenced Task exists on our jira board.
To enable this script please configure your git with: `git config core.hooksPath qa/hooks`
> TSK-1274: Added git hook, that validates git commits

- web/src/app/administration/administration.module.ts
- web/src/app/administration/components/classification-list/classification-list.component.spec.ts
- web/src/app/administration/components/classification-types-selector/classification-types-selector.component.html
- web/src/app/administration/components/classification-types-selector/classification-types-selector.component.scss
- web/src/app/administration/components/classification-types-selector/classification-types-selector.component.spec.ts
- web/src/app/shared/components/sort/sort.component.html
- web/src/app/shared/components/sort/sort.component.scss
The selection dropdown for the classification types, also used checkboxees, these operated like radio buttons. Their visual appearance should reflect their use, therefor they have been changed into radio buttons.
> TSK-1276: Added radiobuttons to classification type selection dropdown

- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.html
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.ts
- web/src/app/shared/components/type-ahead/type-ahead.component.ts
> When administrating taskana accessIDs for a workbasket:
> 
> Given I want to create a new accessID
> When I click on the `+ Add new access` button
> Then I expect an empty accesItem entry (row) to be created AND I expect that the cursor is within the accessID so that I can immediately start typing the accessId after clicking the button.
This expected behaviour is now implemented.
> TSK-1039: Autofocus AccessID field after adding a new AccessID in Workbasket

- .github/auto-comment.yml
Updated the autocomment bot, to provide answers for "no update needed" for documentation and release notes. Small rewording of most of the answers.
> TSK-1300: Updated the autocomment bot

- history/taskana-simplehistory-rest-spring/src/main/java/pro/taskana/simplehistory/rest/TaskHistoryEventController.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/util/CheckedBiConsumer.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/classification/rest/ClassificationController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/QueryHelper.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/TaskanaRestExceptionHandler.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskCommentController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/workbasket/rest/WorkbasketAccessItemController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/workbasket/rest/WorkbasketController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/QueryHelperTest.java
I couldn't find a spot in our `rest-api` where query parameters were documented.
Since I don't have the time to document all query parameters I didn't document the new behaviour.
https://sonarcloud.io/dashboard?branch=task%2F1331&id=mustaphazorgati_taskana
Code Coverage: I have no idea why it dropped. I tested the addition of new code. 
Probably because the other methods I refactored were not tested in the first place
Code Smells: 
- [code smell 1](https://sonarcloud.io/project/issues?branch=task%2F1331&id=mustaphazorgati_taskana&open=AXM1aKBdrgK0Yoghlb9G&resolved=false&types=CODE_SMELL ): Was there before, won't fix
- [code smell 2](https://sonarcloud.io/project/issues?branch=task%2F1331&id=mustaphazorgati_taskana&open=AXM1aKDfrgK0Yoghlb9H&resolved=false&types=CODE_SMELL): Will be fixed …
> TSK-1331: allowed multiple sortBy declarations in REST api

- web/src/app/administration/components/access-items-management/access-items-management.component.html
- web/src/app/administration/components/access-items-management/access-items-management.component.spec.ts
- web/src/app/administration/components/access-items-management/access-items-management.component.ts
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.spec.ts
- web/src/app/shared/components/type-ahead/type-ahead.component.ts
- web/src/app/shared/services/access-ids/access-ids.service.ts
- web/src/app/shared/services/forms-validator/forms-validator.service.ts
The AccessItemManagemant previously did not correctly display the accessItems of the requested accessId. It either showed only the accessItems of the groups the id belonged to, or it showed every item, when the id did not belong to another group. This happened, because the id itself, has not been added to the request. 
Currently there is no real way, to know if the searched for id is a group. Therefore the revokeAccessButton is always enabled, but will throw an error, when trying to remove the accesses of a group.
The belongingGroupsButton now also correctly shows the groups.
https://sonarcloud.io/dashboard?branch=TSK-1328&id=Tristan2357_taskana
> TSK-1327, TSK-1328: Fixed accessItemManagement

- history/taskana-simplehistory-provider/src/test/java/acceptance/events/CreateHistoryEventOnTaskCancelClaimAccTest.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/events/CreateHistoryEventOnTaskCancellationAccTest.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/events/CreateHistoryEventOnTaskClaimAccTest.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/events/CreateHistoryEventOnTaskCompletionAccTest.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/events/CreateHistoryEventOnTaskCreationAccTest.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/events/CreateHistoryEventOnTaskTerminationAccTest.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/events/CreateHistoryEventOnTaskTransferAccTest.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/events/CreateHistoryEventOnTaskUpdateAccTest.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/events/DeleteHistoryEventsOnTaskDeletionAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/spi/history/api/events/task/CancelledEvent.java
- lib/taskana-core/src/main/java/pro/taskana/spi/history/api/events/task/TerminatedEvent.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
Sonarcloud: https://sonarcloud.io/dashboard?branch=TSK-1333&id=gitgoodjhe_taskana
NOTE:
The test coverage is once again not correct. it should be 100%, since it says the uncovered lines are the constructors of the 2 new events as well as the creation in the terminate/cancel methods of the TaskServiceImpl. These clearly actually get tested in the PR.
> TSK-1333: Add history events for cancelled/terminated tasks

- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.ts
- web/src/app/administration/components/workbasket-details/workbasket-details.component.html
- web/src/app/administration/components/workbasket-details/workbasket-details.component.spec.ts
- web/src/app/administration/components/workbasket-details/workbasket-details.component.ts
- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.ts
- web/src/app/administration/components/workbasket-information/workbasket-information.component.ts
- web/src/app/administration/components/workbasket-list-toolbar/workbasket-list-toolbar.component.spec.ts
- web/src/app/administration/components/workbasket-list/workbasket-list.component.spec.ts
- web/src/app/shared/store/workbasket-store/workbasket.state.ts
There are still two commits because in the second commit, I moved the initialization of the store's 'selectedComponent'-attribute from workbasket-details to the store itself. Now, the 'selectedTab'-variable directly depends on the store's variable. For me this improves readability / understanding.
If this is not desired, I will revert the commit. 
sonar: https://sonarcloud.io/dashboard?branch=TSK-1448&id=sofie29_taskana
---
> TSK-1448: Expand workbasket path with selected tab

- pom.xml
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/TestSchemaNameCustomizable.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/doc/api/ClassificationControllerRestDocumentation.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/doc/api/TaskCommentControllerRestDocumentation.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/doc/api/TaskControllerRestDocumentation.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/doc/api/WorkbasketControllerRestDocumentation.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/monitor/rest/models/ReportRepresentationModelTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/WorkbasketAccessItemControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/assembler/WorkbasketSummaryRepresentationModelAssemblerTest.java
Update of Spring Boot version to 2.4.0
Thus and because it is a rule in our guidelines I exchanged all remaining Assertion (junit) uses with the Assertj framework. Moreover Alphanumeric is deprecated since that version, thus change to MethodName.
---
> TSK-1239: Assertj use in every module

- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.html
- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.spec.ts
- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.ts
Fix bugs when selecting a workbaskets with distribution targets from another workbasket with empty distribution targets list
---
> TSK-1489: Fixed bug in distribution target

- history/taskana-simplehistory-provider/src/test/java/acceptance/jobs/HistoryCleanupJobAccTest.java
- lib/taskana-core/src/test/java/acceptance/jobs/TaskCleanupJobAccTest.java
- lib/taskana-core/src/test/java/acceptance/jobs/WorkbasketCleanupJobAccTest.java
> TSK-1457: Fix timing issue in initializeSchedule tests for cleanupjobs

- common/taskana-common-test/src/main/java/pro/taskana/common/test/BaseRestDocTest.java
in order to automatically generate the documentation for our ModelAttribute request types
---
> TSK-1533: configured  spring-auto-rest-docks JacksonModelAttributeSnippet

- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/ldap/LdapClient.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/ldap/LdapClientTest.java
> TSK-1638: Make Comparator for AccessIds in LdapClient NULL-safe

- web/src/app/administration/components/workbasket-distribution-targets-list/workbasket-distribution-targets-list.component.html
- web/src/app/administration/components/workbasket-distribution-targets-list/workbasket-distribution-targets-list.component.spec.ts
- web/src/app/administration/components/workbasket-distribution-targets-list/workbasket-distribution-targets-list.component.ts
- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.html
- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.spec.ts
- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.ts
... and reverted the logic of the boolean allSelected. The checkbox is selected when allSelected is true.
---
> TSK-1627: Reset selectAll in DistributionTargets when Workbasket changes

- web/src/app/shared/components/pagination/pagination.component.html
- web/src/app/shared/components/pagination/pagination.component.spec.ts
- web/src/app/shared/components/pagination/pagination.component.ts
When the input is out of range or doesn't contain numbers, the whole list of suggestions is displayed. Additionally, the input is selected when the user clicks into the input field in order to make it easier to type in new values.
---
> TSK-1641: Modify pagination behavior when input is out of range

- lib/taskana-core/src/main/java/pro/taskana/task/internal/AttachmentMapper.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
The execution time has been reduced from O(n²) to O(n)
https://sonarcloud.io/dashboard?branch=task%2F1707&id=mustaphazorgati_taskana
---
> TSK-1707: Performance optimization for TaskService#getTask and TaskQuery#list

- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java
- lib/taskana-core/src/test/java/acceptance/task/QueryTasksAccTest.java
> TSK-1715: Implemented OwnerNotIn-Filter for TaskQuery.

- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskQueryFilterParameter.java
If domain is specified, but neither workbasket-key nor workbasket-key-not are specified, throw an Exception.
Sonarcloud: https://sonarcloud.io/summary/new_code?branch=TSK-1784&id=ryzheboka_taskana
---
> TSK-1784: throw exception while searching for tasks in case some arguments are invalid

- web/cypress/integration/workbaskets/workbaskets.spec.js
- web/cypress/support/commands.js
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.ts
- web/src/app/administration/components/workbasket-details/workbasket-details.component.html
- web/src/app/administration/components/workbasket-details/workbasket-details.component.ts
- web/src/app/administration/components/workbasket-distribution-targets-list/workbasket-distribution-targets-list.component.html
- web/src/app/administration/components/workbasket-distribution-targets-list/workbasket-distribution-targets-list.component.ts
- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.html
- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.ts
- web/src/app/administration/components/workbasket-information/workbasket-information.component.ts
- web/src/app/shared/services/workbasket/workbasket.service.ts
- web/src/app/shared/store/workbasket-store/workbasket.state.ts
Bug fixes:
Changes no longer get discarded when switching tabs
Saving of Workbasket Distribution Targets is now possible from all tabs
Saving of Workbasket Distribution Targets now works correctly and does not throw an error 400
Removing of Distribution Targets now works correctly
Removed loading of duplicate distribution targets
Added E2E tests for most previously mentioned bugs
---
> TSK-1806: Bug fixes for Workbasket Distribution Targets

- lib/taskana-core-test/src/test/java/acceptance/task/requestchanges/RequestChangesWithAfterSpiAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/requestchanges/RequestChangesWithBeforeSpiAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/InternalTaskanaEngine.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/TaskanaEngineImpl.java
- lib/taskana-core/src/main/java/pro/taskana/spi/task/api/AfterRequestChangesProvider.java
- lib/taskana-core/src/main/java/pro/taskana/spi/task/api/AfterRequestReviewProvider.java
- lib/taskana-core/src/main/java/pro/taskana/spi/task/api/BeforeRequestChangesProvider.java
- lib/taskana-core/src/main/java/pro/taskana/spi/task/api/BeforeRequestReviewProvider.java
- lib/taskana-core/src/main/java/pro/taskana/spi/task/internal/AfterRequestChangesManager.java
- lib/taskana-core/src/main/java/pro/taskana/spi/task/internal/AfterRequestReviewManager.java
- lib/taskana-core/src/main/java/pro/taskana/spi/task/internal/BeforeRequestChangesManager.java
- lib/taskana-core/src/main/java/pro/taskana/spi/task/internal/BeforeRequestReviewManager.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-test-api/src/main/java/pro/taskana/testapi/util/ServiceProviderExtractor.java
sonar: https://sonarcloud.io/summary/new_code?id=mustaphazorgati_taskana&branch=task%2F1944
IMPORTANT: #1990 has to be merged BEFORE this.
---
Release Notes:
```
**NEW**
* TSK-1945: added BeforeRequestChangesProvider which allows customized behavior before changes have been requested on a given Task.
```
> TSK-1944: Implemented BeforeRequestChanges SPI

- lib/taskana-core/src/main/java/pro/taskana/classification/api/ClassificationQuery.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/api/WorkbasketQuery.java
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-1952
---
Release Notes:
```
```
> TSK-1952: adjust parameter names in queries + some clean up

- .gitignore
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/InitBinderControllerAdvice.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/WorkbasketAccessItemControllerIntTest.java
all String[] parameters should not be splitted when only one parameter exists, with values delimited with comma
SonarCloud: https://sonarcloud.io/summary/new_code?id=arolfes_taskana&branch=TSK-1699-query-parameters
Sonar failes but I haven't touched this file at all
---
Release Notes:
```
```
> TSK-1699 - Register CustomEditor for String[]

- .github/workflows/continuous-integration.yml
- pom.xml
https://sonarcloud.io/summary/new_code?id=arolfes_taskana&branch=TSK-1980-bump-surefire-plugin
---
Release Notes:
```
TSK-1980 Bump maven-surefire-plugin from 3.0.0-M5 to 3.0.0-M8
```
> TSK-1980 Bump maven-surefire-plugin from 3.0.0-M5 to 3.0.0-M8

- common/taskana-common/src/main/java/pro/taskana/common/internal/configuration/DB.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/configuration/DbSchemaCreator.java
[SonarCloud](https://sonarcloud.io/summary/new_code?id=arolfes_taskana&branch=TSK-1998-Use-DB-Enum-to-determine-SQL-Scripts)
Must be reviewed and merged after [TSK-1995 refactoring DB Enum](https://github.com/Taskana/taskana/pull/2100)
---
Release Notes:
```
Tsk-1998 use db enum to determine sql scripts
```
> Tsk-1998 use db enum to determine sql scripts

- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/task/claim/SelectAndClaimTaskAccTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/assembler/TaskRepresentationModelAssembler.java
[SonarCloud](https://sonarcloud.io/summary/new_code?id=arolfes_taskana&branch=TSK-2013-selectAndClaim-returns-Optional)
---
Release Notes:
```
```
> TSK-2013 selectAndClaim TasK return Optional and does not throw Exception if Task is notFound

- lib/taskana-core-test/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-2184
---
Release Notes:
```
```
> Closes #2184 - fix setting ownerLongName during claim

- lib/taskana-core-test/src/test/java/acceptance/TaskanaConfigurationTest.java
- lib/taskana-core/src/main/java/pro/taskana/TaskanaConfiguration.java
- lib/taskana-core/src/test/java/acceptance/config/TaskanaConfigAccTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/TaskanaEngineController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/TaskanaEngineControllerIntTest.java
[SonarCloud](https://sonarcloud.io/summary/new_code?id=arolfes_taskana&branch=2227-classifiation-categories-as-list)
---
Release Notes:
```
#2227 Categories of Classifications should have the same order as defined in taskana.properties
```
> Closes #2227 : ClassificationCategories are ordered as defined in properties

- lib/taskana-core-test/src/test/java/acceptance/TaskanaConfigurationTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/get/GetTaskAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplGroupByAccTest.java
- lib/taskana-core-test/src/test/resources/fullTaskana.properties
- lib/taskana-core/src/main/java/pro/taskana/TaskanaConfiguration.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/models/TaskSummary.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryMapper.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/models/TaskImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/models/TaskSummaryImpl.java
- lib/taskana-test-api/src/main/java/pro/taskana/testapi/builder/TaskBuilder.java
- lib/taskana-test-api/src/test/java/pro/taskana/testapi/builder/TaskBuilderTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskQueryGroupByParameter.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/assembler/TaskRepresentationModelAssembler.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/assembler/TaskSummaryRepresentationModelAssembler.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/models/TaskSummaryRepresentationModel.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/assembler/TaskRepresentationModelAssemblerTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/assembler/TaskSummaryRepresentationModelAssemblerTest.java
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-2246
---
Release Notes:
```
Add grouping by the same por or sor value. In case of sor values, a type needs to be specified. 
```
> Closes #2246 - add grouping by sors and pors

- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-2299
---
Release Notes:
```
```
> Closes #2299 - remove lock from the query when unnecessary

- .github/workflows/continuous-integration.yml
- README.md
> Closes #2328 - fix smoketest by waiting for demployment

- rest/taskana-rest-spring/src/docs/asciidoc/rest-api.adoc
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/util/QueryParamsValidator.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/user/rest/UserController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/user/rest/UserControllerIntTest.java
See issue [#2348](https://github.com/Taskana/taskana/issues/2348), [sonar](https://sonarcloud.io/summary/new_code?id=nyuuyn_taskana&branch=TSK-2348)
---
Release Notes:
```
Enables fetching the current user data via HTTP GET on /users?currentUser
```
> Closes #2348 - adds feature to request the current user via /users?currentUser

- lib/taskana-core-test/src/test/java/acceptance/task/complete/CancelTaskAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/complete/CompleteTaskWithSpiAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/complete/TerminateTaskAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/InternalTaskanaEngine.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/TaskanaEngineImpl.java
- lib/taskana-core/src/main/java/pro/taskana/spi/task/api/TaskEndstatePreprocessor.java
- lib/taskana-core/src/main/java/pro/taskana/spi/task/internal/TaskEndstatePreprocessorManager.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-test-api/src/main/java/pro/taskana/testapi/util/ServiceProviderExtractor.java
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-2366
---
Release Notes:
```
Add an SPI that is activated before a Task changes into an endstate. The affected methods are "complete", "cancel" and "terminate"
```
> Closes #2366 - add TaskEndstatePreprocessor

- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
Closes issue #2188 
---
Release Notes:
```
If attachments are set a wrong Task Id the API will respond with a BadRequest
```
> Closes #2188 - adds checking whether attachment has a proper taskId set when updating a task.

- common/taskana-common-data/src/main/java/pro/taskana/sampledata/SampleDataGenerator.java
- common/taskana-common-security/src/main/java/pro/taskana/common/internal/security/CurrentUserContextImpl.java
- common/taskana-common-test/src/main/java/pro/taskana/common/test/security/JaasExtension.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/configuration/parser/SimpleParser.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/util/ComparableVersion.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/util/ReflectionUtil.java
- lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationServiceImpl.java
- lib/taskana-test-api/src/main/java/pro/taskana/testapi/security/JaasExtension.java
https://sonarcloud.io/summary/new_code?id=jamesrdi_taskana&branch=TSK-2459
---
Release Notes:
```
```
> Closes #2459: Fix Code Smells

- lib/taskana-core-test/src/test/java/acceptance/TaskanaConfigurationTest.java
- lib/taskana-core/src/main/java/pro/taskana/TaskanaConfiguration.java
The exception now uses the default delimiter |. It would be possible to use the configured delimeter. However, it would require adding new property to the configuration. We can discuss what would be better! 
Example:
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [pro.taskana.TaskanaConfiguration]: Factory method 'taskanaConfiguration' threw exception with message: Parameter classificationCategoriesByType (taskana.classification.categories.<KEY>) is configured incorrectly. Please check whether all specified Classification Types exist. Additionally, check if the correct separator is used in the property taskana.classification.types .
---
Release Notes:
```
```
> Close #2200 - fix the exception text for wrong classification categories

- history/taskana-simplehistory-provider/src/test/java/acceptance/events/task/CreateHistoryEventOnTaskTransferAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskTransferrer.java
- lib/taskana-core/src/test/java/acceptance/task/transfer/TransferTaskAccTest.java
- rest/taskana-rest-spring/src/docs/asciidoc/rest-api.adoc
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/RestEndpoints.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/assembler/BulkOperationResultsRepresentationModelAssembler.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/models/BulkOperationResultsRepresentationModel.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/models/TransferTaskRepresentationModel.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerRestDocTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/assembler/BulkOperationResultsRepresentationModelAssemblerTest.java
https://sonarcloud.io/summary/new_code?id=jamesrdi_taskana&branch=TSK-2491-BackupNew
---
Release Notes:
```
```
> Closes #2491: Set Owner of Task when Transferring

- lib/taskana-core/src/main/java/pro/taskana/common/api/TaskanaEngine.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/TaskanaEngineImpl.java
Steps to reproduce the problem described in #2634:
- Implement the SPI ReviewRequiredProvider in the module taskana-rest-spring-example-boot
- Put a break point in the reviewRequired method to stop the execution
- Start 2 instances of taskana-rest-spring-example-boot using PostgreSQL
- Open the GUI, select a task to complete it: the break point should kick in
- While the execution of one instance is paused, call the update task endpoint on the other instance (e.g. PUT http://localhost:8081/taskana/api/v1/tasks/:taskId) and change a custom field
- Using another break point, check the output of getTask() in TaskServiceImpl.requestReview: without the changes in this PR, the changes in the custom field from the update in the previous point should not be there
The explanation is that this last …
> Closes #2634: Clear cache of SQL session from TaskanaEngine

- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/util/QueryParamsValidator.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskQueryFilterParameter.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/user/rest/UserController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/user/rest/UserControllerIntTest.java
> Closes #2635: Make owner-is-null=owner-is-null not valid, allow use case "owner-is-null=true"

- lib/taskana-core/src/main/java/pro/taskana/common/api/TaskanaEngine.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/TaskanaEngineImpl.java
…nderlying SQL session
---
```
```
> Closes #2634: Add TaskanaEngine.clearSessionCache to clear cache of underlying SQL session

- lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationMapper.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/ObjectReferenceMapper.java
> Closes #2659 Fix SQL in Mappers
