- lib/taskana-core/pom.xml
- monitor/package-lock.json
- workplace/package-lock.json
Just some changes on "taskana-core/pom.xml" to get the JDB-Driver from NovaTec repository instead of camunda.
> Changed Camunda to NovaTec Repository for JDBC-Driver

- lib/taskana-core/src/main/java/pro/taskana/TaskService.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/TaskMapper.java
- rest/src/main/java/pro/taskana/rest/TaskController.java
- rest/src/main/java/pro/taskana/rest/WorkbasketController.java
- Added select statement to taskMapper
- added new service-method
- applyed it to rest-project 
- tested with authentification (need READ rights on basket)
> TSK-58: Query tasks by workbasketId and tast-state (with Authentification)

- lib/taskana-cdi-example/src/main/java/pro/taskana/ExampleBootstrap.java
- lib/taskana-cdi/src/main/java/pro/taskana/TaskanaProducers.java
- lib/taskana-cdi/src/test/java/pro/taskana/TaskanaEjb.java
- lib/taskana-cdi/src/test/java/pro/taskana/TaskanaRestTest.java
- lib/taskana-core/src/main/java/pro/taskana/TaskService.java
- lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskServiceImpl.java
- lib/taskana-core/src/test/java/pro/taskana/impl/ClassificationServiceImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TaskServiceImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/SummaryServiceImplIntAutoCommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskServiceImplIntAutocommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskServiceImplIntExplicitTest.java
- lib/taskana-spring-example/src/main/java/pro/taskana/ExampleBootstrap.java
- lib/taskana-spring/src/test/java/pro/taskana/TaskanaComponent.java
- rest/src/main/java/pro/taskana/rest/TaskController.java
changed createTask functions for all files in lib.
> TSK-64: Refactor createManualTask to createTask

- lib/taskana-core/src/main/java/pro/taskana/SummaryService.java
- lib/taskana-core/src/main/java/pro/taskana/impl/SummaryServiceImpl.java
- lib/taskana-core/src/test/java/pro/taskana/impl/SummaryServiceImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/SummaryServiceImplIntAutoCommitTest.java
Don't know if its a relevant task. But I finished it.
> TSK-62: Let getTaskSummaries throw WorkbasketNotFoundException

- lib/taskana-cdi/src/test/java/pro/taskana/TaskanaRestTest.java
- lib/taskana-core/src/main/java/pro/taskana/Classification.java
- lib/taskana-core/src/main/java/pro/taskana/ClassificationQuery.java
- lib/taskana-core/src/main/java/pro/taskana/ClassificationService.java
- lib/taskana-core/src/main/java/pro/taskana/exceptions/ClassificationAlreadyExistException.java
- lib/taskana-core/src/main/java/pro/taskana/exceptions/ClassificationNotFoundException.java
- lib/taskana-core/src/main/java/pro/taskana/exceptions/TaskanaException.java
- lib/taskana-core/src/main/java/pro/taskana/exceptions/TaskanaRuntimeException.java
- lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/model/ClassificationImpl.java
- lib/taskana-core/src/main/java/pro/taskana/model/Task.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/ClassificationMapper.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/QueryMapper.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/TaskMapper.java
- lib/taskana-core/src/test/java/pro/taskana/impl/ClassificationQueryImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/ClassificationServiceImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TaskServiceImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TestClassificationQuery.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/ClassificationServiceImplIntAutoCommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/ClassificationServiceImplIntExplicitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/SummaryServiceImplIntAutoCommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskServiceImplIntAutocommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskServiceImplIntExplicitTest.java
- lib/taskana-spring/src/test/java/pro/taskana/TaskanaComponent.java
- rest/src/main/java/pro/taskana/rest/ClassificationController.java
Added interface
Added interface everywhere (public api)
improved some Unit-tests
solved merge-conflicts
> TSK-61: Classification-Interface

- lib/taskana-cdi/src/test/java/pro/taskana/TaskanaRestTest.java
- lib/taskana-core/src/main/java/pro/taskana/exceptions/ClassificationAlreadyExistException.java
- lib/taskana-core/src/main/java/pro/taskana/exceptions/ClassificationNotFoundException.java
- lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskServiceImpl.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/SummaryServiceImplIntAutoCommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskServiceImplIntAutocommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskServiceImplIntExplicitTest.java
Adding code-review issues and resolved failures on TaskIntegrationTests.
- Fixed TaskIntegrationTests
- Imporved ClassificationExceptions-JavaDoc
- IntegrationsTests calling newClassification() on Service instead casting a new instance.
> TSK-61: Update after review

- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskServiceImplIntExplicitTest.java
- lib/taskana-core/src/test/java/pro/taskana/security/JAASRunner.java
- lib/taskana-core/src/test/java/pro/taskana/security/WithAccessId.java
- lib/taskana-core/src/test/resources/sql/workbasket-access-list.sql
- Add JAASRunner with a sample subject
- Remove the doAs methods from the tests and use it in JAASRunner
- Generate sample data instead of using a sql-file
> TSK-101: Run TaskServiceImplIntExplicitTest with JAASRunner

- lib/taskana-cdi/src/test/java/pro/taskana/TaskanaRestTest.java
- lib/taskana-core/src/main/java/pro/taskana/TaskService.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskServiceImpl.java
- lib/taskana-core/src/test/java/pro/taskana/impl/ClassificationServiceImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TaskServiceImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/WorkbasketServiceImplIntAutocommitTest.java
- lib/taskana-spring-example/src/main/java/pro/taskana/ExampleBootstrap.java
- rest/src/main/java/pro/taskana/rest/TaskController.java
...with force-flag and user-check. 
Added unit test for this function. 
Added completeTask(id) without flag
improved unit-test
reacted to TSK-22.
> TSK-23: Complete a Task... (REOPEN)

- lib/taskana-core/src/main/java/pro/taskana/TaskMonitorService.java
- lib/taskana-core/src/main/java/pro/taskana/TaskService.java
- lib/taskana-core/src/main/java/pro/taskana/TaskanaEngine.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskMonitorServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskanaEngineImpl.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/TaskMapper.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/TaskMonitorMapper.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TaskMonitorServiceImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TaskServiceImplTest.java
- rest/src/main/java/pro/taskana/rest/MonitorController.java
- rest/src/main/java/pro/taskana/rest/RestApplication.java
- Add TaskMonitorService and move the needed methods from TaskService
- Add TaskMonitorService and move the needed methods from TaskServiceImpl
- Add TaskMonitorServiceImplTest and move the needed methods from TaskServiceImplTest
- Update TaskanaEngine with TaskMonitorService
- Replace TaskService by TaskMonitorService in MonitorController 
- Update RestApplication with TaskMonitorService
> TSK-109: Separate monitor and task operations

- lib/taskana-cdi-example/src/main/java/pro/taskana/ExampleBootstrap.java
- lib/taskana-cdi/src/test/java/pro/taskana/TaskanaEjb.java
- lib/taskana-cdi/src/test/java/pro/taskana/TaskanaRestTest.java
- lib/taskana-core/src/main/java/pro/taskana/Task.java
- lib/taskana-core/src/main/java/pro/taskana/TaskQuery.java
- lib/taskana-core/src/main/java/pro/taskana/TaskService.java
- lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/QueryMapper.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/TaskMapper.java
- lib/taskana-core/src/test/java/pro/taskana/impl/ClassificationServiceImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TaskQueryImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TaskServiceImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskServiceImplIntAutocommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskServiceImplIntExplicitTest.java
- lib/taskana-spring-example/src/main/java/pro/taskana/ExampleBootstrap.java
- lib/taskana-spring/src/test/java/pro/taskana/TaskanaComponent.java
- rest/src/main/java/pro/taskana/rest/ClassificationController.java
- rest/src/main/java/pro/taskana/rest/TaskController.java
- rest/src/main/java/pro/taskana/rest/query/TaskFilter.java
- Introduced an interface for 'Task'
- added Methods
- solved conflicts
- fixed some test issues
- TaskImpl package-private constructor
> TSK-39: Interface for Task

- lib/taskana-core/src/main/java/pro/taskana/ClassificationService.java
- lib/taskana-core/src/main/java/pro/taskana/exceptions/ClassificationAlreadyExistException.java
- lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/ClassificationMapper.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/QueryMapper.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/TaskMapper.java
- lib/taskana-core/src/test/java/pro/taskana/impl/ClassificationQueryImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/ClassificationServiceImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TaskServiceImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TestClassificationQuery.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/ClassificationServiceImplIntAutoCommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/ClassificationServiceImplIntExplicitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskServiceImplIntAutocommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskServiceImplIntExplicitTest.java
- qa/eclipseFormatter/taskana_formatter.xml
- correced some ClassificationService Methods
- Tests
- need unique ID for task-join
(only one classification key+domain at one time existing but JOIN only got 1 param which is unique ID then)
> TSK-81: Create a Classification

- lib/taskana-cdi-example/src/main/java/pro/taskana/ExampleBootstrap.java
- lib/taskana-core/src/main/java/pro/taskana/TaskService.java
- lib/taskana-core/src/main/java/pro/taskana/impl/AttachmentImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/AttachmentMapper.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/QueryMapper.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/TaskMapper.java
- lib/taskana-core/src/test/java/acceptance/task/CreateTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/UpdateTaskAccTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TaskServiceImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskServiceImplIntAutocommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskServiceImplIntExplicitTest.java
- lib/taskana-spring-example/src/main/java/pro/taskana/ExampleBootstrap.java
- rest/src/main/java/pro/taskana/rest/TaskController.java
Only at Service - Query with attachments was not part of this task/ticket.
> TSK-137: Get all attachments of a Task.

- lib/taskana-cdi/src/test/java/pro/taskana/TaskanaRestTest.java
- lib/taskana-core/src/main/java/pro/taskana/Classification.java
- lib/taskana-core/src/main/java/pro/taskana/ClassificationQuery.java
- lib/taskana-core/src/main/java/pro/taskana/ClassificationService.java
- lib/taskana-core/src/main/java/pro/taskana/ClassificationSummary.java
- lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationSummaryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/model/TaskSummary.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/ClassificationMapper.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/QueryMapper.java
- lib/taskana-core/src/test/java/acceptance/classification/DeleteClassificationAccTest.java
- lib/taskana-core/src/test/java/acceptance/classification/GetClassificationAccTest.java
- lib/taskana-core/src/test/java/acceptance/classification/QueryClassificationAccTest.java
- lib/taskana-core/src/test/java/acceptance/classification/UpdateClassificationAccTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/ClassificationQueryImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/ClassificationServiceImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TaskServiceImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TestClassificationQuery.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/ClassificationServiceImplIntAutoCommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/ClassificationServiceImplIntExplicitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskMonitorServiceImplIntAutocommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskMonitorServiceImplIntExplicitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskServiceImplIntAutocommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskServiceImplIntExplicitTest.java
- rest/src/main/java/pro/taskana/rest/ClassificationController.java
Also deleted forbidden methods on Classification-Interface. 
Mappers for Query changed.
> TSK-146: Introduced ClassificationSummary Interface and Impl.

- lib/taskana-core/src/main/java/pro/taskana/model/mappings/QueryMapper.java
- lib/taskana-core/src/test/java/acceptance/task/QueryTasksByWorkbasketAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/UpdateTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/workbasket/GetWorkbasketAccTest.java
- lib/taskana-core/src/test/java/acceptance/workbasket/QueryWorkbasketByPermissionAccTest.java
- lib/taskana-core/src/test/resources/sql/workbasket-access-list.sql
especially for querying WB content.
> TSK-125: Create/Update/Enable Acc-Tests.

- lib/taskana-core/src/main/java/pro/taskana/TaskQuery.java
- lib/taskana-core/src/main/java/pro/taskana/TaskService.java
- lib/taskana-core/src/main/java/pro/taskana/impl/BulkOperationResults.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/QueryMapper.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/TaskMapper.java
- lib/taskana-core/src/test/java/acceptance/task/TransferTaskAccTest.java
Tested with a Acc-Test.
Method is declared at TaskService, not all Services!
Unittest will be implemented later, because I just want to get some feedback before.
> TSK-252: Bulk-Transfer for Task UPDATED

- lib/taskana-core/src/main/java/pro/taskana/TaskService.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/model/mappings/TaskMapper.java
- lib/taskana-core/src/test/java/acceptance/task/DeleteTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/TransferTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/WorkOnTaskAccTest.java
- Complete a bulk of tasks does work with storing errors
- Renamed completeTaskBulk to completeTasks
- Inproved deleteTasks (bulk) and updated the ACC-Tests
> TSK-273: Complete a bulk of tasks

- rest/src/main/java/pro/taskana/rest/RestApplication.java
- rest/src/main/java/pro/taskana/rest/WorkbasketDefinitionController.java
- rest/src/main/java/pro/taskana/rest/resource/WorkbasketDefinition.java
- rest/src/main/java/pro/taskana/rest/resource/mapper/WorkbasketDefinitionMapper.java
first version
initial setup
revert core
reverted changes
added query for domain in WorkbasketDefinitionController
created bean WorkbasketDefinitionMapper and autowired WorkbasketService
deleted ImportExportController
fixed rebase error
> TSK-299: added rest endpoint to export workbaskets

- admin/src/app/app.module.ts
- admin/src/app/shared/spinner/spinner.component.html
- admin/src/app/shared/spinner/spinner.component.scss
- admin/src/app/shared/spinner/spinner.component.spec.ts
- admin/src/app/shared/spinner/spinner.component.ts
- admin/src/app/workbasket/details/workbasket-details.component.html
- admin/src/app/workbasket/details/workbasket-details.component.spec.ts
- admin/src/app/workbasket/details/workbasket-details.component.ts
- admin/src/app/workbasket/list/workbasket-list.component.html
- admin/src/app/workbasket/list/workbasket-list.component.spec.ts
- admin/src/app/workbasket/list/workbasket-list.component.ts
- admin/src/assets/_site.scss
Probably you will not notice if spinner is working locally because the network connection is really fast.
If you want to test it locally first please simulate a poor network connection using this -> https://developers.google.com/web/tools/chrome-devtools/network-performance/network-conditions
> TSK-294 Create spinner component

- lib/taskana-core/src/main/java/pro/taskana/impl/DaysToWorkingDaysConverter.java
- lib/taskana-core/src/test/java/pro/taskana/impl/DaysToWorkingDaysConverterTest.java
- The instant is converted back to LocalDateTime to check whether a day is saturday or sunday
- Update also the unit test for this converter
> TSK-321: Change LocalDate to Instant in DaysToWorkingDaysConverter

- lib/taskana-core/src/main/java/pro/taskana/TaskMonitorService.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskMonitorServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/mappings/TaskMonitorMapper.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideCategoryReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideClassificationReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideCustomFieldValueReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideDetailedClassificationReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideWorkbasketLevelReportAccTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TaskMonitorServiceImplTest.java
- Add a list of categories as parameter to all methods of the TaskMonitorService and the TaskMonitorMapper
- Update unit and acceptance tests
> TSK-267: Add category filter to reports

- lib/taskana-core/src/main/java/pro/taskana/configuration/TaskanaEngineConfiguration.java
- lib/taskana-spring/src/main/java/pro/taskana/SpringTaskanaEngineImpl.java
- lib/taskana-spring/src/main/java/pro/taskana/configuration/SpringTaskanaEngineConfiguration.java
just a update for existing/integrated 318
> TSK-318: Enable security by default on Spring

- rest/src/main/java/pro/taskana/rest/WorkbasketController.java
- rest/src/main/java/pro/taskana/rest/resource/WorkbasketAccessItemResource.java
- rest/src/main/java/pro/taskana/rest/resource/WorkbasketResource.java
sourceId - list of targetIDs
Can be changed to sourceId + List<Wb> if wanted. Backend can still be list of ids.
> TSK-224: REST setDistributionTargets

- rest/src/main/java/pro/taskana/rest/ClassificationDefinitionController.java
- rest/src/main/java/pro/taskana/rest/WorkbasketDefinitionController.java
- rest/src/main/java/pro/taskana/rest/resource/WorkbasketDefinition.java
- rest/src/main/java/pro/taskana/rest/resource/WorkbasketResource.java
- rest/src/main/java/pro/taskana/rest/resource/mapper/WorkbasketAccessItemMapper.java
- rest/src/main/java/pro/taskana/rest/resource/mapper/WorkbasketDefinitionMapper.java
Please do not merge!!
https://github.com/Taskana/taskana/pull/224/commits has to be merged first
> TSK-300 import all workbasketdefinitions

- rest/src/main/java/pro/taskana/rest/ClassificationController.java
- rest/src/main/java/pro/taskana/rest/MonitorController.java
- rest/src/main/java/pro/taskana/rest/TaskController.java
- rest/src/main/java/pro/taskana/rest/WorkbasketController.java
- rest/src/main/java/pro/taskana/rest/WorkbasketDefinitionController.java
tested with workbaskets since the ClassificationController still does not use the resource classes
> TSK-347 enabled transaction management for all rest interfaces

- rest/pom.xml
- rest/src/main/java/pro/taskana/rest/resource/ClassificationResource.java
- rest/src/main/java/pro/taskana/rest/resource/WorkbasketAccessItemResource.java
- rest/src/main/java/pro/taskana/rest/resource/WorkbasketResource.java
- rest/src/main/java/pro/taskana/rest/resource/WorkbasketSummaryResource.java
- rest/src/main/java/pro/taskana/rest/resource/mapper/ClassificationMapper.java
- rest/src/main/java/pro/taskana/rest/resource/mapper/WorkbasketAccessItemMapper.java
- rest/src/main/java/pro/taskana/rest/resource/mapper/WorkbasketMapper.java
- rest/src/main/java/pro/taskana/rest/resource/mapper/WorkbasketSummaryMapper.java
- rest/src/test/java/pro/taskana/rest/resource/mapper/ClassificationMapperTest.java
- rest/src/test/java/pro/taskana/rest/resource/mapper/WorkbasketAccessItemMapperTest.java
- rest/src/test/java/pro/taskana/rest/resource/mapper/WorkbasketMapperTest.java
- rest/src/test/java/pro/taskana/rest/resource/mapper/WorkbasketSummaryMapperTest.java
> TSK-343 Using Bean Utils for mappers with tests

- lib/taskana-core/src/main/java/pro/taskana/BaseQuery.java
- lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/ObjectReferenceQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/WorkbasketAccessItemQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/WorkbasketQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/mappings/QueryMapper.java
- lib/taskana-core/src/test/java/acceptance/classification/QueryClassificationAccTest.java
- lib/taskana-core/src/test/java/acceptance/objectreference/QueryObjectReferenceAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/QueryTasksAccTest.java
- lib/taskana-core/src/test/java/acceptance/workbasket/QueryWorkbasketAccTest.java
- lib/taskana-core/src/test/java/acceptance/workbasket/QueryWorkbasketAccessItemsAccTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TestClassificationQuery.java
listValues() gets a TABLENAME as parameter and got the same QRY-String (with filters/...) like other QRYs of it´s type.
The returning value is a List of Strings containing all values which are used in the given column for the matching entries.
currently there is no parameter-validation! Maybe sould be a switch-case for columnnames later with InvalidArgumentException.
All Types can be converted to String (bool = 0/1, date="mm:dd:yyy..", ...)
> TSK-69: Offer all values of a DB-Column with filter by Query.

- lib/taskana-core/src/main/java/pro/taskana/TaskMonitorService.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskMonitorServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/mappings/TaskMonitorMapper.java
- lib/taskana-core/src/test/java/acceptance/monitoring/GetTaskIdsOfCategoryReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideCategoryReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideClassificationReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideCustomFieldValueReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideDetailedClassificationReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/monitoring/ProvideWorkbasketLevelReportAccTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TaskMonitorServiceImplTest.java
and use null parameter to disable a filter in TaskMonitorService
> TSK-269: Add custom property filter to reports

- admin/src/app/app.module.ts
- admin/src/app/pipes/remove-none-type.ts
- admin/src/app/services/workbasket.service.spec.ts
- admin/src/app/services/workbasket.service.ts
- admin/src/app/shared/filter/filter.component.html
- admin/src/app/shared/sort/sort.component.html
- admin/src/app/shared/sort/sort.component.scss
- admin/src/app/shared/sort/sort.component.spec.ts
- admin/src/app/shared/sort/sort.component.ts
- admin/src/app/shared/type-icon/icon-type.component.html
- admin/src/app/shared/type-icon/icon-type.component.ts
- admin/src/app/workbasket/details/information/workbasket-information.component.html
- admin/src/app/workbasket/details/workbasket-details.component.spec.ts
- admin/src/app/workbasket/list/workbasket-list.component.html
- admin/src/app/workbasket/list/workbasket-list.component.scss
- admin/src/app/workbasket/list/workbasket-list.component.spec.ts
- admin/src/app/workbasket/list/workbasket-list.component.ts
- monitor/package-lock.json
- monitor/package.json
- Fix sorting and filtering initialization
- Create sorting component
- Fix Github moment vulnerability from monitor
> TSK-354 Fix sorting bug and create sorting component

- lib/taskana-core/src/main/java/pro/taskana/impl/DaysToWorkingDaysConverter.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskMonitorServiceImpl.java
- lib/taskana-core/src/test/java/pro/taskana/impl/DaysToWorkingDaysConverterTest.java
- Now method convertWorkingDaysToDays returns all days that match to the inserted working day to include weekends and holidays
> TSK-379: Return all matching days in DaysToWorkingDaysConverter

- lib/taskana-core/src/test/java/acceptance/task/CreateTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/UpdateTaskAttachmentsAccTest.java
> TSK-384b  Fix testcases that calculated due date based on days rather than working days

- .travis.yml
- lib/deployment/change_version.sh
- lib/deployment/release.sh
tested on own travis: https://travis-ci.org/mustaphazorgati/taskana/builds/362506972
> bluemix deployment now working

- web/src/app/administration/classification/details/classification-details.component.spec.ts
- web/src/app/administration/classification/details/classification-details.component.ts
- web/src/app/administration/classification/master/list/classification-list.component.spec.ts
- web/src/app/administration/classification/master/list/classification-list.component.ts
- web/src/app/app.module.ts
- web/src/app/services/tree/tree.service.ts
- web/src/app/shared/tree/tree.component.spec.ts
- web/src/app/shared/tree/tree.component.ts
Text loading... label has been removed after deleting last children of a node.
> TSK-440 Fix loading... text when remove the last children of a node

- web/src/app/administration/classification/details/classification-details.component.html
- web/src/app/administration/classification/details/classification-details.component.spec.ts
- web/src/app/administration/classification/details/classification-details.component.ts
- web/src/app/app.module.ts
- web/src/app/services/classification-categories-service/classification-categories.service.spec.ts
- web/src/app/services/classification-categories-service/classification-categories.service.ts
- web/src/app/shared/tree/tree.component.html
Get Classification categories and types from their respective services.
> TSK-438 Get categories from classification category service.

- web/.angular-cli.json
- web/src/app/app-routing.module.ts
- web/src/app/app.module.ts
- web/src/app/guards/environment-url-guard.ts
- web/src/app/services/httpClientInterceptor/http-client-interceptor.service.ts
- web/src/environments/data-sources/environment-information.json
- Added external configuration file for url setup.
- If urls are empty string or file is not created, default url configuration is used
- Configuration file is located at: web/src/environments/data-sources/environment-information.json
- To change the file after AOT compilation file is located at \web\dist\environments\data-sources\*
> TSK-453 Add external configuration file for environment setup

- web/src/app/administration/classification/details/classification-details.component.html
- web/src/app/administration/classification/details/classification-details.component.ts
- web/src/app/administration/classification/master/list/classification-list.component.ts
- web/src/app/administration/workbasket/details/distribution-targets/distribution-targets.component.html
- web/src/app/administration/workbasket/details/distribution-targets/distribution-targets.component.ts
- web/src/app/administration/workbasket/details/workbasket-details.component.ts
- web/src/app/administration/workbasket/master/list/workbasket-list-toolbar/workbasket-list-toolbar.component.ts
- web/src/app/administration/workbasket/master/list/workbasket-list.component.html
- web/src/app/app-routing.module.ts
- web/src/app/app.module.ts
- web/src/app/guards/domain-guard.ts
- web/src/app/services/classification-categories-service/classification-categories.service.ts
- web/src/app/services/classification-types/classification-types.service.ts
- web/src/app/services/classifications/classifications.service.ts
- web/src/app/services/domain/domain.service.mock.ts
- web/src/app/services/domain/domain.service.ts
- web/src/app/services/errorModal/error-modal.service.ts
- web/src/app/services/startup-service/startup.service.ts
- web/src/app/shared/nav-bar/nav-bar.component.html
- web/src/app/shared/nav-bar/nav-bar.component.ts
- Fix Domain switching bug
- Cache domain server call to avoid multiple calls
- Move environment guard to startup service.
- Some minor improvements(tooltip when truncate text ...)
> Tsk 454 change domain details bug

- web/src/app/administration/workbasket/details/distribution-targets/dual-list/dual-list.component.scss
- web/src/app/administration/workbasket/master/list/pagination/pagination.component.scss
- web/src/app/administration/workbasket/master/list/workbasket-list.component.scss
- web/src/app/app-routing.module.ts
- web/src/app/shared/nav-bar/nav-bar.component.html
- Navigation bar bug
- Highligth lists on mouse hover.
> TSK-450 Fix navigation menu bug when load application for first time.

- web/package-lock.json
- web/package.json
- web/src/app/administration/classification/master/list/classification-list.component.scss
- web/src/app/administration/workbasket/master/list/pagination/pagination.component.html
- web/src/app/administration/workbasket/master/list/pagination/pagination.component.scss
- web/src/app/administration/workbasket/master/list/pagination/pagination.component.spec.ts
- web/src/app/administration/workbasket/master/list/pagination/pagination.component.ts
- web/src/app/administration/workbasket/master/list/workbasket-list-toolbar/workbasket-list-toolbar.component.spec.ts
- web/src/app/administration/workbasket/master/list/workbasket-list.component.scss
- web/src/app/administration/workbasket/master/list/workbasket-list.component.spec.ts
- web/src/app/app.component.spec.ts
- web/src/app/app.module.ts
- web/src/app/components/nav-bar/nav-bar.component.spec.ts
- web/src/assets/_site.scss
- web/src/index.html
- IE10 wrong paging position bug
- Page number now is being displayed correctly.
> TSK-451-457 Fix pagination bugs

- web/src/app/administration/classification/master/list/classification-list.component.scss
- web/src/app/shared/tree/tree.component.ts
- Classification filtering input style
- Collapse classification tree after clean filter
> TSK-474 Change classification searcher input style and collapse tree after remove filter

- lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/security/GroupPrincipal.java
- lib/taskana-core/src/test/java/pro/taskana/database/TestDataGenerator.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/AbstractPagingController.java
Some small changes to prevent potential Errors.
Found by using FindBugs-plugin for Eclipse
> TSK-520: Replaced code smells found by FindBugs

- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/TaskController.java
- web/src/app/services/workbasket/workbasket.service.ts
- web/src/app/shared/master-and-detail/master-and-detail.component.html
- web/src/app/workplace/services/task.service.ts
- web/src/app/workplace/task/task.component.html
- web/src/app/workplace/task/task.component.ts
- web/src/app/workplace/taskdetails/taskdetails.component.html
- web/src/app/workplace/taskdetails/taskdetails.component.scss
- web/src/app/workplace/taskdetails/taskdetails.component.ts
- web/src/app/workplace/tasklist/tasklist.component.html
- web/src/app/workplace/tasklist/tasklist.component.scss
- web/src/app/workplace/tasklist/tasklist.component.ts
- web/src/app/workplace/workbasket-selector/workbasket-selector.component.html
- web/src/app/workplace/workbasket-selector/workbasket-selector.component.ts
- web/src/app/workplace/workplace.module.ts
lots of bugfixes on the workplace, also renamed a PathVariable in the TaskController transfer method
> TSK-535: Bugfixes for Workplace

- web/src/app/administration/administration.module.ts
- web/src/app/administration/workbasket/details/access-items/access-items.component.html
- web/src/app/administration/workbasket/details/access-items/access-items.component.ts
- web/src/app/administration/workbasket/details/workbasket-details.component.spec.ts
- web/src/app/shared/type-ahead/type-ahead.component.ts
- Fixed add/remove access items bug
- Changed template-drive forms to Reactive/dynamic forms.
> TSK-541 Fix access items validation error when add/remove new access items and use ReactiveForms

- .travis.yml
- web/karma.conf.js
Use Firefox instead of PhantomJs since phantom is causing some problems.
> Tsk 376 Use firefox instead of PhantomJs for running UI tests

- lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationServiceImpl.java
- rest/taskana-rest-spring-example/src/test/java/pro/taskana/rest/GenenalExceptionHandlingTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/TaskanaRestExceptionHandler.java
- Create general exception handling error log system for all rest api endpoints
- Fix typo in ClassificationServiceImpl messages
> TSK-575 Created General handling error log system for REST API

- web/src/app/administration/classification/details/classification-details.component.spec.ts
- web/src/app/administration/classification/master/list/classification-list.component.spec.ts
- web/src/app/administration/components/import-export/import-export.component.spec.ts
- web/src/app/administration/workbasket/details/access-items/access-items.component.spec.ts
- web/src/app/administration/workbasket/details/distribution-targets/distribution-targets.component.spec.ts
- web/src/app/administration/workbasket/details/information/workbasket-information.component.spec.ts
- web/src/app/administration/workbasket/details/workbasket-details.component.spec.ts
- web/src/app/app.component.spec.ts
- web/src/app/app.test.configuration.ts
- web/src/app/components/nav-bar/nav-bar.component.html
- web/src/app/components/nav-bar/nav-bar.component.spec.ts
- web/src/app/components/nav-bar/nav-bar.component.ts
- web/src/app/guards/domain-guard.ts
- web/src/app/services/domain/domain.service.mock.ts
- web/src/app/services/domain/domain.service.spec.ts
- web/src/app/services/domain/domain.service.ts
- web/src/app/services/selected-route/selected-route.ts
- web/src/app/services/workbasket/workbasket.service.ts
- Master domain support for classifications / disable for workbaskets
- Remove some tests imports to tests bootstrap.
> TSK-580 Add master domain option for classification screens

- rest/taskana-rest-spring-example/src/main/resources/application.properties
- rest/taskana-rest-spring-example/src/main/resources/static/environments/data-sources/environment-information.json
- web/src/environments/environment.prod.ts
Also renamed url from taskana-rest.mybluemix.net to taskana.mybluemix.net
> TSK-536: taskana-rest-example redirect http -> https

- web/src/app/administration/workbasket/master/list/workbasket-list-toolbar/workbasket-list-toolbar.component.html
Bugfix: exporting workbaskets on the workbasket export in admin now
> TSK-449 exporting workbaskets in admin ui

- web/src/app/services/domain/domain.service.ts
TSK-620 Move master domain to dropdown last element
> TSK-620 Move master domain to dropdown last element

- web/src/app/administration/classification/master/list/classification-list.component.ts
- web/src/app/administration/components/filter/filter.component.ts
- web/src/app/administration/services/classifications/classifications.service.ts
- web/src/app/administration/workbasket/master/list/workbasket-list.component.ts
- web/src/app/services/workbasket/workbasket.service.ts
- web/src/app/shared/util/query-parameters.spec.ts
- web/src/app/shared/util/query-parameters.ts
- web/src/environments/environment.prod.ts
- Add query parameters to classification list service in order to  order by key instead of Id
> TSK-622 Add query parameters to classification list service

- web/src/app/administration/classification/details/classification-details.component.spec.ts
- web/src/app/administration/classification/details/classification-details.component.ts
- web/src/app/administration/workbasket/details/information/workbasket-information.component.ts
- web/src/app/app.component.html
- web/src/app/app.component.spec.ts
- web/src/app/app.module.ts
- web/src/app/app.test.configuration.ts
- web/src/app/services/remove-confirmation/remove-confirmation.service.ts
- web/src/app/shared/general-message-modal/general-message-modal.component.ts
- web/src/app/shared/remove-confirmation/remove-confirmation.component.html
- web/src/app/shared/remove-confirmation/remove-confirmation.component.scss
- web/src/app/shared/remove-confirmation/remove-confirmation.component.spec.ts
- web/src/app/shared/remove-confirmation/remove-confirmation.component.ts
- web/src/app/shared/shared.module.ts
- web/src/app/workplace/taskdetails/taskdetails.component.ts
- web/src/app/workplace/tasklist/tasklist-toolbar/tasklist-toolbar.component.html
- Create new remove confirmation component and use it for Classification, workbasket and tasks deletion.
> Tsk-589 Create remove confirmation component

- lib/taskana-core/src/main/java/pro/taskana/BulkOperationResults.java
- lib/taskana-core/src/main/java/pro/taskana/impl/JobTaskRunner.java
- lib/taskana-core/src/test/java/acceptance/task/JobTaskRunnerAccTest.java
- rest/taskana-rest-spring-example/src/main/java/pro/taskana/rest/JobScheduler.java
- Scheduler tasks cleanup job.
- Transactional support on deleting. batchSize = 50
- Retry system when failing on delete tasks. maxRetryOperations = 3
> TSK-567 Create scheduler task job

- web/src/app/administration/workbasket/details/access-items/access-items.component.spec.ts
- web/src/app/administration/workbasket/details/access-items/access-items.component.ts
- Update accesItemsClone onReset access items form.
> TSK-604 BUG Update accesItemsClone onReset access items form.

- web/src/app/shared/tree/tree.component.ts
- web/src/assets/_site.scss
- web/src/assets/_tree.scss
- Added new feature to allow user deselect a node by clicking outside of the tree component.
> TSK-600 Add click outside taskana-tree to deselect node feature

- lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationServiceImpl.java
- lib/taskana-core/src/test/java/pro/taskana/impl/ClassificationServiceImplTest.java
- Allow save classifications when service level is empty
> TSK-616 Allow update classifications with empty service_level

- lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/impl/WorkbasketServiceImpl.java
- Added key and domain for those  exception messages which has access to key and domain values in classification and workbasket services.
> TSK-615 - Add key and domain in error messages.

- web/src/app/administration/classification/details/classification-details.component.html
- web/src/app/administration/classification/details/classification-details.component.ts
- web/src/app/administration/classification/master/list/classification-list.component.html
- web/src/app/shared/spinner/spinner.component.html
- web/src/app/shared/spinner/spinner.component.ts
- web/src/app/shared/tree/tree.component.ts
- web/src/assets/_site.scss
- Solved bug  which makes classification details screen flickers when selecting a classification of creating a new one.
> TSK-610 BUG - Remove flickering on classification details screen

- web/src/app/administration/classification/details/classification-details.component.html
- web/src/app/administration/classification/details/classification-details.component.spec.ts
- web/src/app/administration/classification/details/classification-details.component.ts
- web/src/app/administration/classification/master/list/classification-list.component.spec.ts
- web/src/app/administration/components/type-icon/icon-type.component.spec.ts
- web/src/app/administration/workbasket/details/access-items/access-items.component.html
- web/src/app/administration/workbasket/details/access-items/access-items.component.spec.ts
- web/src/app/administration/workbasket/details/access-items/access-items.component.ts
- web/src/app/administration/workbasket/details/distribution-targets/distribution-targets.component.spec.ts
- web/src/app/administration/workbasket/details/information/workbasket-information.component.html
- web/src/app/administration/workbasket/details/information/workbasket-information.component.spec.ts
- web/src/app/administration/workbasket/details/information/workbasket-information.component.ts
- web/src/app/administration/workbasket/details/workbasket-details.component.spec.ts
- web/src/app/administration/workbasket/details/workbasket-details.component.ts
- web/src/app/app.component.ts
- web/src/app/app.module.ts
- web/src/app/app.test.configuration.ts
- web/src/app/components/user-information/user-information.component.spec.ts
- web/src/app/shared/field-error-display/field-error-display.component.html
- web/src/app/shared/field-error-display/field-error-display.component.spec.ts
- web/src/app/shared/field-error-display/field-error-display.component.ts
- web/src/app/shared/filter/filter.component.spec.ts
- web/src/app/shared/remove-confirmation/remove-confirmation.component.spec.ts
- web/src/app/shared/services/forms/forms-validator.service.ts
- web/src/app/shared/shared.module.ts
- web/src/app/shared/sort/sort.component.spec.ts
- web/src/app/shared/tree/tree.component.spec.ts
- web/src/app/shared/type-ahead/type-ahead.component.html
- web/src/app/shared/type-ahead/type-ahead.component.ts
Only validate fields after form submission.
> TSK-636 Validate fields after submit form

- web/src/app/administration/workbasket/details/distribution-targets/distribution-targets.component.ts
- web/src/app/administration/workbasket/master/list/workbasket-list-toolbar/workbasket-list-toolbar.component.html
- web/src/app/administration/workbasket/master/list/workbasket-list-toolbar/workbasket-list-toolbar.component.ts
- web/src/app/components/user-information/user-information.component.html
- web/src/app/components/user-information/user-information.component.ts
- web/src/app/shared/filter/filter.component.ts
- web/src/app/shared/shared.module.ts
- web/src/app/workplace/tasklist/tasklist-toolbar/tasklist-toolbar.component.html
- web/src/app/workplace/tasklist/tasklist-toolbar/tasklist-toolbar.component.ts
Use animations from animation.ts file instead of creating a new definition for each component.
> TSK-509 use predefined animations

- web/src/app/administration/workbasket/details/distribution-targets/distribution-targets.component.spec.ts
- web/src/app/administration/workbasket/details/distribution-targets/distribution-targets.component.ts
- web/src/app/administration/workbasket/details/distribution-targets/dual-list/dual-list.component.html
- web/src/app/administration/workbasket/details/distribution-targets/dual-list/dual-list.component.ts
- web/src/app/administration/workbasket/master/list/workbasket-list-toolbar/workbasket-list-toolbar.component.html
- web/src/app/components/user-information/user-information.component.html
- web/src/app/shared/animations/expand.animation.ts
- web/src/app/workplace/tasklist/tasklist-toolbar/tasklist-toolbar.component.html
Fixed the filtering of distribution.
Fixed the animation in all place where it is used
> TSK-661 - Filtering of distribution target selection does not work

- web/src/app/administration/workbasket/details/information/workbasket-information.component.ts
- web/src/app/shared/services/forms/forms-validator.service.ts
- If the owner field is not valid the message will be different
- Replace the repetitive string by a property
> TSK-691 - Add snack bar meaningfull message when triying to save a workbasket and owner is not correctly validated.

- .travis.yml
- ci/prepare_db.bat
- ci/prepare_db.sh
- ci/test.sh
Please check here to review the documentation:
https://taskana.atlassian.net/browse/TSK-631
https://taskana.atlassian.net/browse/TSK-632
Note to me: don't forget to delete https://hub.docker.com/r/mustaphazorgati/db2/ after integration
> TSK-631/TSK-632: docker image cleanup + build documentatation

- web/angular.json
- web/package.json
> Revert "TSK-728 - Update bootstrap version"

- lib/taskana-core/src/main/java/pro/taskana/configuration/TaskanaEngineConfiguration.java
- rest/taskana-rest-spring-example/src/main/resources/application.properties
Add 'generateSampleData'-Flag (forgotten in last commit).
> TSK-721-2: Add missing file, correct TYPO, add Flag

- lib/taskana-core/src/main/java/pro/taskana/history/HistoryEventProducer.java
- lib/taskana-core/src/main/java/pro/taskana/history/api/TaskanaHistory.java
- lib/taskana-core/src/main/java/pro/taskana/history/api/TaskanaHistoryEvent.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskanaEngineImpl.java
- lib/taskana-spring-example/src/main/java/pro/taskana/TaskanaConfig.java
This is a first step to implement the ticket TSK-726 because changing the public api requires the code to be pushed for working on changes in TaskanaSimpleHistory repository
> TSK-726 Refactored public api and history event producer to initialize TaskanaHistory implementations

- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/TaskController.java
- web/src/app/shared/filter/filter.component.html
- web/src/app/shared/filter/filter.component.scss
- web/src/app/shared/filter/filter.component.ts
- web/src/app/shared/util/query-parameters.ts
- web/src/app/workplace/tasklist/tasklist-toolbar/tasklist-toolbar.component.html
- web/src/app/workplace/tasklist/tasklist-toolbar/tasklist-toolbar.component.scss
- The filter of state is now a dropdown
- The search by Name and owner is with "LIKE"
> TSK-739 - Fix task list filtering

- lib/taskana-core/src/main/java/pro/taskana/history/api/TaskanaHistoryEvent.java
- lib/taskana-core/src/main/java/pro/taskana/history/events/task/ClaimCancelledEvent.java
- lib/taskana-core/src/main/java/pro/taskana/history/events/task/CompletedEvent.java
- lib/taskana-core/src/main/java/pro/taskana/history/events/task/CreatedEvent.java
- lib/taskana-core/src/main/java/pro/taskana/history/events/task/TransferredEvent.java
> TSK-758 - Rename property type from TaskanaHistoryEvent to eventType

- lib/taskana-core/src/main/java/pro/taskana/impl/ClassificationServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/classification/UpdateClassificationAccTest.java
- If any classification has the same key and parentKey will show an error.
- Modify the updateClassification method to split the functionality into small methods
- Create the test to check the before point
- Fix style mistake
> TSK-771 - Invalid parentKey does not result in appropriate error message

- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/WorkbasketDefinitionController.java
- web/package-lock.json
- web/src/app/administration/services/classification-definition/classification-definition.service.ts
- web/src/app/administration/services/workbasket-definition/workbasket-definition.service.ts
- web/src/app/shared/util/blob-generator.ts
Indentation doesn't work with more basic texts editors like, notepad ... use notepad++ or another one more modern.
> TSK-774 Add indentation to export json files

- rest/taskana-rest-spring-example/src/test/java/pro/taskana/rest/ClassificationDefinitionControllerIntTest.java
- rest/taskana-rest-spring-example/src/test/java/pro/taskana/rest/WorkbasketDefinitionControllerIntTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/ClassificationDefinitionController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/WorkbasketDefinitionController.java
Also, I have added the test to check the returned object
> TSK-787 - Add missing code

- web/jasmine-seed-reporter.js
- web/karma.conf.js
- web/src/app/shared/date-picker/date-picker.component.spec.ts
- web/src/app/shared/date-picker/date-picker.component.ts
- web/src/app/shared/util/query-parameters.spec.ts
-  bug/825 fix random test failing in travis, added seed inspector for future errors
- bug/825 Fix error message in test report due to wrong date initializaion
>  bug/825 fix random test failing in travis, added seed inspector for future errors

- web/src/app/workplace/taskdetails/general/general-fields.component.html
- web/src/app/workplace/taskdetails/general/general-fields.component.ts
- web/src/app/workplace/taskmaster/task-master.component.ts
- Fix the bug. Now the task show his correct associated classification
- Now, the list of classification show which classification is selected
- Fix the bug that broke the application by an undefined subscription
> bug/826 The tasks don't show the correct associated classification

- web/package-lock.json
- web/src/app/models/classification-resource.ts
- web/src/app/services/classifications/classifications.service.ts
- web/src/app/shared/dropdown/dropdown.component.html
- web/src/app/shared/dropdown/dropdown.component.scss
- web/src/app/shared/dropdown/dropdown.component.spec.ts
- web/src/app/shared/dropdown/dropdown.component.ts
- web/src/app/shared/shared.module.ts
- web/src/app/workplace/taskdetails/general/general-fields.component.html
- web/src/app/workplace/taskdetails/general/general-fields.component.spec.ts
- web/src/app/workplace/taskdetails/general/general-fields.component.ts
- web/src/app/workplace/taskdetails/taskdetails.component.ts
- web/src/app/workplace/taskmaster/task-list-toolbar/task-list-toolbar.component.ts
- web/src/assets/_buttons.scss
- The call to get the classifications is just done once.
- Fix the problem when there are two classifications with the same name (now we compare with key property).
- Fix the problem that the list doesn't show every classification.
- Create a new component (dropdown)
- Change subscription to promise async/away
> bug/TSK-809: Duplicated http call when selecting a task in workplaces

- lib/taskana-cdi-example/pom.xml
- lib/taskana-cdi/pom.xml
- lib/taskana-spring-example/pom.xml
- rest/taskana-rest-spring-base/pom.xml
- rest/taskana-rest-spring-example/pom.xml
- rest/taskana-rest-spring-test/pom.xml
- rest/taskana-rest-spring-wildfly-example/pom.xml
- remove repeated dependencies
> task/782 Review POM.xml files from REST

- web/package-lock.json
- web/package.json
- web/src/app/administration/classification/details/classification-details.component.ts
- web/src/app/administration/classification/master/list/classification-list.component.html
- web/src/app/administration/classification/master/list/classification-list.component.ts
- web/src/app/administration/workbasket/details/information/workbasket-information.component.ts
- web/src/app/services/startup-service/startup.service.spec.ts
- web/src/app/services/tree/tree.service.ts
- web/src/app/shared/services/classifications/classifications.service.ts
- web/src/app/shared/shared.module.ts
- web/src/app/shared/tree/tree.component.html
- web/src/app/shared/tree/tree.component.spec.ts
- web/src/app/shared/tree/tree.component.ts
- web/src/app/workplace/task/task.component.ts
Now you can drag the node over the node you want to be its parent (or over none if you want it to be a parent node)
> task/827 Modify classification's parent

- lib/taskana-core/src/main/java/pro/taskana/TaskQuery.java
- rest/taskana-rest-spring-example/src/main/resources/application.properties
Allow larger uploads (up to 10 MB).
Additionally corrected a typo.
> TSK-671: Allow upload of large classification or workbasket files

- pom.xml
> [CLEANUP] moved  eclipse specific setup into seperated profile to reduce build warnings

- web/pom.xml
> TSK-951: Ignore maven javadocs for web build

- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/AbstractPagingController.java
- web/src/app/shared/pagination/pagination.component.html
- web/src/app/shared/pagination/pagination.component.ts
Show the pager in Taskana - Admin - Workbasket only when there is a workbasket
> TSK 885: Remove pager from empty workbasket list

- lib/taskana-core/pom.xml
- lib/taskana-core/src/test/java/pro/taskana/ArchitectureTest.java
- pom.xml
I talked with the team and presented my approach. Much wanted. Here is the pull request again. We can do a follow up with additional rules to test on another ticket.
> TSK-963: Add architecture tests to taskana core

- lib/taskana-core/src/test/java/acceptance/classification/CreateClassificationAccTest.java
- lib/taskana-data/pom.xml
- lib/taskana-data/src/test/java/pro/taskana/sampledata/SampleDataProviderTest.java
- lib/taskana-data/src/test/java/pro/taskana/sampledata/SqlReplacerTest.java
#869 is a prerequisite.
To see the "real" diff: https://github.com/Taskana/taskana/pull/870/files/7d369d1e46d21422b5cada0cb336bd99a2080d2b..051d66ebbffba90b95a1852305f7941eaa09f7c8
EDIT: Done. Can watch files properly
> TSK-1053: refactored taskana-data tests with assertJ

- history/taskana-simplehistory-provider/src/test/java/acceptance/AbstractAccTest.java
- history/taskana-simplehistory-provider/src/test/java/configuration/TaskanaEngineConfigurationTest.java
- history/taskana-simplehistory-spring-test/src/test/java/pro/taskana/doc/api/TaskHistoryEventControllerRestDocumentation.java
- lib/taskana-core/src/main/java/pro/taskana/impl/InternalTaskanaEngine.java
- lib/taskana-core/src/main/java/pro/taskana/impl/TaskanaEngineImpl.java
- lib/taskana-core/src/main/java/pro/taskana/jobs/ScheduledJob.java
- lib/taskana-core/src/main/java/pro/taskana/mappings/JobMapper.java
- lib/taskana-core/src/test/java/pro/taskana/impl/configuration/TaskanaEngineTestConfiguration.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/TaskanaRestExceptionHandler.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/doc/api/WorkbasketAccessItemControllerRestDocumentation.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/WorkbasketControllerIntTest.java
#869 , #870 , #862 are blocking this PR.
real diff: https://github.com/Taskana/taskana/pull/872/commits/cf51d261f2b3173ebc4b0c67140810d21d1d5f5e
> Formatting (automated)

- lib/taskana-core/src/main/java/pro/taskana/WorkbasketService.java
- lib/taskana-core/src/main/java/pro/taskana/exceptions/WorkbasketAccessItemAlreadyExistException.java
- lib/taskana-core/src/main/java/pro/taskana/impl/WorkbasketServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/workbasket/CreateWorkbasketAccTest.java
- lib/taskana-core/src/test/java/acceptance/workbasket/UpdateWorkbasketAuthorizations2AccTest.java
- lib/taskana-core/src/test/java/acceptance/workbasket/UpdateWorkbasketAuthorizationsAccTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/WorkbasketServiceImplTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/WorkbasketController.java
Do not Merge. This is blocked by #869 and #870. 
real diff: https://github.com/Taskana/taskana/pull/871/commits/d8ee80a9793e57ec8c456f34e072edc3df5b2c78
EDIT: files can be viewed normally now.
> Task/1038 fixed error message for workbasketAccessItemAlreadyExistException.

- lib/taskana-core/src/main/java/pro/taskana/history/HistoryEventProducer.java
- lib/taskana-core/src/main/java/pro/taskana/taskrouting/TaskRoutingManager.java
- lib/taskana-core/src/test/java/pro/taskana/impl/TaskAttachmentTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/ClassificationServiceImplIntAutoCommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/impl/integration/TaskServiceImplIntExplicitTest.java
- rest/taskana-rest-spring-example-common/src/main/java/pro/taskana/ldap/LdapCacheTestImpl.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/ldap/LdapCacheTestImpl.java
Last PR of this kind for a while. Made some refactorings to fix more bugs found by Spotbugs.
> Tsk987 spotbugs

- pom.xml
- rest/taskana-rest-spring/pom.xml
- rest/taskana-rest-spring/src/main/java/pro/taskana/ldap/LdapClient.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/ldap/LdapClientTest.java
Working Mockito test for the Ldapclient
> TSK-1024: Add tests for ldapclient

- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/TaskController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/TaskControllerIntTest.java
- rest/taskana-rest-spring/src/test/resources/asciidoc/rest-api.adoc
-Added planned param in filter list
-Implemented needed methods
-Added Test
> TSK-989 Filter Tasks by planned TimeIntervals (REST)

- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/WorkbasketDefinitionController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/WorkbasketDefinitionControllerIntTest.java
Additionally allow a correct update of an workbasketDefinitonResource with existing Key-Domain value.
> TSK-1037: WBDefinitonController accepts existing distributionTargets

- rest/taskana-rest-spring/src/main/java/pro/taskana/ldap/LdapClient.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/ldap/LdapConfiguration.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/ldap/LdapSettings.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/ldap/LdapClientTest.java
This maybe fixes a nullpointer exception that I found while adding tests.
> TSK-1024: Make LdapClient more testable

- lib/taskana-core/src/test/java/pro/taskana/ArchitectureTest.java
More Architecture Tests 
Some need to be enabled and resulting errors need to be fixed
> TSK-991: Add more architecture tests

- lib/taskana-core/src/test/java/pro/taskana/ArchitectureTest.java
small changes to add more dynamic tests and make failures more readable ...
> TSK-991: Make archunit tests more readable

- lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/jobs/TaskCleanupJob.java
- lib/taskana-core/src/main/java/pro/taskana/history/api/events/task/TaskEvent.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/Task.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskSummary.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryMapper.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskSummaryImpl.java
- lib/taskana-core/src/test/java/acceptance/jobs/TaskCleanupJobAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/CallbackStateAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/QueryTasksAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/QueryTasksWithSortingAccTest.java
- lib/taskana-spring-example/src/test/java/pro/taskana/TaskanaTransactionIntTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/resource/TaskSummaryResource.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/resource/TaskSummaryAssemblerTest.java
TaskImpl and TaskSummaryImpl had the same attribute with different names ("id" and "taskID"), that's why "taskID" was renamed "id"
> TSK-1065 Refactor TaskImpl

- history/taskana-simplehistory-provider/src/test/java/acceptance/AbstractAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/util/Pair.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-core/src/test/java/pro/taskana/classification/internal/ClassificationServiceImplIntExplicitTest.java
- lib/taskana-core/src/test/java/pro/taskana/workbasket/internal/WorkbasketServiceImplIntExplicitTest.java
- qa/checkstyle/checkstyle.xml
- rest/taskana-rest-spring-example-common/src/test/java/pro/taskana/jobs/AsyncUpdateJobIntTest.java
@benjamineckstein we already talked about this. This is only adjusted to the new package structure
> TSK-1064: removed DeclarationOrderCheck from checkstyle

- lib/taskana-core/src/main/java/pro/taskana/workbasket/api/WorkbasketService.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/WorkbasketServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/workbasket/UpdateWorkbasketAccTest.java
- lib/taskana-core/src/test/java/pro/taskana/workbasket/internal/WorkbasketServiceImplTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/TaskanaRestExceptionHandler.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/WorkbasketController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/WorkbasketDefinitionController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/WorkbasketControllerIntTest.java
- Added optimistic locking for workbasket update
- Adjusted WorkbasketDefinitionController
- Added tests in UpdateWorkbasketAccTest
- Added tests in WorkbasketControllerIntTest
> TSK-1088 optimistic locking on workbasket update

- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/resource/ClassificationSummaryResource.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/ClassificationControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/ClassificationDefinitionControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/TaskControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/resource/ClassificationSummaryAssemblerTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/resource/TaskResourceAssemberTest.java
TSK-1106 Converted tests to AssertJ
> TSK-1106 Make ClassificationSummaryResource attributes private

- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/ClassificationController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/ClassificationControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/WorkbasketControllerIntTest.java
> TSK-1110: Enforce application/hal+json MediaType for classification and

- history/taskana-simplehistory-spring-test/pom.xml
- history/taskana-simplehistory-spring-test/src/main/resources/application.properties
- pom.xml
- Added overriding beans option to application.json
- Changed junit-vintage-engine version
> TSK-1111 Fix TaskHistoryEventControllerIntTest

- history/taskana-simplehistory-spring-test/pom.xml
- history/taskana-simplehistory-spring-test/src/test/java/pro/taskana/TaskHistoryEventControllerIntTest.java
- history/taskana-simplehistory-spring-test/src/test/java/pro/taskana/doc/api/TaskHistoryEventControllerRestDocumentation.java
and converted tests to AssertJ
> TSK-1135 Removed JUnit 4 dependency in taskana-simplehistory-spring-test

- web/src/app/administration/access-items-management/access-items-management.component.html
- web/src/app/administration/workbasket/details/access-items/access-items.component.html
Renaming of the Output Emitter must be renames within the usage too.
> TSK-1018: Fix Accessitem List displaying no values

- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/TaskController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/RestHelper.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/doc/api/TaskControllerRestDocumentation.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/TaskControllerIntTest.java
- rest/taskana-rest-spring/src/test/resources/asciidoc/rest-api.adoc
-Added endpoint
-Added tests
-updated REST documentation
-removed unnecessary delete documentation from unrelated tests in TaskControllerRestDocumentation
> TSK-1137 Endpoint to cancel claim task for REST-API

- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/resource/ClassificationResourceAssembler.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/resource/ClassificationAssemblerTest.java
> TSK-1140 Corrected ClassificationResourceAssembler

- rest/taskana-rest-spring-example-common/src/test/java/pro/taskana/jobs/AsyncUpdateJobIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/RestHelper.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/AccessIdControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/ClassificationControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/ClassificationDefinitionControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/GeneralExceptionHandlingTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/MappingTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/TaskControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/TaskanaEngineControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/TestSchemaNameCustomizable.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/WorkbasketAccessItemControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/WorkbasketControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/WorkbasketDefinitionControllerIntTest.java
and converted to AssertJ / replaced "fail()" by "assertThatThrownBy()"
Sonarcloud passed: https://sonarcloud.io/dashboard?branch=TSK-1147&id=sofie29_taskana
> TSK-1147 Replaced getRestTemplate() by constant TEMPLATE

- pom.xml
> TSK-1034: Bump spring-restdocs-mockmvc to 2.0.4.RELEASE from

- rest/taskana-rest-spring/src/test/java/pro/taskana/doc/api/BaseRestDocumentation.java
Found the fix here --> https://jaehyun8719.github.io/2019/05/29/springboot/restdocs/
> TSK-1151: fixed pretty printing configuration for spring rest doc

- .gitignore
- lib/taskana-core/src/test/java/acceptance/task/SetPlannedAccTest.java
- fixed the test case
- removed unused code
- added java environment configuration file for jenv in .gitignore
> TSK-1149: fixed test so that the build will also run on macos

- history/taskana-simplehistory-provider/pom.xml
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/SimpleHistoryServiceImpl.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/AbstractAccTest.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/query/QueryHistoryAccTest.java
- history/taskana-simplehistory-provider/src/test/java/configuration/TaskanaEngineConfigurationTest.java
- history/taskana-simplehistory-provider/src/test/java/pro/taskana/simplehistory/impl/HistoryQueryImplTest.java
- history/taskana-simplehistory-provider/src/test/java/pro/taskana/simplehistory/impl/SimpleHistoryServiceImplTest.java
- pom.xml
Sonarcloud passed: https://sonarcloud.io/dashboard?branch=TSK-1142&id=sofie29_taskana
> TSK-1142 Removed JUnit4 dependency in taskana-simplehistory-provider

- web/package.json
- web/src/app/workplace/taskmaster/task-list-toolbar/task-list-toolbar.component.ts
- web/src/polyfills.ts
See https://eslint.org/docs/user-guide/command-line-interface
> TSK-1048: expanded eslint to scan every *.ts file (instead of src/*.ts)

- lib/taskana-core/src/main/java/pro/taskana/workbasket/api/WorkbasketService.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/rest/WorkbasketController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/doc/api/WorkbasketControllerRestDocumentation.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/WorkbasketControllerIntTest.java
- rest/taskana-rest-spring/src/test/resources/asciidoc/rest-api.adoc
- web/src/app/administration/workbasket/details/information/workbasket-information.component.ts
- web/src/app/shared/services/workbasket/workbasket.service.ts
> TSK-1029: Proper distinction between delete and markForFeletion for

- lib/taskana-core/src/main/java/pro/taskana/common/internal/jobs/TaskRefreshJob.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/util/DaysToWorkingDaysConverter.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/models/ObjectReference.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/AttachmentHandler.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/AttachmentMapper.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/ServiceLevelHandler.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/models/TaskImpl.java
- lib/taskana-core/src/test/java/acceptance/persistence/UpdateObjectsUseUtcTimeStampsAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/ServiceLevelOfAllTasksAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/ServiceLevelPriorityAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/SetPlannedAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/UpdateTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/UpdateTaskAttachmentsAccTest.java
Sonar is green: https://sonarcloud.io/dashboard?branch=TSK-1143&id=BerndBreier_taskana
> TSK-1143 UpdateTask with Planned sometimes fails

- lib/taskana-core/src/test/java/pro/taskana/classification/internal/ClassificationServiceImplIntAutoCommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/task/internal/TaskServiceImplIntAutocommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/task/internal/TaskServiceImplIntExplicitTest.java
- pom.xml
- new postgres version 42.2.11
- refactoring of db setup/teardown in test classes
> TSK-1162 new postgres version 42.2.11

- lib/taskana-core/src/main/java/pro/taskana/task/internal/ServiceLevelHandler.java
- lib/taskana-core/src/test/java/acceptance/task/ServiceLevelPriorityAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/UpdateTaskAccTest.java
Sonar is green: https://sonarcloud.io/dashboard?branch=TSK-1177&id=BerndBreier_taskana
> TSK-1177 update Planned of Task if only Due() was changed

- history/taskana-simplehistory-spring-test/src/test/java/pro/taskana/TaskHistoryEventControllerIntTest.java
- history/taskana-simplehistory-spring-test/src/test/java/pro/taskana/TaskHistoryEventResourceAssemblerTest.java
- removed the annoatation @EnableAutoConfiguration
- set id to 45 in should_ReturnSpecificTaskHistoryEventWithDetails_When_SingleEventIsQueried
> TSK-1211: removed the annoatation @EnableAutoConfiguration

- README.md
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/TaskanaHistoryEngineImpl.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/api/reports/header/TimeIntervalColumnHeader.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/preprocessor/WorkingDaysToDaysReportConverter.java
- lib/taskana-core/src/test/java/acceptance/classification/QueryClassificationAccTest.java
fixed the 3 new introduced code smells https://sonarcloud.io/project/issues?id=Taskana_taskana&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL
> fixed newly introduced code smells

- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/jobs/TaskCleanupJob.java
- lib/taskana-core/src/test/java/acceptance/task/DeleteTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/WorkOnTaskAccTest.java
Sonarcloud: https://sonarcloud.io/dashboard?branch=TSK-1195&id=gitgoodjhe_taskana
> TSK-1195: Secure deleteTasks in TaskServiceImpl

- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskCommentServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/task/UpdateTaskCommentAccTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/rest/TaskCommentControllerIntTest.java
Sonarcloud: https://sonarcloud.io/dashboard?branch=TSK-1246&id=gitgoodjhe_taskana
> TSK-1246: Fix updateTaskComment in TaskCommentService

- lib/taskana-core/src/test/java/acceptance/task/CreateTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/ServiceLevelPriorityAccTest.java
and tests don't fail based on todays date anymore
> TSK-1261: test data for task creation's due and planned date calculation is now more robust

- .github/auto-comment.yml
TSK-1284: Updated the autocomment bot
> TSK-1284: Updated the autocomment bot

- .github/auto-comment.yml
sonarcloud: https://sonarcloud.io/dashboard?branch=TSK-1288&id=sofie29_taskana
I updated the PR with the changes we requested in community of practices.
> TSK-1288: Enhance auto-comment bot with checklist from team agreements

- web/src/app/administration/components/classification-details/classification-details.component.ts
- web/src/app/shared/store/classification-store/classification.state.ts
> TSK-1214: Removed unneccessary copie and GET call

- rest/taskana-rest-spring-example-boot/src/main/resources/application.properties
- web/src/app/administration/components/classification-details/classification-details.component.ts
- web/src/app/administration/components/classification-list/classification-list.component.ts
- web/src/app/shared/components/tree/tree.component.ts
- web/src/app/shared/store/classification-store/classification.state.ts
> TSK-1279 Enable the creation of subclassifications

- .github/auto-comment.yml
Small fix for problem introduced by my last PR
> TSK-1300: Fixed problem with link to bluemix environment

- web/src/app/shared/components/tree/tree.component.ts
https://sonarcloud.io/dashboard?branch=TSK-1295&id=sofie29_taskana
> TSK-1295: Tree no longer expands automatically when category is changed

- web/src/app/administration/components/classification-details/classification-details.component.html
- web/src/app/administration/components/classification-details/classification-details.component.spec.ts
- web/src/app/administration/components/classification-details/classification-details.component.ts
Added a Button to copy classifications.
> TSK-1221: Added copy functionality to classifications

- web/src/app/administration/components/classification-details/classification-details.component.spec.ts
- web/src/app/shared/models/action.ts
- web/src/app/shared/store/classification-store/classification.state.ts
Added a new action and added test for creation of classifications
> TSK-1221: Fixed problem with action and added test

- web/src/app/administration/components/classification-details/classification-details.component.ts
The key of classifications did not show, after copying and then selecting another classification.
This has been fixed
> TSK-1221: Fix for key not showing after copy of classification

- web/src/app/shared/store/classification-store/classification.state.ts
https://sonarcloud.io/dashboard?branch=TSK-1312&id=sofie29_taskana
> TSK-1312: Fix bug due to type change while creating a new classification

- web/src/app/monitor/components/classification-report/classification-report.component.html
- web/src/app/monitor/components/classification-report/classification-report.component.ts
- web/src/app/monitor/components/monitor/monitor.component.html
- web/src/app/monitor/components/report-table/report-table.component.ts
- web/src/app/monitor/components/task-report/task-report.component.html
- web/src/app/monitor/components/task-report/task-report.component.ts
- web/src/app/monitor/components/timestamp-report/timestamp-report.component.html
- web/src/app/monitor/components/timestamp-report/timestamp-report.component.ts
- web/src/app/monitor/components/workbasket-report-due-date/workbasket-report-due-date.component.html
- web/src/app/monitor/components/workbasket-report-due-date/workbasket-report-due-date.component.ts
- web/src/app/monitor/components/workbasket-report-planned-date/workbasket-report-planned-date.component.html
- web/src/app/monitor/components/workbasket-report-planned-date/workbasket-report-planned-date.component.ts
- web/src/app/monitor/components/workbasket-report-query-switcher/workbasket-report-query-switcher.component.ts
- web/src/app/monitor/components/workbasket-report/workbasket-report.component.html
- web/src/app/monitor/components/workbasket-report/workbasket-report.component.ts
- web/src/theme/_site.scss
https://sonarcloud.io/dashboard?branch=TSK-1313&id=sofie29_taskana
> TSK-1313: Renamed selectors in monitor component

- web/src/app/administration/components/classification-overview/classification-overview.component.ts
- web/src/app/shared/store/classification-store/classification.state.ts
https://sonarcloud.io/dashboard?branch=TSK-1305&id=sofie29_taskana
> TSK-1305: Adapt classification type when entering a deep link

- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryMapper.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/AbstractAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/SelectAndClaimTaskAccTest.java
- rest/taskana-rest-spring-example-boot/src/main/resources/application-db2.properties
- rest/taskana-rest-spring-example-boot/src/main/resources/application-postgres.properties
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/Mapping.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/doc/api/TaskControllerRestDocumentation.java
- rest/taskana-rest-spring/src/test/resources/asciidoc/rest-api.adoc
Sonarcloud: https://sonarcloud.io/dashboard?branch=TSK-1275&id=gitgoodjhe_taskana
NOTE: uncovered lines are Logger Debugs....
> TSK-1275: Support select and claim in one API call

- history/taskana-simplehistory-rest-spring/src/test/java/pro/taskana/TaskHistoryEventResourceAssemblerTest.java
- lib/taskana-core/src/test/java/acceptance/classification/UpdateClassificationAccTest.java
- lib/taskana-core/src/test/java/acceptance/jobs/WorkbasketCleanupJobAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/CompleteTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/workbasket/QueryWorkbasketAccessItemsAccTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/classification/rest/ClassificationControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/AccessIdControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/RestHelper.java
https://sonarcloud.io/dashboard?branch=sonarqube&id=mustaphazorgati_taskana
> fixed new sonarqube code smells and bugs

- web/src/app/administration/components/classification-list/classification-list.component.ts
- web/src/app/shared/services/domain/domain.service.ts
https://sonarcloud.io/dashboard?branch=TSK-1306&id=Tristan2357_taskana
> TSK-1306: Fixed problem with domain switching in classifications

- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/Mapping.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskCommentController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/classification/rest/ClassificationControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/RestHelper.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/doc/api/TaskCommentControllerRestDocumentation.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskCommentControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
https://sonarcloud.io/dashboard?branch=tsk1317&id=holgerhagen_taskana
> TSK-1317: Fixed task comment authorization tests.

- web/src/app/administration/components/access-items-management/access-items-management.component.ts
- web/src/app/administration/components/classification-details/classification-details.component.ts
- web/src/app/administration/components/classification-list/classification-list.component.html
- web/src/app/administration/components/classification-list/classification-list.component.ts
- web/src/app/administration/components/classification-overview/classification-overview.component.html
- web/src/app/administration/components/classification-overview/classification-overview.component.ts
- web/src/app/administration/components/classification-types-selector/classification-types-selector.component.ts
- web/src/app/administration/components/import-export/import-export.component.ts
- web/src/app/administration/components/type-icon/icon-type.component.ts
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.ts
- web/src/app/administration/components/workbasket-details/workbasket-details.component.html
- web/src/app/administration/components/workbasket-details/workbasket-details.component.ts
- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.html
- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.ts
- web/src/app/administration/components/workbasket-dual-list/workbasket-dual-list.component.html
- web/src/app/administration/components/workbasket-dual-list/workbasket-dual-list.component.ts
- web/src/app/administration/components/workbasket-information/workbasket-information.component.html
- web/src/app/administration/components/workbasket-information/workbasket-information.component.ts
- web/src/app/administration/components/workbasket-list-toolbar/workbasket-list-toolbar.component.html
- web/src/app/administration/components/workbasket-list-toolbar/workbasket-list-toolbar.component.ts
- web/src/app/administration/components/workbasket-list/workbasket-list.component.html
- web/src/app/administration/components/workbasket-list/workbasket-list.component.ts
- web/src/app/shared/components/filter/filter.component.html
- web/src/theme/_site.scss
https://sonarcloud.io/dashboard?branch=TSK-1325&id=sofie29_taskana
> TSK-1325: Renamed selectors in administration component

- web/package-lock.json
For security update https://github.com/Taskana/taskana/network/alert/web/package-lock.json/lodash/closed
> GHSA-p6mc-m468-83gw Security update by npm install

- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
Sonarcloud: https://sonarcloud.io/dashboard?branch=TSK-1336&id=gitgoodjhe_taskana
> TSK-1336: Remove unnecessary warn logging in updateTask()

- web/src/app/shared/components/pagination/pagination.component.html
- web/src/app/shared/components/pagination/pagination.component.spec.ts
Fixed https://taskana.atlassian.net/browse/TSK-1121
> TSK-1121: Workbasket count displaying bugs

- web/src/app/shared/components/dropdown/dropdown.component.ts
- web/src/app/workplace/components/task/task.component.ts
- web/src/app/workplace/components/taskdetails-general/general-fields.component.html
- web/src/app/workplace/components/taskdetails-general/general-fields.component.ts
- web/src/app/workplace/models/task.ts
Fixed problem, which caused the classification of a task in workplace not to be displayed.
> TSK-1340: Classification now gets displayed correctly in Workplace

- rest/taskana-rest-spring/src/main/java/pro/taskana/monitor/rest/MonitorController.java
https://sonarcloud.io/dashboard?branch=TSK-1342&id=Tristan2357_taskana
> TSK-1342: getTasksWorkbasketReport now filters for states

- web/src/app/administration/components/classification-details/classification-details.component.html
- web/src/app/administration/components/classification-details/classification-details.component.spec.ts
- web/src/app/administration/components/classification-details/classification-details.component.ts
- web/src/app/administration/components/classification-list/classification-list.component.ts
- web/src/app/administration/components/classification-overview/classification-overview.component.ts
- web/src/app/administration/components/tree/tree.component.spec.ts
- web/src/app/administration/components/tree/tree.component.ts
- web/src/app/shared/services/http-client-interceptor/http-client-interceptor.service.ts
- web/src/app/shared/store/classification-store/classification.actions.ts
- web/src/app/shared/store/classification-store/classification.selectors.ts
- web/src/app/shared/store/classification-store/classification.state.ts
https://sonarcloud.io/dashboard?branch=TSK-1291&id=sofie29_taskana
> TSK-1291: Removed action property in store to make the code cleaner

- lib/taskana-core/src/test/java/acceptance/report/GetTaskIdsOfClassificationCategoryReportAccTest.java
- web/src/app/administration/components/access-items-management/access-items-management.component.html
- web/src/app/administration/components/access-items-management/access-items-management.component.scss
- web/src/app/administration/components/access-items-management/access-items-management.component.ts
- web/src/app/shared/store/access-items-management-store/access-items-management.actions.ts
- web/src/app/shared/store/access-items-management-store/access-items-management.selector.ts
- web/src/app/shared/store/access-items-management-store/access-items-management.state.ts
- web/src/app/shared/store/index.ts
> TSK-1216: Storing access items management states in NGXS store

- web/angular.json
- web/package-lock.json
- web/package.json
- web/webpack.config.js
New source-map:
Before (without compression)
After (with compression)
> TSK-1354: Optimize webapp size

- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.scss
https://sonarcloud.io/dashboard?branch=TSK-1041&id=sofie29_taskana
> TSK-1041: Fixed accessID table header when scrolling

- history/taskana-simplehistory-provider/src/test/resources/taskana.properties
- lib/taskana-cdi/src/test/java/pro/taskana/RestApplication.java
- lib/taskana-cdi/src/test/java/pro/taskana/TaskanaCdiTestRestController.java
- lib/taskana-cdi/src/test/java/pro/taskana/TaskanaEjb.java
- lib/taskana-cdi/src/test/java/pro/taskana/common/internal/TaskanaProducersTest.java
- lib/taskana-core/src/main/java/pro/taskana/TaskanaEngineConfiguration.java
- lib/taskana-core/src/main/java/pro/taskana/common/api/BaseQuery.java
- lib/taskana-core/src/main/java/pro/taskana/spi/history/api/events/task/TaskEvent.java
- lib/taskana-core/src/main/java/pro/taskana/spi/history/api/events/task/TransferredEvent.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/ObjectReferenceQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/ServiceLevelHandler.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/models/AttachmentImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/models/TaskImpl.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/WorkbasketServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/config/TaskanaConfigAccTest.java
- lib/taskana-core/src/test/java/acceptance/config/TaskanaRoleConfigAccTest.java
- lib/taskana-core/src/test/java/acceptance/security/TaskEngineAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/CompleteTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/CreateTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/DeleteTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/QueryTasksAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/SetOwnerAccTest.java
- lib/taskana-core/src/test/java/acceptance/taskrouting/TaskRoutingAccTest.java
- lib/taskana-core/src/test/java/pro/taskana/common/internal/TaskanaEngineConfigurationTest.java
- lib/taskana-core/src/test/java/pro/taskana/common/internal/TaskanaEngineProxy.java
- lib/taskana-spring-example/src/main/java/pro/taskana/TaskanaConfig.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/classification/rest/ClassificationControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
https://sonarcloud.io/dashboard?branch=code-smells&id=mustaphazorgati_taskana
> TSK-1337: removed some code smells

- web/src/app/workplace/components/task-list-toolbar/task-list-toolbar.component.ts
- web/src/app/workplace/components/task-list/task-list.component.ts
- web/src/app/workplace/components/task-master/task-master.component.ts
- web/src/app/workplace/components/task/task.component.ts
- web/src/app/workplace/services/task.service.ts
https://sonarcloud.io/dashboard?branch=TSK-1338&id=Tristan2357_taskana
> TSK-1338: tasklist now does not refresh after selection of a task

- web/src/app/workplace/components/task/task.component.html
- web/src/app/workplace/components/task/task.component.ts
- web/src/app/workplace/services/task.service.ts
https://sonarcloud.io/dashboard?branch=TSK-1155&id=sofie29_taskana
> TSK-1155: Claiming a task and cancelling a claim works in UI/workplace

- ci/test.sh
- web/cypress/integration/history/history.spec.js
- web/cypress/integration/workbaskets/workbaskets.spec.js
- web/cypress/support/commands.js
Added Tests for workbasket.distribution-targets and workbasket.access-items.
Also added small test for history
> TSK-1366: Expanded e2e tests 

- web/cypress/integration/workbaskets/workbaskets.spec.js
- web/src/app/shared/components/type-ahead/type-ahead.component.html
Hopefully makes the selection more consistent
> TSK-1356: Fixed selector for access items in workbaskets

- web/src/app/administration/components/access-items-management/access-items-management.component.spec.ts
- web/src/app/administration/components/classification-types-selector/classification-types-selector.component.html
- web/src/app/administration/components/classification-types-selector/classification-types-selector.component.spec.ts
> TSK-1349: Added unit test for classification-types-selector component

- web/src/app/administration/components/access-items-management/access-items-management.component.spec.ts
- web/src/app/administration/components/workbasket-details/workbasket-details.component.html
- web/src/app/administration/components/workbasket-details/workbasket-details.component.spec.ts
- web/src/app/administration/components/workbasket-details/workbasket-details.component.ts
- web/src/app/administration/components/workbasket-information/workbasket-information.component.html
- web/src/app/administration/components/workbasket-information/workbasket-information.component.spec.ts
- web/src/app/administration/components/workbasket-information/workbasket-information.component.ts
- web/src/app/shared/store/mock-data/mock-store.ts
https://taskana.atlassian.net/browse/TSK-1349
> TSK-1349: Unit tests for workbasket-details, -information

- web/src/app/administration/components/classification-overview/classification-overview.component.html
- web/src/app/administration/components/classification-overview/classification-overview.component.spec.ts
- web/src/app/administration/components/classification-types-selector/classification-types-selector.component.spec.ts
- web/src/app/shared/store/mock-data/mock-store.ts
> TSK-1349: Added unit test for classification-overview

- web/src/app/administration/components/classification-list/classification-list.component.html
- web/src/app/administration/components/classification-list/classification-list.component.spec.ts
- web/src/app/shared/store/mock-data/mock-store.ts
> TSK-1349: Added unit test for classification-list component

- web/jest.config.js
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.html
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.spec.ts
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.ts
- web/src/app/shared/models/workbasket-access-items.ts
- web/src/app/shared/store/mock-data/mock-store.ts
https://sonarcloud.io/dashboard?branch=TSK-1349-workbasket-access-items&id=cnguyen-de_taskana
https://taskana.atlassian.net/browse/TSK-1349
notes: commits will be squashed during merge
> TSK-1349: Workbasket access items unit tests

- web/src/app/administration/components/type-icon/icon-type.component.spec.ts
- web/src/app/administration/components/type-icon/icon-type.component.ts
> TSK-1349: Added unit test for icon-type component

- web/src/app/administration/components/classification-details/classification-details.component.html
- web/src/app/administration/components/classification-details/classification-details.component.spec.ts
- web/src/app/administration/components/classification-details/classification-details.component.ts
- web/src/app/shared/store/mock-data/mock-store.ts
> TSK-1349: Added unit test for classification-details component

- rest/taskana-rest-spring-example-common/src/test/java/pro/taskana/jobs/AsyncUpdateJobIntTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/assembler/TaskRepresentationModelAssembler.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/assembler/TaskRepresentationModelAssemberTest.java
Sonarcloud: https://sonarcloud.io/dashboard?branch=TSK-1379&id=gitgoodjhe_taskana
> TSK-1379: Verify customAttributes format in taskRepresentationModel

- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
Sonarcloud: https://sonarcloud.io/dashboard?branch=TSK-1382&id=gitgoodjhe_taskana
> TSK-1382: Fix wildcard-search

- web/src/app/shared/components/pagination/pagination.component.ts
- web/src/app/shared/services/forms-validator/forms-validator.service.ts
- web/src/app/workplace/components/task-master/task-master.component.ts
- web/src/app/workplace/components/taskdetails/taskdetails.component.ts
- web/src/app/workplace/services/task.service.ts
sonarcloud: https://sonarcloud.io/dashboard?branch=TSK-1370&id=sofie29_taskana
> TSK-1370: A deleted task is immediately removed from the task list

- web/src/app/monitor/components/report-table/report-table.component.ts
sonarcloud: https://sonarcloud.io/dashboard?branch=TSK-1383&id=sofie29_taskana
> TSK-1383: Solving error in monitor when clicking on last entry in table

- web/src/app/administration/services/classification-tree.service.spec.ts
https://taskana.atlassian.net/browse/TSK-1349
sonarcloud: https://sonarcloud.io/dashboard?branch=TSK-1349&id=sofie29_taskana
> TSK-1349: Added unit test for classification-tree service

- web/src/app/workplace/components/taskdetails-general/general-fields.component.html
- web/src/app/workplace/components/taskdetails-general/general-fields.component.ts
- web/src/app/workplace/components/taskdetails/taskdetails.component.html
- web/src/app/workplace/components/taskdetails/taskdetails.component.ts
https://sonarcloud.io/dashboard?branch=TSK-1371&id=sofie29_taskana
> TSK-1371: Inform user about empty classification when creating a task

- ci/test.sh
- web/angular.json
- web/src/app/app.component.html
- web/src/app/shared/components/nav-bar/nav-bar.component.html
- web/src/theme/_main.scss
- web/src/theme/_ngxbootstrap.scss
This PR only removes bootstrap 3 to create a branch for other members to work on.
> TSK-1394: Remove bootstrap 3

- web/src/app/administration/components/classification-list/classification-list.component.html
- web/src/app/administration/components/import-export/import-export.component.html
- web/src/app/administration/components/import-export/import-export.component.spec.ts
- web/src/app/administration/components/import-export/import-export.component.ts
- web/src/app/administration/services/classification-definition.service.ts
- web/src/app/administration/services/workbasket-definition.service.ts
- web/src/app/app.component.ts
- web/src/app/shared/services/forms-validator/forms-validator.service.ts
- web/src/app/shared/services/upload/upload.service.ts
Added test for import and export.
> TSK-1349: Added test for import-export

- web/src/app/administration/components/workbasket-information/workbasket-information.component.spec.ts
... and fixed console error during tests.
https://sonarcloud.io/dashboard?branch=TSK-1392&id=sofie29_taskana
> TSK-1392: Ensure that a new workbasket is selected after saving

- common/taskana-common-test/src/test/java/pro/taskana/common/test/security/JaasExtensionTest.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/ClassificationHistoryQueryImpl.java
- history/taskana-simplehistory-rest-spring/src/test/java/pro/taskana/doc/api/TaskHistoryEventControllerRestDocumentation.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/WorkbasketAccessItemControllerIntTest.java
> TSK-1414: Fixed most of the new SonaCloud Code Smells since 4.0.2-SNAPSHOT

- common/taskana-common-data/pom.xml
- common/taskana-common-data/src/main/java/pro/taskana/sampledata/SqlReplacer.java
> SqlReplacer now using DB#isDb2

- .travis.yml
So that the adapter can use them
---
> TSK-1415: released all common modules to maven central

- common/taskana-common/src/main/resources/sql/postgres/taskana_schema_update_2.0.2_to_3.0.0_postgres.sql
- common/taskana-common/src/main/resources/sql/postgres/taskana_schema_update_3.0.0_to_4.0.0_postgres.sql
> TSK-1417: fix update scripts postgres

- web/src/app/administration/administration.module.ts
- web/src/app/administration/components/access-items-management/access-items-management.component.scss
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.html
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.scss
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.spec.ts
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.ts
- web/src/app/shared/components/nav-bar/nav-bar.component.html
- web/src/app/shared/store/workbasket-store/workbasket.state.ts
- web/src/theme/_site.scss
- Rework how save/undo work internally.
- Update UI to be compatible without bootstrap
- Added accessibility, ability to tab/shift+tab through elements
https://taskana.atlassian.net/browse/TSK-1411
---
> TSK-1411: Update Update Workbasket Access Items Component MD

- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/classification/ClassificationHistoryQuery.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/query/QueryClassificationHistoryAccTest.java
> TSK-1428: fixed tests for QueryClassificationHistory due to current date

- web/src/app/administration/components/access-items-management/access-items-management.component.html
- web/src/app/administration/components/access-items-management/access-items-management.component.spec.ts
- web/src/app/administration/components/access-items-management/access-items-management.component.ts
- web/src/app/administration/components/administration-overview/administration-overview.component.ts
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.spec.ts
- web/src/app/administration/components/workbasket-information/workbasket-information.component.html
- web/src/app/administration/components/workbasket-information/workbasket-information.component.scss
- web/src/app/administration/components/workbasket-information/workbasket-information.component.spec.ts
- web/src/app/administration/components/workbasket-list/workbasket-list.component.scss
- web/src/app/app.component.html
- web/src/app/app.component.scss
- web/src/app/app.component.ts
- web/src/app/app.module.ts
- web/src/app/shared/components/filter/filter.component.scss
- web/src/app/shared/components/nav-bar/nav-bar.component.html
- web/src/app/shared/components/pagination/pagination.component.scss
- web/src/app/shared/components/sidenav-list/sidenav-list.component.html
- web/src/app/shared/components/sidenav-list/sidenav-list.component.scss
- web/src/app/shared/components/sort/sort.component.scss
- web/src/app/shared/components/type-ahead/type-ahead.component.html
- web/src/app/shared/components/type-ahead/type-ahead.component.scss
- web/src/app/shared/components/type-ahead/type-ahead.component.spec.ts
- web/src/app/shared/components/type-ahead/type-ahead.component.ts
- web/src/app/shared/services/access-ids/access-ids.service.ts
- web/src/app/shared/shared.module.ts
> TSK-1401: Update Typeahead component with material design

- .travis.yml
https://sonarcloud.io/dashboard?branch=Task%2F1438&id=SAllhusen_taskana
---
> TSK-1438: explicitly listed all releasable modules in travis config file

- common/taskana-common/src/main/java/pro/taskana/common/api/BaseQuery.java
- common/taskana-common/src/main/java/pro/taskana/common/api/exceptions/NotFoundException.java
- history/taskana-simplehistory-rest-spring/src/test/java/pro/taskana/doc/api/TaskHistoryEventControllerRestDocumentation.java
- lib/taskana-core/src/main/java/pro/taskana/classification/internal/jobs/ClassificationChangedJob.java
- lib/taskana-core/src/main/java/pro/taskana/classification/internal/models/ClassificationImpl.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/reports/TimeIntervalReportBuilderImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/jobs/TaskCleanupJob.java
- lib/taskana-core/src/test/java/acceptance/classification/CreateClassificationAccTest.java
- lib/taskana-core/src/test/java/acceptance/classification/DeleteClassificationAccTest.java
- lib/taskana-core/src/test/java/acceptance/classification/GetClassificationAccTest.java
- lib/taskana-core/src/test/java/acceptance/objectreference/QueryObjectReferenceAccTest.java
- lib/taskana-core/src/test/java/acceptance/report/GetTaskIdsOfWorkbasketReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/security/ClassificationQueryAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/CreateTaskCommentAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/QueryTaskByClassificationNameAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/QueryTaskWithAttachmentAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/QueryTasksAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/UpdateTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/workbasket/GetWorkbasketAccTest.java
- lib/taskana-core/src/test/java/acceptance/workbasket/QueryWorkbasketAccTest.java
https://sonarcloud.io/dashboard?branch=Task%2F1437&id=SAllhusen_taskana
---
> TSK-1437: Fixed some SonarCloud Code Smells

- lib/taskana-core/src/main/java/pro/taskana/classification/internal/models/ClassificationImpl.java
- lib/taskana-core/src/main/java/pro/taskana/common/api/ScheduledJob.java
- lib/taskana-core/src/main/java/pro/taskana/spi/history/api/events/classification/ClassificationHistoryEvent.java
- lib/taskana-core/src/main/java/pro/taskana/spi/history/api/events/task/TaskHistoryEvent.java
- lib/taskana-core/src/main/java/pro/taskana/spi/history/api/events/workbasket/WorkbasketHistoryEvent.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/models/AttachmentSummaryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/models/MinimalTaskSummary.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/models/TaskCommentImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/models/TaskSummaryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/models/WorkbasketImpl.java
> TSK-1416: Truncation of Instant Membervariables

- common/taskana-common-test/src/test/java/pro/taskana/common/test/security/JaasExtensionTest.java
- common/taskana-common-test/src/test/java/pro/taskana/common/test/security/JaasExtensionTestExtensions.java
> TSK-1444: enable disabled tests for JaasExtension

- .travis.yml
> TSK-1282: provide gpg passphrase during key import

- .travis.yml
> TSK-1282: fixed build by properly importing gpg key

- pom.xml
- rest/taskana-rest-spring-example-wildfly/src/test/resources/module.xml
> TSK-1452: update to Spring Boot 2.3.5

- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/task/CompleteTaskAccTest.java
> TSK-1441: Enable Admin to complete tasks already claimed by other users

- .travis.yml
> TSK-1282: finally found a fix for the gpg issue

- .gitignore
- .mvn/wrapper/MavenWrapperDownloader.java
- .mvn/wrapper/maven-wrapper.properties
- mvnw
- mvnw.cmd
> TSK-1461: added maven-wrapper

- .travis.yml
- ci/change_version.sh
- ci/compile.sh
- ci/test.sh
> TSK-1463: travis now using maven-wrapper

- sonar-project.properties
This is done in order to enable the XSS vulnerabilities check
---
> TSK-1464: now adding thymeleaf template to sonar index

- web/src/app/shared/components/pagination/pagination.component.html
- web/src/app/shared/components/pagination/pagination.component.ts
> TSK-1451: Add input field to pagination component

- web/src/app/administration/components/workbasket-overview/workbasket-overview.component.spec.ts
- web/src/app/administration/components/workbasket-overview/workbasket-overview.component.ts
> TSK-1460: Add ID to path when the workbasket component is selected

- web/src/app/administration/components/access-items-management/access-items-management.component.html
- web/src/app/administration/components/access-items-management/access-items-management.component.scss
- web/src/app/app.component.scss
- web/src/app/shared/components/sort/sort.component.html
- web/src/app/shared/components/sort/sort.component.scss
- web/src/app/shared/components/sort/sort.component.ts
> TSK-1466: Fix bug in sort component 

- web/src/app/administration/components/access-items-management/access-items-management.component.html
> TSK-1470: remove table closing tag

- ci/docker-compose.yml
- ci/prepare_db.bat
- ci/prepare_db.sh
- rest/taskana-rest-spring-example-boot/src/main/resources/application-db2.properties
- rest/taskana-rest-spring-example-boot/src/main/resources/application-postgres.properties
- rest/taskana-rest-spring-example-boot/src/main/resources/application.properties
- rest/taskana-rest-spring-example-wildfly/src/test/resources/int-test-standalone.xml
> TSK-1471: now using docker-compose for all database containers

- history/taskana-simplehistory-provider/src/test/java/acceptance/events/classification/CreateHistoryEventOnClassificationsCreationAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/classification/CreateClassificationAccTest.java
- lib/taskana-core/src/test/java/acceptance/classification/UpdateClassificationAccTest.java
- lib/taskana-core/src/test/java/acceptance/persistence/UpdateObjectsUseUtcTimeStampsAccTest.java
- lib/taskana-core/src/test/java/pro/taskana/classification/internal/ClassificationServiceImplIntAutoCommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/classification/internal/ClassificationServiceImplIntExplicitTest.java
- lib/taskana-core/src/test/java/pro/taskana/task/internal/TaskServiceImplIntAutocommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/task/internal/TaskServiceImplIntExplicitTest.java
- lib/taskana-spring-example/src/main/java/pro/taskana/ExampleBootstrap.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/classification/rest/ClassificationControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/classification/rest/ClassificationDefinitionControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/doc/api/ClassificationControllerRestDocumentation.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/doc/api/ClassificationDefinitionControllerRestDocumentation.java
> TSK-1419: Null check for Service Level in classification service

- README.md
> TSK-1480: updated travis-ci badge to link to new repo

- qa/intellij/taskana_formatter_intellij.xml
> TSK-1482: adapted custom taskana formatter changes to new formatter

- web/src/app/administration/components/workbasket-list/workbasket-list.component.ts
> TSK-1484: Fix pagination bug

- web/src/app/administration/components/workbasket-list-toolbar/workbasket-list-toolbar.component.html
- web/src/app/administration/components/workbasket-list-toolbar/workbasket-list-toolbar.component.scss
- web/src/app/administration/components/workbasket-list-toolbar/workbasket-list-toolbar.component.ts
- web/src/app/administration/components/workbasket-list/workbasket-list.component.html
- web/src/app/administration/components/workbasket-list/workbasket-list.component.scss
- web/src/app/administration/components/workbasket-list/workbasket-list.component.spec.ts
- web/src/app/administration/components/workbasket-list/workbasket-list.component.ts
- web/src/app/administration/components/workbasket-overview/workbasket-overview.component.html
- web/src/app/administration/components/workbasket-overview/workbasket-overview.component.scss
- web/src/app/administration/components/workbasket-overview/workbasket-overview.component.spec.ts
- web/src/app/administration/components/workbasket-overview/workbasket-overview.component.ts
- web/src/app/shared/components/pagination/pagination.component.html
- web/src/app/shared/components/pagination/pagination.component.scss
- web/src/app/shared/components/pagination/pagination.component.ts
https://taskana.atlassian.net/browse/TSK-1475
---
> TSK-1475: Hide mechanism workbasket list

- lib/taskana-core/src/main/java/pro/taskana/workbasket/api/WorkbasketService.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/WorkbasketServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/workbasket/UpdateWorkbasketAccTest.java
> TSK-1468: Added validation of name and type of workbasket when updating Workbasket

- common/taskana-common-test/src/main/resources/taskana-test.ldif
- history/taskana-simplehistory-rest-spring/src/test/resources/application.properties
- rest/taskana-rest-spring-example-boot/src/main/resources/application-db2.properties
- rest/taskana-rest-spring-example-boot/src/main/resources/application-postgres.properties
- rest/taskana-rest-spring-example-boot/src/main/resources/application.properties
- rest/taskana-rest-spring-example-common/src/main/resources/taskana-example.ldif
- rest/taskana-rest-spring-example-common/src/test/java/pro/taskana/ldap/LdapTest.java
- rest/taskana-rest-spring-example-common/src/test/resources/application.properties
- rest/taskana-rest-spring-example-wildfly/src/main/resources/application-postgres.properties
- rest/taskana-rest-spring-example-wildfly/src/main/resources/application.properties
- rest/taskana-rest-spring-example-wildfly/src/test/resources/application-postgres.properties
- rest/taskana-rest-spring-example-wildfly/src/test/resources/application.properties
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/ldap/LdapClient.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/ldap/LdapSettings.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/ldap/LdapClientTest.java
- rest/taskana-rest-spring/src/test/resources/application.properties
> TSK-1423: Implemented the option to search for an Access Id by the full name of the user

- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.ts
- web/src/app/shared/store/workbasket-store/workbasket.state.ts
> TSK-1488: fixed error while saving workbasket information

- web/src/app/administration/components/classification-details/classification-details.component.html
- web/src/app/administration/components/classification-details/classification-details.component.scss
- web/src/app/administration/components/classification-list/classification-list.component.html
- web/src/app/administration/components/classification-list/classification-list.component.scss
- web/src/app/administration/components/classification-list/classification-list.component.spec.ts
- web/src/app/administration/components/classification-overview/classification-overview.component.scss
- web/src/theme/_tree.scss
also change headline in classification details to have a max length to not bump the buttons to overflow when headline's length is too long
---
> TSK-1479: fixed classification tree not displaying all items

- web/src/app/shared/components/pagination/pagination.component.html
- web/src/app/shared/components/pagination/pagination.component.ts
> TSK-1487: fix bug in pagination input field

- web/src/app/administration/components/workbasket-information/workbasket-information.component.html
- web/src/app/administration/components/workbasket-information/workbasket-information.component.ts
> TSK-1483: Fixed error when entering an owner in a new workbasket

- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.ts
- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.ts
- web/src/app/administration/components/workbasket-information/workbasket-information.component.ts
> TSK-1485: implement save all components in save button

- web/src/app/history/history.module.ts
- web/src/app/history/task-history-query/task-history-query.component.html
- web/src/app/history/task-history-query/task-history-query.component.scss
- web/src/app/history/task-history-query/task-history-query.component.ts
- web/src/app/shared/models/task-history-event.ts
This is done to fix the breaking api changes
---
> TSK-1436: replaced history table view with material table

- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.ts
> TSK-1393: fix wrong import

- web/src/app/administration/components/access-items-management/access-items-management.component.spec.ts
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.html
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.scss
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.spec.ts
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.ts
- web/src/app/administration/components/workbasket-details/workbasket-details.component.html
- web/src/app/administration/components/workbasket-details/workbasket-details.component.spec.ts
- web/src/app/administration/components/workbasket-details/workbasket-details.component.ts
- web/src/app/administration/components/workbasket-overview/workbasket-overview.component.html
- web/src/app/administration/components/workbasket-overview/workbasket-overview.component.spec.ts
- web/src/app/shared/components/type-ahead/type-ahead.component.html
- web/src/app/shared/components/type-ahead/type-ahead.component.ts
- web/src/environments/data-sources/taskana-customization.json
> TSK-1476: Rework workbasket access items

- web/src/app/administration/components/access-items-management/access-items-management.component.ts
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.ts
- web/src/app/history/services/task-history-query/task-history-query.service.ts
- web/src/app/history/task-history-query/task-history-query.component.html
- web/src/app/history/task-history-query/task-history-query.component.scss
Renamed css classes in task-history-query, moved pagination to the bottom and made the page scrollable in x-direction.
---
> TSK-1493: Small changes in task-history-query

- rest/taskana-rest-spring/src/main/java/pro/taskana/workbasket/rest/WorkbasketController.java
- web/src/app/shared/models/workbasket-access-items-representation.ts
- web/src/app/shared/services/workbasket/workbasket.service.ts
- web/src/app/shared/store/workbasket-store/workbasket.state.ts
> TSK-1436: fixed breaking REST API change for workbasketAccessItems

- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.html
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.ts
- web/src/app/administration/components/workbasket-information/workbasket-information.component.ts
> TSK-1496: Fixed error in console when creating new workbasket

- common/taskana-common-data/src/main/java/pro/taskana/sampledata/SampleDataGenerator.java
- common/taskana-common-data/src/main/java/pro/taskana/sampledata/SqlReplacer.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/configuration/DB.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/configuration/DbSchemaCreator.java
- history/taskana-simplehistory-provider/src/test/java/pro/taskana/simplehistory/impl/SimpleHistoryServiceImplTest.java
- history/taskana-simplehistory-rest-spring/src/main/java/pro/taskana/simplehistory/rest/TaskHistoryEventController.java
- lib/taskana-cdi/src/main/java/pro/taskana/common/internal/TaskanaProducers.java
- lib/taskana-core/src/main/java/pro/taskana/TaskanaEngineConfiguration.java
- lib/taskana-core/src/main/java/pro/taskana/TaskanaEngineConfiguration.java.BASE
- lib/taskana-core/src/main/java/pro/taskana/TaskanaEngineConfiguration.java.LOCAL
- lib/taskana-core/src/main/java/pro/taskana/TaskanaEngineConfiguration.java.REMOTE
- lib/taskana-core/src/main/java/pro/taskana/common/internal/TaskanaEngineImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java
- lib/taskana-core/src/test/java/acceptance/config/TaskanaSecurityConfigAccTest.java
- lib/taskana-core/src/test/java/pro/taskana/classification/internal/ClassificationServiceImplIntAutoCommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/common/internal/TaskanaEngineTestConfiguration.java
- lib/taskana-core/src/test/java/pro/taskana/task/internal/TaskServiceImplIntAutocommitTest.java
- lib/taskana-spring-example/src/main/java/pro/taskana/TaskanaConfig.java
- lib/taskana-spring/src/main/java/pro/taskana/SpringTaskanaEngineConfiguration.java
- lib/taskana-spring/src/main/java/pro/taskana/common/internal/SpringTaskanaEngineImpl.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/RestConfiguration.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/TestSchemaNameCustomizable.java
> TSK-1472: Replaced the DB check with productName by productId

- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.html
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.spec.ts
- web/src/app/administration/components/workbasket-details/workbasket-details.component.html
- web/src/app/administration/components/workbasket-details/workbasket-details.component.scss
- web/src/app/administration/components/workbasket-information/workbasket-information.component.html
- web/src/app/shared/components/type-ahead/type-ahead.component.html
> TSK-1502: Small improvements in workbasket details

- .github/workflows/continuous-integration.yml
> TSK-1497: removed sonar job from pull requests & removed run on branch creation

- .github/workflows/continuous-integration.yml
- README.md
- pom.xml
> TSK-1497 various improvements

- pom.xml
> TSK-1497: fixed code coverage report xml path (final)

- .github/workflows/continuous-integration.yml
> TSK-1497: fixed deploy job by re-enabling javadoc generation for rest

- lib/taskana-core/src/main/java/pro/taskana/workbasket/api/exceptions/WorkbasketAlreadyExistException.java
- lib/taskana-core/src/test/java/acceptance/task/CompleteTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/TransferTaskAccTest.java
> TSK-1498: Created specific error message if workbasket already existing

- .github/workflows/continuous-integration.yml
> TSK-1497: disabled sonarqube on release and specified tag

- web/src/app/administration/components/access-items-management/access-items-management.component.html
- web/src/app/administration/components/access-items-management/access-items-management.component.scss
- web/src/app/administration/components/access-items-management/access-items-management.component.spec.ts
- web/src/app/administration/components/access-items-management/access-items-management.component.ts
- web/src/app/administration/components/classification-list/classification-list.component.html
- web/src/app/administration/components/classification-list/classification-list.component.scss
- web/src/app/administration/components/classification-list/classification-list.component.spec.ts
- web/src/app/shared/components/workbasket-filter/workbasket-filter.component.html
- web/src/app/shared/components/workbasket-filter/workbasket-filter.component.scss
The way I modified the all-icon should only be temporary. I'll create a ticket.
---
> TSK-1523: Small changes in access-items and modified all-icon

- web/src/app/workplace/components/task-list-toolbar/task-list-toolbar.component.html
- web/src/app/workplace/components/task-list-toolbar/task-list-toolbar.component.scss
- web/src/app/workplace/components/task-list-toolbar/task-list-toolbar.component.ts
- web/src/app/workplace/workplace.module.ts
https://sonarcloud.io/dashboard?branch=TSK-1490&id=sofie29_taskana
---
> TSK-1490: Fix autocomplete in workplace workbasket search

- common/taskana-common/src/main/java/pro/taskana/common/api/BaseQuery.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/ClassificationHistoryQueryImpl.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/TaskHistoryQueryImpl.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/WorkbasketHistoryQueryImpl.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/query/QueryClassificationHistoryAccTest.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/query/QueryTaskHistoryAccTest.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/query/QueryWorkbasketHistoryAccTest.java
> TSK-1355: Adjust all single() methods to use mybatis selectOne

- lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/classification/CreateClassificationAccTest.java
> TSK-1115: Validate that Service Level is not negative

- lib/taskana-core/src/main/java/pro/taskana/classification/api/exceptions/ClassificationAlreadyExistException.java
> TSK-1421: Specific error message if classification already existing

- web/src/app/administration/components/classification-details/classification-details.component.html
- web/src/app/administration/components/classification-details/classification-details.component.scss
- web/src/app/administration/components/classification-details/classification-details.component.spec.ts
- web/src/app/administration/components/workbasket-details/workbasket-details.component.html
- web/src/app/administration/components/workbasket-details/workbasket-details.component.scss
- web/src/app/administration/components/workbasket-details/workbasket-details.component.spec.ts
> TSK-1527: Modify how badge messages are displayed

- web/src/app/administration/components/classification-overview/classification-overview.component.spec.ts
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.scss
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.spec.ts
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.ts
- web/src/app/administration/components/workbasket-information/workbasket-information.component.spec.ts
- web/src/app/administration/components/workbasket-list-toolbar/workbasket-list-toolbar.component.spec.ts
- web/src/app/shared/components/type-ahead/type-ahead.component.html
- web/src/app/shared/components/type-ahead/type-ahead.component.spec.ts
> TSK-1043: Fix access-items table width

- lib/taskana-core/src/test/java/pro/taskana/classification/internal/ClassificationServiceImplIntAutoCommitTest.java
- lib/taskana-core/src/test/java/pro/taskana/classification/internal/ClassificationServiceImplIntExplicitTest.java
- lib/taskana-core/src/test/java/pro/taskana/task/internal/TaskServiceImplIntAutocommitTest.java
> TSK-1529: fixed database cleanup for failing test classes

- web/src/app/shared/services/http-client-interceptor/http-client-interceptor.service.ts
Relates to [TSK-1421](https://taskana.atlassian.net/browse/TSK-1421). Solves the problem by removing the error message in the HttpInterceptor. However, this issue should be considered again in combination with [TSK-1202](https://taskana.atlassian.net/browse/TSK-1202). 
---
> TSK-1528: Remove duplicated error message when creating a classification

- common/taskana-common/src/main/java/pro/taskana/common/internal/util/ListUtil.java
- common/taskana-common/src/test/java/pro/taskana/common/api/ListUtilTest.java
- history/taskana-loghistory-provider/pom.xml
- history/taskana-simplehistory-provider/pom.xml
- lib/taskana-core/pom.xml
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/jobs/TaskCleanupJob.java
- lib/taskana-core/src/test/java/acceptance/task/QueryTasksAccTest.java
- lib/taskana-core/src/test/java/pro/taskana/task/internal/TaskQueryImplTest.java
> TSK-1506: Fixed bug for Cleanup Jobs with more than 32767 tasks

- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.spec.ts
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.ts
- web/src/app/shared/store/mock-data/mock-store.ts
> TSK-1431: Sort workbasket access items by accessId

- web/src/app/administration/components/classification-list/classification-list.component.html
- web/src/app/administration/components/workbasket-distribution-targets-list/workbasket-distribution-targets-list.component.html
- web/src/app/administration/components/workbasket-distribution-targets-list/workbasket-distribution-targets-list.component.spec.ts
- web/src/app/shared/pipes/order-by.pipe.ts
> TSK-1433: Sort distribution targets by type and description

- common/taskana-common/src/main/java/pro/taskana/common/internal/util/CollectionUtil.java
- common/taskana-common/src/test/java/pro/taskana/common/api/CollectionUtilTest.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/jobs/HistoryCleanupJob.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/jobs/HistoryCleanupJobAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/jobs/TaskCleanupJob.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/jobs/WorkbasketCleanupJob.java
- lib/taskana-core/src/test/java/acceptance/jobs/TaskCleanupJobAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/QueryTasksAccTest.java
> TSK-1499: Fixed bug of also cleaning completed tasks with parentProcessId null/empty

- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.html
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.spec.ts
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.ts
https://sonarcloud.io/dashboard?branch=TSK-1044&id=sofie29_taskana
---
> TSK-1044: Fix selectAll checkbox

- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/jobs/HistoryCleanupJob.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/jobs/HistoryCleanupJobAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/JobMapper.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/JobServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/jobs/AbstractTaskanaJob.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/jobs/TaskCleanupJob.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/jobs/WorkbasketCleanupJob.java
- lib/taskana-core/src/test/java/acceptance/jobs/TaskCleanupJobAccTest.java
- lib/taskana-core/src/test/java/acceptance/jobs/WorkbasketCleanupJobAccTest.java
> TSK-1504: Next scheduled job now based on due date of previous job

- common/taskana-common/src/main/java/pro/taskana/common/api/BaseQuery.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/classification/ClassificationHistoryEventMapper.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/classification/ClassificationHistoryQueryMapper.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/task/TaskHistoryEventMapper.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/task/TaskHistoryQueryMapper.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/workbasket/WorkbasketHistoryEventMapper.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/workbasket/WorkbasketHistoryQueryMapper.java
- lib/taskana-cdi/src/main/java/pro/taskana/common/internal/TaskanaProducers.java
- lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationMapper.java
- lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationQueryMapper.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/JobMapper.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/MonitorMapper.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/AttachmentMapper.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/ObjectReferenceMapper.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskCommentMapper.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskMapper.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryMapper.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/WorkbasketAccessMapper.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/WorkbasketMapper.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/WorkbasketQueryMapper.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/jobs/WorkbasketCleanupJob.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/models/WorkbasketImpl.java
- lib/taskana-core/src/test/java/acceptance/report/ProvideClassificationReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/report/ProvideDetailedClassificationReportAccTest.java
- lib/taskana-core/src/test/java/pro/taskana/task/internal/TaskTestMapper.java
> TSK-1507: Cleaned up some CodeSmells

- rest/taskana-rest-spring/src/docs/asciidoc/rest-api.adoc
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/RestEndpoints.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerRestDocTest.java
> TSK-1530: Add a REST endpoint to cancel a task

- web/src/app/shared/pipes/date-time-zone.pipe.ts
- web/src/app/workplace/components/task-list/task-list.component.html
- web/src/app/workplace/components/task-list/task-list.component.scss
- web/src/app/workplace/components/task-list/task-list.component.spec.ts
- web/src/app/workplace/components/task-list/task-list.component.ts
- web/src/app/workplace/components/task-master/task-master.component.ts
- web/src/app/workplace/workplace.module.ts
> TSK-1540: Rework task-list component with Angular Material

- web/src/app/shared/components/master-and-detail/master-and-detail.component.html
- web/src/app/shared/components/master-and-detail/master-and-detail.component.scss
Component will be renamed in another ticket: https://taskana.atlassian.net/browse/TSK-1556
---
> TSK-1553: Rework master-and-details with Angular Material

- web/src/app/shared/components/sort/sort.component.html
- web/src/app/workplace/components/task-list-toolbar/task-list-toolbar.component.html
- web/src/app/workplace/components/task-list-toolbar/task-list-toolbar.component.scss
- web/src/app/workplace/components/task-list/task-list.component.html
- web/src/app/workplace/components/task-master/task-master.component.ts
- web/src/app/workplace/workplace.module.ts
> TSK-1547: Rework task-list-toolbar component with Angular Material

- lib/taskana-core/src/main/java/pro/taskana/common/internal/jobs/JobRunner.java
- lib/taskana-core/src/test/java/pro/taskana/ArchitectureTest.java
- pom.xml
> TSK-1552: Updated archunit version to 0.16.0

- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.html
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.ts
> TSK-1556: Fix indexing in workbasket access items

- web/src/app/administration/components/classification-overview/classification-overview.component.scss
> TSK-1564: Fix classification list width

- web/src/app/shared/pipes/order-by.pipe.ts
https://sonarcloud.io/dashboard?branch=TSK-1560&id=sofie29_taskana
---
> TSK-1560: TSK-1558: Fix error when displaying distribution targets

- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.ts
> TSK-1044: Correct checking of 'select all' checkbox in access items

- web/src/app/administration/components/workbasket-distribution-targets-list/workbasket-distribution-targets-list.component.html
- web/src/app/administration/components/workbasket-distribution-targets-list/workbasket-distribution-targets-list.component.spec.ts
- web/src/app/administration/components/workbasket-distribution-targets-list/workbasket-distribution-targets-list.component.ts
- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.html
- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.spec.ts
- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.ts
- web/src/app/administration/components/workbasket-list-toolbar/workbasket-list-toolbar.component.html
- web/src/app/administration/components/workbasket-list-toolbar/workbasket-list-toolbar.component.spec.ts
- web/src/app/administration/components/workbasket-list-toolbar/workbasket-list-toolbar.component.ts
- web/src/app/administration/components/workbasket-list/workbasket-list.component.html
- web/src/app/administration/components/workbasket-list/workbasket-list.component.spec.ts
- web/src/app/administration/components/workbasket-list/workbasket-list.component.ts
- web/src/app/administration/components/workbasket-overview/workbasket-overview.component.ts
- web/src/app/shared/components/workbasket-filter/workbasket-filter.component.html
- web/src/app/shared/components/workbasket-filter/workbasket-filter.component.ts
- web/src/app/shared/store/filter-store/filter.actions.ts
- web/src/app/shared/store/filter-store/filter.selectors.ts
- web/src/app/shared/store/filter-store/filter.state.ts
- web/src/app/shared/store/index.ts
- web/src/app/shared/store/workbasket-store/workbasket.state.ts
https://sonarcloud.io/dashboard?branch=TSK-1562&id=sofie29_taskana
---
> TSK-1562: Reset filter when changing workbasket and move filter to store

- .github/workflows/continuous-integration.yml
documentation:
- https://taskana.atlassian.net/wiki/spaces/TAS/pages/1821935692/Continuous+Integration+GitHub+Actions
SonarCloud not provided since this is only a change in workflow file. 
---
> TSK-1548: now using PAT of admin for release job

- common/taskana-common/src/main/java/pro/taskana/common/internal/util/ComparableVersion.java
- common/taskana-common/src/test/java/pro/taskana/common/api/CollectionUtilTest.java
- history/taskana-simplehistory-rest-spring/src/main/java/pro/taskana/simplehistory/rest/TaskHistoryEventController.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/JobMapper.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/MonitorMapper.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/reports/ClassificationCategoryReportBuilderImpl.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/reports/ClassificationReportBuilderImpl.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/reports/TaskCustomFieldValueReportBuilderImpl.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/reports/TimeIntervalReportBuilderImpl.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/reports/TimestampReportBuilderImpl.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/reports/WorkbasketReportBuilderImpl.java
- lib/taskana-core/src/test/java/acceptance/config/TaskanaSecurityConfigAccTest.java
- lib/taskana-core/src/test/java/acceptance/workbasket/QueryWorkbasketAccTest.java
- lib/taskana-core/src/test/java/pro/taskana/ArchitectureTest.java
- lib/taskana-core/src/test/java/pro/taskana/monitor/internal/ClassificationClassificationCategoryReportBuilderImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/monitor/internal/ClassificationReportBuilderImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/monitor/internal/TaskCustomFieldValueReportBuilderImplTest.java
- lib/taskana-core/src/test/java/pro/taskana/monitor/internal/WorkbasketReportBuilderImplTest.java
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/example/wildfly/AbstractAccTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/classification/rest/assembler/ClassificationDefinitionCollectionRepresentationModel.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/classification/rest/models/ClassificationDefinitionRepresentationModel.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskQueryFilterParameter.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/workbasket/rest/WorkbasketController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/classification/rest/ClassificationDefinitionControllerIntTest.java
> TSK-1572: replaced "CURRENT_TIMESTAMP" sql function with Instant

- common/taskana-common-test/src/main/java/pro/taskana/common/test/security/JaasExtension.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/util/CheckedFunction.java
- lib/taskana-core/src/test/java/acceptance/task/ServiceLevelPriorityAccTest.java
https://sonarcloud.io/dashboard?branch=task%2F1571&id=mustaphazorgati_taskana
---
> TSK-1571: fixed test which breaks after 22:00 local time

- lib/taskana-core/src/main/java/pro/taskana/common/internal/TaskanaEngineImpl.java
> TSK-1577: passing properly initialized TaskanaEngine during SPI initialization

- rest/taskana-rest-spring-example-boot/src/main/resources/application-db2.properties
- rest/taskana-rest-spring-example-boot/src/main/resources/application-postgres.properties
- rest/taskana-rest-spring-example-boot/src/main/resources/application.properties
- rest/taskana-rest-spring-example-wildfly/src/main/resources/application-postgres.properties
- rest/taskana-rest-spring-example-wildfly/src/main/resources/application.properties
> TSK-1361: Configure Spring Boot to serve gzip files

- history/taskana-simplehistory-rest-spring/src/main/java/pro/taskana/simplehistory/rest/TaskHistoryEventController.java
- history/taskana-simplehistory-rest-spring/src/test/java/pro/taskana/simplehistory/rest/TaskHistoryEventControllerIntTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/classification/rest/ClassificationController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/QuerySortParameter.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/util/QueryParamsValidator.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/workbasket/rest/WorkbasketAccessItemController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/workbasket/rest/WorkbasketController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/workbasket/rest/assembler/WorkbasketRepresentationModelAssembler.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/classification/rest/ClassificationControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerRestDocTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/WorkbasketAccessItemControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/WorkbasketControllerIntTest.java
> TSK-1544: Throw error for unknown query parameter

- web/src/app/workplace/components/task-master/task-master.component.ts
- web/src/app/workplace/services/task.service.ts
> TSK-1574: add workbasket-id as filter parameter

- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.ts
- web/src/app/shared/store/workbasket-store/workbasket.state.ts
> TSK-1573: Reset distribution targets filter after saving a workbasket

- lib/taskana-core/src/main/java/pro/taskana/common/internal/jobs/AbstractTaskanaJob.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java
- lib/taskana-core/src/test/java/acceptance/jobs/TaskCleanupJobAccTest.java
> TSK-1555: Initialize due of Cleanup Job based on firstRun

- web/src/app/administration/components/tree/tree.component.html
- web/src/app/administration/components/tree/tree.component.scss
- web/src/app/administration/components/tree/tree.component.ts
https://sonarcloud.io/dashboard?branch=TSK-1564&id=sofie29_taskana
---
> TSK-1564: Make scrolling in classification list smoother

- web/src/app/workplace/components/task-list-toolbar/task-list-toolbar.component.ts
https://sonarcloud.io/dashboard?branch=TSK-1580&id=sofie29_taskana
---
> TSK-1580: Load workbasket of current user in workplace after login

- common/taskana-common-test/pom.xml
- history/taskana-simplehistory-rest-spring/pom.xml
- pom.xml
- rest/taskana-rest-spring/pom.xml
reason: https://discourse.hibernate.org/t/hibernate-validator-7-and-spring-mvc-5-3-2-compatible/4927
---
> TSK-1519: replaced hibernate dependency with spring-starter-validation

- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskTransferrer.java
- lib/taskana-core/src/test/java/acceptance/task/TransferTaskAccTest.java
- qa/checkstyle/checkstyle.xml
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
> TSK-1538: Added transfer method with control setTransferFlag

- .github/workflows/continuous-integration.yml
> TSK-1589: Updated Nodejs to latest LTS version

- common/taskana-common-test/src/main/java/pro/taskana/common/test/rest/RestHelper.java
- history/taskana-simplehistory-rest-spring/src/test/java/pro/taskana/simplehistory/rest/TaskHistoryEventControllerIntTest.java
- rest/taskana-rest-spring-example-common/src/test/java/pro/taskana/example/jobs/AsyncUpdateJobIntTest.java
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/example/wildfly/AbstractAccTest.java
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/example/wildfly/TaskanaWildflyTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/classification/rest/ClassificationControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/classification/rest/ClassificationDefinitionControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/AccessIdControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/GeneralExceptionHandlingTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/TaskanaEngineControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskCommentControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/WorkbasketAccessItemControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/WorkbasketControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/WorkbasketDefinitionControllerIntTest.java
https://sonarcloud.io/dashboard?branch=task%2F1594&id=mustaphazorgati_taskana
---
> TSK-1594:  inlined RestHelper#defaultRequest

- .github/workflows/continuous-integration.yml
- ci/ibm_cf_manifest.yml
> TSK-1595: updated IBM/cloudfoundry-deploy action to version 2.0

- lib/taskana-core/src/test/java/acceptance/config/TaskanaConfigAccTest.java
- lib/taskana-core/src/test/java/acceptance/config/TaskanaRoleConfigAccTest.java
> TSK-1223: Replace folder generation in tests with Junit5 TempDir

- common/taskana-common-test/src/main/resources/taskana-test.ldif
- rest/taskana-rest-spring-example-common/src/main/resources/taskana-example.ldif
> TSK-1609: fixed password for user-2-2

- common/taskana-common/src/main/java/pro/taskana/common/api/exceptions/TaskanaException.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/util/ObjectAttributeChangeDetector.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/TaskanaEngineImpl.java
- pom.xml
> TSK-1611: updated checkstyle to 8.41.1

- .github/workflows/continuous-integration.yml
> TSK-1615: updated setup-java action to v2

- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.ts
- web/src/app/shared/components/task-filter/task-filter.component.html
- web/src/app/shared/components/task-filter/task-filter.component.scss
- web/src/app/shared/components/task-filter/task-filter.component.ts
- web/src/app/shared/components/workbasket-filter/workbasket-filter.component.ts
- web/src/app/shared/store/filter-store/filter.actions.ts
- web/src/app/shared/store/filter-store/filter.selectors.ts
- web/src/app/shared/store/filter-store/filter.state.ts
- web/src/app/shared/store/workbasket-store/workbasket.state.ts
- web/src/app/workplace/components/task-list-toolbar/task-list-toolbar.component.html
- web/src/app/workplace/components/task-list/task-list.component.html
... and wrote input values into the filter store. Search and clear buttons are deleted and will be part of the task-list-toolbar PR.
---
> TSK-1554: Reworked task-filter component with Angular Material

- ci/prepare_db.bat
- ci/prepare_db.sh
- lib/taskana-core/src/test/java/acceptance/AbstractAccTest.java
- lib/taskana-core/src/test/java/acceptance/TaskanaEngineTestConfiguration.java
> TSK-1617: Fixed unit tests when creating db2 with prepare_db.bat script

- common/taskana-common-test/src/main/java/pro/taskana/common/test/config/TaskanaEngineTestConfiguration.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/util/FileLoaderUtil.java
- lib/taskana-core/src/main/java/pro/taskana/TaskanaEngineConfiguration.java
- lib/taskana-core/src/main/java/pro/taskana/common/api/TaskanaEngine.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/InternalTaskanaEngine.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/TaskanaEngineImpl.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/reports/TaskStatusReportBuilderImpl.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/reports/WorkbasketReportBuilderImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/WorkbasketServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/task/SetOwnerAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/TaskEngineAccTest.java
- pom.xml
- rest/taskana-rest-spring-example-boot/src/main/java/pro/taskana/example/boot/ExampleRestConfiguration.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/RestConfiguration.java
- taskana-routing-parent/pom.xml
- taskana-routing-parent/taskana-spi-routing-dmn-router/pom.xml
- taskana-routing-parent/taskana-spi-routing-dmn-router/src/main/java/pro/taskana/routing/dmn/DmnTaskRouter.java
- taskana-routing-parent/taskana-spi-routing-dmn-router/src/test/java/acceptance/AbstractAccTest.java
- taskana-routing-parent/taskana-spi-routing-dmn-router/src/test/java/pro/taskana/routing/dmn/DmnTaskRouterTest.java
- taskana-routing-parent/taskana-spi-routing-dmn-router/src/test/resources/META-INF/services/pro.taskana.spi.routing.api.TaskRoutingProvider
- taskana-routing-parent/taskana-spi-routing-dmn-router/src/test/resources/dmn-table.dmn
- taskana-routing-parent/taskana-spi-routing-dmn-router/src/test/resources/taskana.properties
> TSK-1628: New DmnTaskRouter module

- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/assembler/TaskRepresentationModelAssembler.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/assembler/TaskSummaryRepresentationModelAssembler.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/assembler/TaskRepresentationModelAssemberTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/assembler/TaskSummaryRepresentationModelAssemblerTest.java
> TSK-1567: Fixed creating a task using a TaskRouter

- common/taskana-common-test/src/main/java/pro/taskana/common/test/config/TaskanaEngineTestConfiguration.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/util/ComparableVersion.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/util/FileLoaderUtil.java
- history/taskana-simplehistory-rest-spring/src/test/resources/taskana.properties
- lib/taskana-core/src/main/java/pro/taskana/TaskanaEngineConfiguration.java
- lib/taskana-core/src/test/java/acceptance/config/TaskanaConfigAccTest.java
- lib/taskana-core/src/test/java/acceptance/config/TaskanaEngineConfigTest.java
- lib/taskana-core/src/test/java/acceptance/config/TaskanaRoleConfigAccTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/assembler/TaskRepresentationModelAssembler.java
- taskana-routing-parent/pom.xml
- taskana-routing-parent/taskana-spi-routing-dmn-router/pom.xml
- taskana-routing-parent/taskana-spi-routing-dmn-router/src/main/java/pro/taskana/routing/dmn/DmnTaskRouter.java
- taskana-routing-parent/taskana-spi-routing-dmn-router/src/test/java/pro/taskana/routing/dmn/DmnTaskRouterTest.java
> TSK-1628: cleanup of code smells & refactoring

- rest/taskana-rest-spring/src/test/java/pro/taskana/classification/rest/ClassificationControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/classification/rest/ClassificationDefinitionControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/AccessIdControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/GeneralExceptionHandlingTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/TaskanaEngineControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/monitor/rest/MonitorControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskCommentControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/WorkbasketAccessItemControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/WorkbasketControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/WorkbasketDefinitionControllerIntTest.java
> TSK-1597: Unified HTTP Request in Rest Tests

- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/TaskanaRestExceptionHandler.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/models/TaskanaErrorData.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/GeneralExceptionHandlingTest.java
> TSK-1543: Throw expressive error when REST parameter cannot be converted

- web/src/app/administration/components/workbasket-distribution-targets-list/workbasket-distribution-targets-list.component.html
- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.html
- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.spec.ts
- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.ts
> TSK-1626: Swap lists of available and selected distribution targets

- web/src/app/administration/components/workbasket-list/workbasket-list.component.html
- web/src/app/administration/components/workbasket-list/workbasket-list.component.scss
> TSK-1625: List items in workbasket list now readable if the content is too long

- web/src/app/shared/store/index.ts
- web/src/app/shared/store/workplace-store/workplace.actions.ts
- web/src/app/shared/store/workplace-store/workplace.selectors.ts
- web/src/app/shared/store/workplace-store/workplace.state.ts
- web/src/app/workplace/components/task-list-toolbar/task-list-toolbar.component.html
- web/src/app/workplace/components/task-list-toolbar/task-list-toolbar.component.ts
- web/src/app/workplace/components/task-master/task-master.component.ts
> TSK-1613: Introduce store in Workplace and prevent scrolling in Task list

- rest/taskana-rest-spring/src/docs/asciidoc/rest-api.adoc
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/RestEndpoints.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerRestDocTest.java
> TSK-1635: Make forceCancelClaim of a task available in the REST-API

- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskQueryFilterParameter.java
> TSK-1623: Make like query filters for tasks available in the REST-API

- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/ldap/LdapClient.java
> TSK-1610: Replaced hardcoded user id attribute

- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/task/CreateTaskAccTest.java
> TSK-795: Changed Exception when creating a Task with a non-empty taskId

- common/taskana-common/src/main/java/pro/taskana/common/internal/util/ObjectAttributeChangeDetector.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/util/Pair.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/util/Triplet.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/events/task/CreateHistoryEventOnTaskTransferAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/spi/history/api/events/task/TaskTransferredEvent.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskMapper.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskTransferrer.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/models/TaskSummaryImpl.java
- lib/taskana-core/src/test/java/acceptance/task/QueryTasksAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/TransferTaskAccTest.java
- qa/hooks/pre-commit
https://sonarcloud.io/dashboard?branch=task%2F1642&id=mustaphazorgati_taskana
---
> TSK-1642: now setting details attribute for TaskTransferHistoryEvent

- web/src/app/administration/components/workbasket-distribution-targets-list/workbasket-distribution-targets-list.component.html
- web/src/app/administration/components/workbasket-distribution-targets-list/workbasket-distribution-targets-list.component.scss
> TSK-1652: Adapt view in WorkbasketDistributionTargets for long data

- web/browserslist
documentation links:
- https://taskana.atlassian.net/wiki/spaces/TAS/pages/1758593073/Supported+Environments
---
> TSK-1653: configured browserslist according to our supported environments

- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/jobs/HistoryCleanupJob.java
- history/taskana-simplehistory-rest-spring/src/main/java/pro/taskana/simplehistory/rest/TaskHistoryEventController.java
- lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/ObjectReferenceQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/jobs/TaskCleanupJob.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/AbstractWorkbasketAccessItemQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/WorkbasketAccessItemQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/WorkbasketQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/WorkbasketServiceImpl.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/classification/rest/ClassificationController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/classification/rest/ClassificationDefinitionController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/TaskanaEngineController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/assembler/AttachmentRepresentationModelAssembler.java
https://sonarcloud.io/dashboard?branch=task%2F1654&id=mustaphazorgati_taskana
---
> TSK-1654: fixed current code smells

- rest/taskana-rest-spring-example-boot/src/main/java/pro/taskana/example/boot/security/BootWebSecurityConfigurer.java
- rest/taskana-rest-spring-example-boot/src/main/resources/application.properties
- web/src/app/app.module.ts
- web/src/app/shared/services/http-client-interceptor/http-client-interceptor.service.ts
Since backend doesn't provide any XSRF Token, this implementation isn't yet tested. 
New change is compatible with the current backend, all requests are sent and reponses are received as expected.
According to https://angular.io/api/common/http/HttpClientXsrfModule, the cookie name XSRF-TOKEN and the header name X-XSRF-TOKEN would be created when the server supports a cookie-based XSRF protection system
---
> TSK-1651: Add XSRF Support

- common/taskana-common/src/main/java/pro/taskana/common/internal/util/ObjectAttributeChangeDetector.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/events/task/CreateHistoryEventOnTaskTransferAccTest.java
https://sonarcloud.io/dashboard?branch=task%2F1642-2&id=mustaphazorgati_taskana
---
> TSK-1642: now resolving complex objects during change detection properly

- history/taskana-simplehistory-rest-spring/src/main/java/pro/taskana/simplehistory/rest/TaskHistoryEventController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/classification/rest/ClassificationController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/workbasket/rest/WorkbasketController.java
> TSK-1661: Added sort-by parameters for all entities.

- common/taskana-common-test/src/main/resources/taskana-test.ldif
- rest/taskana-rest-spring-example-common/src/test/java/pro/taskana/example/ldap/LdapEmptySearchRootsTest.java
- rest/taskana-rest-spring-example-common/src/test/java/pro/taskana/example/ldap/LdapTest.java
- rest/taskana-rest-spring-example-common/src/test/resources/application-emptySearchRoots.properties
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/AccessIdController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/ldap/LdapClient.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/AccessIdControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/ldap/LdapClientTest.java
> TSK-1308: Retrieve users by DN without using userSearchBase.

- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/TaskanaHistoryEngineImpl.java
> TSK-1668: simplehistory-provider now presisting timestamps at UTC

- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskQueryFilterParameter.java
https://sonarcloud.io/dashboard?branch=TSK-1656&id=Tristan2357_taskana
---
> TSK-1656: Added from and until for created and completed

- rest/taskana-rest-spring-example-common/src/test/java/pro/taskana/example/ldap/LdapEmptySearchRootsTest.java
- rest/taskana-rest-spring-example-common/src/test/java/pro/taskana/example/ldap/LdapTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/ldap/LdapClientTest.java
> TSK-1308: Format corrections.

- common/taskana-common-data/src/main/java/pro/taskana/sampledata/SampleDataGenerator.java
- common/taskana-common-security/src/main/java/pro/taskana/common/internal/security/CurrentUserContextImpl.java
- common/taskana-common-test/src/main/java/pro/taskana/common/test/BaseRestDocTest.java
- common/taskana-common-test/src/main/java/pro/taskana/common/test/rest/RestHelper.java
- history/taskana-simplehistory-rest-spring/src/test/java/pro/taskana/simplehistory/rest/TaskHistoryEventControllerIntTest.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/models/ObjectReference.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/task/CreateTaskAccTest.java
- rest/taskana-rest-spring-example-common/src/test/java/pro/taskana/example/jobs/AsyncUpdateJobIntTest.java
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/example/wildfly/AbstractAccTest.java
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/example/wildfly/TaskanaWildflyTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/classification/rest/ClassificationControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/classification/rest/ClassificationDefinitionControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/AccessIdControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/GeneralExceptionHandlingTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/TaskanaEngineControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/monitor/rest/MonitorControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskCommentControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerRestDocTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/WorkbasketAccessItemControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/WorkbasketControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/WorkbasketDefinitionControllerIntTest.java
> TSK-1664: fixed some code smells and redesigned RestHelper

- .run/All in taskana-common-data.run.xml
- .run/All in taskana-common-logging.run.xml
- .run/All in taskana-common-test.run.xml
- .run/All in taskana-common.run.xml
- .run/All in taskana-core.run.xml
- .run/All in taskana-loghistory-provider.run.xml
- .run/All in taskana-rest-spring-example-common.run.xml
- .run/All in taskana-rest-spring.run.xml
- .run/All in taskana-simplehistory-provider.run.xml
- .run/All in taskana-simplehistory-rest-spring.run.xml
- .run/All in taskana-spi-routing-dmn-router.run.xml
- .run/All in taskana-spring-example.run.xml
- .run/Build Backend No Checkstyle.run.xml
- .run/Build Backend.run.xml
- .run/Clean Install.run.xml
- .run/Db2.run.xml
- .run/Debug Frontend.run.xml
- .run/Postgres.run.xml
- .run/Prepare RestDocs History.run.xml
- .run/Prepare RestDocs.run.xml
- .run/Start DevMode ExampleRestApplication.run.xml
- .run/Start ExampleRestApplication.run.xml
- .run/Start Frontend.run.xml
- .run/Stop all DB.run.xml
- .run/Test E2E.run.xml
- .run/Test Frontend.run.xml
https://sonarcloud.io/dashboard?id=Tristan2357_taskana&branch=TSK-1672
https://taskana.atlassian.net/wiki/spaces/TAS/pages/2114617357/Backend+Development
---
> TSK-1672: Added run configurations

- .run/Start Demo App DevMode.run.xml
- .run/Start Demo App No CSRF.run.xml
- .run/Start Demo App.run.xml
- rest/taskana-rest-spring/src/main/java/pro/taskana/classification/rest/ClassificationQueryFilterParameter.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/classification/rest/ClassificationControllerIntTest.java
Co-authored-by: Sofie Hofmann<29145005+sofie29@users.noreply.github.com>
https://sonarcloud.io/dashboard?branch=task%2F1677&id=mustaphazorgati_taskana
---
> TSK-1677: fixed retrieval of all master classifications

- web/src/app/administration/components/administration-overview/administration-overview.component.html
- web/src/app/administration/components/classification-details/classification-details.component.spec.ts
- web/src/app/administration/components/classification-details/classification-details.component.ts
- web/src/app/shared/services/forms-validator/forms-validator.service.ts
- web/src/app/shared/services/notifications/notification.service.ts
- web/src/app/shared/services/obtain-message/message-by-error-code.ts
- web/src/app/shared/services/obtain-message/message-types.ts
> TSK-1678: Show error when saving empty WorkbasketAccessItem

- web/src/app/shared/store/classification-store/classification.state.ts
> TSK-1679: Prevent multiple calls of getClassifications

- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/TaskanaRestExceptionHandler.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/classification/rest/ClassificationControllerIntTest.java
> TSK-1676: Fixed REST Exception Mapping for *InUseExceptions.

- lib/taskana-core/pom.xml
- rest/taskana-rest-spring/pom.xml
- rest/taskana-rest-spring/src/main/java/pro/taskana/classification/rest/ClassificationQueryFilterParameter.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/QueryPagingParameter.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/QuerySortParameter.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskQueryFilterParameter.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/workbasket/rest/WorkbasketQueryFilterParameter.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/SpringArchitectureTest.java
https://sonarcloud.io/dashboard?branch=TSK-1666&id=Tristan2357_taskana
---
> TSK-1666: Cheap Fix

- web/src/app/administration/components/classification-details/classification-details.component.html
- web/src/app/administration/components/classification-details/classification-details.component.spec.ts
- web/src/app/administration/components/classification-details/classification-details.component.ts
- web/src/app/administration/components/workbasket-information/workbasket-information.component.html
- web/src/app/administration/components/workbasket-information/workbasket-information.component.spec.ts
- web/src/app/administration/components/workbasket-information/workbasket-information.component.ts
- web/src/app/shared/services/forms-validator/forms-validator.service.ts
> TSK-1683: Saving Workbaskets and Classifications custom fields corrected

- .github/workflows/continuous-integration.yml
- common/taskana-common/src/main/java/pro/taskana/common/internal/configuration/SecurityVerifier.java
- lib/taskana-core/src/test/java/acceptance/config/TaskanaSecurityConfigAccTest.java
https://sonarcloud.io/dashboard?branch=task%2F1691&id=mustaphazorgati_taskana
---
> TSK-1691: made TASKANA v4.7.X compatible with v.4.8.X

- common/taskana-common-logging/pom.xml
- pom.xml
> TSK-1688: Changed AspectJ plugin to mojo

- .mvn/wrapper/MavenWrapperDownloader.java
- common/taskana-common-logging/pom.xml
- lib/taskana-core/src/main/java/pro/taskana/monitor/api/reports/TimeIntervalReportBuilder.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/MonitorMapper.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/reports/TimeIntervalReportBuilderImpl.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/WorkbasketAccessItemQueryImpl.java
- lib/taskana-core/src/test/java/acceptance/report/ProvideClassificationCategoryReportAccTest.java
- pom.xml
- rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/WorkbasketControllerIntTest.java
> TSK-1693: automatic reformatting

- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/routing/IntegrationTestTaskRouter.java
- rest/taskana-rest-spring/src/test/resources/META-INF/services/pro.taskana.spi.routing.api.TaskRoutingProvider
> TSK-1701: added integration test for task routing via REST API.

- common/taskana-common-logging/src/main/java/pro/taskana/common/internal/logging/LoggingAspect.java
- common/taskana-common-logging/src/test/java/outside/of/pro/staskana/OutsideOfProTaskanaPackageLoggingTestClass.java
- common/taskana-common-logging/src/test/java/pro/taskana/AtProTaskanaRootPackageLoggingTestClass.java
- common/taskana-common-logging/src/test/java/pro/taskana/common/internal/logging/LoggingAspectTest.java
https://sonarcloud.io/dashboard?branch=task%2F1708&id=mustaphazorgati_taskana
---
> TSK-1708: The JointPoint for our LoggingAspect now only looks for classes within pro.taskana package

- common/taskana-common-logging/pom.xml
- common/taskana-common-logging/src/main/java/pro/taskana/common/internal/logging/LoggingAspect.java
- common/taskana-common-logging/src/test/java/pro/taskana/common/internal/logging/LoggingAspectTest.java
- common/taskana-common-logging/src/test/java/pro/taskana/common/internal/logging/LoggingTestClass.java
- common/taskana-common-logging/src/test/java/pro/taskana/common/internal/logging/NoLoggingTestClass.java
- common/taskana-common-logging/src/test/java/pro/taskana/common/internal/logging/NoLoggingTestSubClass.java
- lib/taskana-core/src/test/java/acceptance/task/QueryTasksAccTest.java
updated doc:
* https://taskana.atlassian.net/wiki/spaces/TAS/pages/2200567863/Enable+TRACE+Logging+with+Logging+AspectJ
sonar:
* https://sonarcloud.io/dashboard?branch=task%2F1709&id=mustaphazorgati_taskana
---
es](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
> TSK-1709: optimized LoggingAspect

- lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/InternalTaskanaEngine.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/TaskanaEngineImpl.java
- lib/taskana-core/src/main/java/pro/taskana/spi/priority/api/PriorityServiceProvider.java
- lib/taskana-core/src/main/java/pro/taskana/spi/priority/internal/PriorityServiceManager.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/ArchitectureTest.java
- lib/taskana-core/src/test/java/acceptance/priorityservice/PriorityServiceAccTest.java
- lib/taskana-core/src/test/java/acceptance/priorityservice/TestPriorityServiceProvider.java
> TSK-1686: Introduced an SPI for the individual calculation of priorities

- lib/taskana-core/src/main/java/pro/taskana/TaskanaEngineConfiguration.java
- lib/taskana-core/src/main/java/pro/taskana/common/api/ScheduledJob.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/jobs/AbstractTaskanaJob.java
- lib/taskana-core/src/main/java/pro/taskana/spi/priority/internal/PriorityServiceManager.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/jobs/TaskUpdatePriorityJob.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/jobs/helper/SqlConnectionRunner.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/jobs/helper/TaskUpdatePriorityBatchStatement.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/jobs/helper/TaskUpdatePriorityWorker.java
- lib/taskana-core/src/test/java/acceptance/jobs/TaskUpdatePriorityJobAccTest.java
- lib/taskana-core/src/test/java/acceptance/jobs/helper/SqlConnectionRunnerAccTest.java
- lib/taskana-core/src/test/java/acceptance/jobs/helper/TaskUpdatePriorityBatchStatementAccTest.java
- lib/taskana-core/src/test/java/acceptance/jobs/helper/TaskUpdatePriorityWorkerAccTest.java
https://sonarcloud.io/dashboard?id=benjamineckstein_taskana
---
> TSK-1705: Add a job to update priority for unfinished tasks

- common/taskana-common-logging/src/main/java/pro/taskana/common/internal/logging/LoggingAspect.java
- common/taskana-common-logging/src/test/java/outside/of/pro/taskana/OutsideOfProTaskanaPackageLoggingTestClass.java
- common/taskana-common-logging/src/test/java/pro/taskana/AtProTaskanaRootPackageLoggingTestClass.java
- common/taskana-common-logging/src/test/java/pro/taskana/common/internal/logging/LoggingAspectTest.java
https://sonarcloud.io/dashboard?branch=task%2F1717&id=mustaphazorgati_taskana
---
> TSK-1717: The JointPoint for our LoggingAspect now only looks for classes within pro.taskana package

- common/taskana-common/src/main/java/pro/taskana/common/internal/configuration/DbSchemaCreator.java
- common/taskana-common/src/test/java/pro/taskana/common/internal/util/LogSanitizerTest.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/TaskHistoryQueryImpl.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/WorkbasketHistoryQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/jobs/AbstractTaskanaJob.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/SpringArchitectureTest.java
https://sonarcloud.io/dashboard?branch=TSK-1710&id=LiaLissmann_taskana
---
> TSK-1710: Fixed a few code smells

- web/src/app/administration/components/workbasket-distribution-targets-list/workbasket-distribution-targets-list.component.html
- web/src/app/administration/components/workbasket-distribution-targets-list/workbasket-distribution-targets-list.component.spec.ts
> TSK-1720: Sort Workbasket Distribution Targets by type and name

- common/taskana-common-logging/pom.xml
- common/taskana-common-logging/src/main/java/pro/taskana/common/internal/logging/LoggingAspect.java
- common/taskana-common-logging/src/test/java/pro/taskana/common/internal/logging/LoggingAspectTest.java
- common/taskana-common-logging/src/test/java/pro/taskana/common/internal/logging/LoggingTestClass.java
- common/taskana-common-logging/src/test/java/pro/taskana/common/internal/logging/NoLoggingTestClass.java
- common/taskana-common-logging/src/test/java/pro/taskana/common/internal/logging/NoLoggingTestSubClass.java
- lib/taskana-core/src/test/java/acceptance/task/QueryTasksAccTest.java
docs:
* https://taskana.atlassian.net/wiki/spaces/TAS/pages/2200567863/Enable+TRACE+Logging+with+Logging+AspectJ
sonar:
* https://sonarcloud.io/dashboard?branch=task%2F1719&id=mustaphazorgati_taskana
* 
---
> TSK-1719: optimized LoggingAspect

- lib/taskana-core/src/main/java/pro/taskana/task/internal/AttachmentMapper.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
DISCLAIMER: This contains no tests because nothing, outside of performance, has changed.
Before refactoring I made sure that the methods I touched were tested to ensure that I didn't break anything ;)
The execution time has been reduced from O(n²) to O(n)
https://sonarcloud.io/dashboard?branch=task%2F1718&id=mustaphazorgati_taskana
---
> TSK-1718: Performance optimization for TaskService#getTask and TaskQuery#list

- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/jobs/HistoryCleanupJob.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/jobs/HistoryCleanupJobAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/classification/internal/jobs/ClassificationChangedJob.java
- lib/taskana-core/src/main/java/pro/taskana/common/api/ScheduledJob.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/JobMapper.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/JobServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/jobs/AbstractTaskanaJob.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/jobs/TaskCleanupJob.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/jobs/TaskRefreshJob.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/jobs/TaskUpdatePriorityJob.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/jobs/WorkbasketCleanupJob.java
- lib/taskana-core/src/test/java/acceptance/jobs/JobRunnerAccTest.java
- lib/taskana-core/src/test/java/acceptance/jobs/TaskCleanupJobAccTest.java
- lib/taskana-core/src/test/java/acceptance/jobs/TaskUpdatePriorityJobAccTest.java
- lib/taskana-core/src/test/java/acceptance/jobs/WorkbasketCleanupJobAccTest.java
- lib/taskana-core/src/test/java/acceptance/persistence/UpdateObjectsUseUtcTimeStampsAccTest.java
- rest/taskana-rest-spring-example-common/src/main/java/pro/taskana/example/jobs/JobScheduler.java
> TSK-1724: Change JobType from Enum to String

- rest/taskana-rest-spring/src/docs/asciidoc/rest-api.adoc
- rest/taskana-rest-spring/src/main/java/pro/taskana/monitor/rest/MonitorController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/monitor/rest/MonitorControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/monitor/rest/MonitorControllerRestDocTest.java
> TSK-1687: Added Rest Docs for WorkbasketPriorityReport

- common/taskana-common/src/main/java/pro/taskana/common/internal/util/SqlProviderUtil.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/MonitorMapperSqlProvider.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/api/WorkbasketQueryColumnName.java
https://sonarcloud.io/dashboard?branch=TSK-1728&id=Tristan2357_taskana
---
> TSK-1728: Refactored SqlProviderUtil

- web/cypress/integration/workbaskets/workbaskets.spec.js
- web/src/app/app.component.scss
- web/src/app/shared/components/type-ahead/type-ahead.component.html
- web/src/app/shared/components/type-ahead/type-ahead.component.scss
> TSK-1714: Show tooltip on Access Item label to see complete name

- .github/workflows/continuous-integration.yml
- .run/All in taskana-core DB2.run.xml
- .run/All in taskana-core POSTGRES.run.xml
- .run/Run ArchitectureTest.run.xml
- common/taskana-common-test/pom.xml
- common/taskana-common-test/src/main/java/pro/taskana/common/test/DockerContainerCreator.java
- common/taskana-common-test/src/main/java/pro/taskana/common/test/config/DataSourceGenerator.java
- lib/taskana-core/pom.xml
- lib/taskana-core/src/test/java/acceptance/jobs/helper/TaskUpdatePriorityWorkerAccTest.java
- lib/taskana-core/src/test/java/testapi/extensions/TestContainerExtension.java
This is based on #1709. That PR has to be merged first
sonar: https://sonarcloud.io/dashboard?branch=task%2F1735&id=mustaphazorgati_taskana
---
> TSK-1735: replaced taskanaUnitTest.properties with testcontainers

- common/taskana-common-test/src/main/java/pro/taskana/common/test/rest/TaskanaSpringBootTest.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/api/reports/header/PriorityColumnHeader.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/JsonPropertyEditor.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/JsonPropertyEditorRegistrator.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/monitor/rest/MonitorController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/monitor/rest/assembler/PriorityColumnHeaderRepresentationModelAssembler.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/monitor/rest/assembler/ReportRepresentationModelAssembler.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/monitor/rest/models/PriorityColumnHeaderRepresentationModel.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/monitor/rest/MonitorControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/monitor/rest/assembler/PriorityColumnHeaderRepresentationModelAssemblerTest.java
sonar: https://sonarcloud.io/dashboard?branch=task%2F1741&id=mustaphazorgati_taskana
---
> TSK-1741: WorkbasketPriorityReport now accepts column headers as request params

- common/taskana-common/src/main/java/pro/taskana/common/internal/util/SqlProviderUtil.java
- lib/taskana-core/src/main/java/pro/taskana/classification/internal/builder/ClassificationBuilder.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/MonitorMapperSqlProvider.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/builder/TaskBuilder.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/models/TaskSummaryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/builder/WorkbasketBuilder.java
- lib/taskana-core/src/test/java/acceptance/ArchitectureTest.java
- lib/taskana-core/src/test/java/acceptance/builder/ClassificationBuilderTest.java
- lib/taskana-core/src/test/java/acceptance/builder/TaskAttachmentBuilderTest.java
- lib/taskana-core/src/test/java/acceptance/builder/TaskBuilderTest.java
- lib/taskana-core/src/test/java/acceptance/builder/WorkbasketBuilderTest.java
- lib/taskana-core/src/test/java/acceptance/jobs/helper/TaskUpdatePriorityWorkerAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/QueryTasksAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/QueryTasksByWildcardSearchAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/QueryTasksListValuesAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/TaskQueryImplAccTest.java
- lib/taskana-core/src/test/java/acceptance/taskpreprocessing/CreateTaskPreprocessingAccTest.java
- lib/taskana-core/src/test/java/acceptance/taskrouting/TaskRoutingAccTest.java
- lib/taskana-core/src/test/java/testapi/util/ExtensionCommunicator.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskQueryFilterParameter.java
https://sonarcloud.io/dashboard?branch=TSK-1727&id=LiaLissmann_taskana
---
> TSK-1727: Add notLike and notIn filter parameter to TaskQuery

- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/ldap/LdapClient.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/ldap/LdapClientTest.java
> TSK-1756: additional user ldap attributes are now optional.

- common/taskana-common/src/main/java/pro/taskana/common/internal/configuration/TaskanaConfigurationInitializer.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/util/ObjectAttributeChangeDetector.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/util/ReflectionUtil.java
- common/taskana-common/src/test/java/pro/taskana/common/internal/util/ReflectionUtilTest.java
- lib/taskana-core/src/main/java/pro/taskana/TaskanaEngineConfiguration.java
> TSK-1763: refactored TaskanaConfigurationInitalizer

- .github/workflows/continuous-integration.yml
- ci/ibm_cf_manifest.yml
- rest/taskana-rest-spring-example-boot/pom.xml
- rest/taskana-rest-spring-example-boot/src/main/resources/application.properties
- rest/taskana-rest-spring-example-boot/src/main/resources/dmn-table.dmn
- rest/taskana-rest-spring-example-boot/src/main/resources/taskana.properties
- routing/taskana-routing-rest/src/main/java/pro/taskana/routing/dmn/rest/DmnUploadController.java
- routing/taskana-routing-rest/src/main/java/pro/taskana/routing/dmn/rest/RoutingRestEndpoints.java
> TSK-1759: Demo-App now contains routing documentation

- common/taskana-common-test/src/main/java/pro/taskana/common/test/util/ParallelThreadHelper.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/ConfigurationMapper.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/ConfigurationServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/config/ConfigurationServiceImplAccTest.java
- lib/taskana-core/src/test/java/acceptance/jobs/JobRunnerAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/SelectAndClaimTaskAccTest.java
> Tsk1757: Added lock to prevent concurrent initialisation of configuration

- .github/workflows/continuous-integration.yml
> TSK-1759: Release routing-rest module

- web/src/app/monitor/services/monitor.service.ts
> TSK-1771: Workbasket-Priority-Report default filter set to state=READY

- web/src/app/administration/components/administration-overview/administration-overview.component.html
- web/src/app/administration/components/administration-overview/administration-overview.component.ts
- web/src/app/shared/components/sidenav-list/sidenav-list.component.html
- web/src/app/shared/components/sidenav-list/sidenav-list.component.spec.ts
- web/src/app/shared/components/sidenav-list/sidenav-list.component.ts
- web/src/app/shared/guards/task-routing.guard.ts
- web/src/app/shared/services/taskana-engine/taskana-engine.service.ts
> TSK-1773: make routing-rest-enabled endpoint use the configured env

- common/taskana-common/src/main/java/pro/taskana/common/api/exceptions/SystemException.java
- history/taskana-loghistory-provider/src/test/java/pro/taskana/loghistory/impl/LogfileHistoryServiceImplTest.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/TaskHistoryQueryImpl.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/query/QueryTaskHistoryAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/jobs/AbstractTaskanaJob.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskCommentQuery.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskCommentQueryColumnName.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/user/api/models/User.java
- lib/taskana-core/src/test/java/acceptance/task/GetTaskAccTest.java
- lib/taskana-core/src/test/java/testapi/TaskanaEngineConfigurationModifier.java
- pom.xml
- rest/taskana-rest-spring/src/main/java/pro/taskana/monitor/rest/ReportFilterParameter.java
- routing/taskana-routing-rest/src/main/java/pro/taskana/routing/dmn/spi/api/DmnValidator.java
- routing/taskana-routing-rest/src/test/java/pro/taskana/routing/dmn/spi/TestDmnValidatorImpl.java
> TSK-1775: updated google-java-format

- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskCommentServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/task/TaskQueryImplAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/UpdateTaskCommentAccTest.java
Sonarcloud: https://sonarcloud.io/summary/new_code?branch=TSK-1777&id=ryzheboka_taskana
---
> TSK-1777: updated UpdateTaskCommentAccTest to use testapi

- common/taskana-common/src/test/java/pro/taskana/common/internal/util/ReflectionUtilTest.java
- lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/builder/ClassificationBuilderTest.java
- lib/taskana-core/src/test/java/acceptance/builder/TaskBuilderTest.java
- lib/taskana-core/src/test/java/acceptance/builder/TaskCommentBuilderTest.java
- lib/taskana-core/src/test/java/acceptance/builder/WorkbasketBuilderTest.java
https://sonarcloud.io/summary/new_code?branch=TSK-1778&id=ryzheboka_taskana
---
> TSK-1778: fix code smells

- common/taskana-common-test/src/main/java/pro/taskana/common/test/security/JaasExtension.java
- history/taskana-simplehistory-rest-spring/src/test/java/pro/taskana/simplehistory/rest/TaskHistoryEventControllerIntTest.java
- pom.xml
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/RestEndpoints.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/assembler/CollectionRepresentationModelAssembler.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/user/jobs/UserInfoRefreshJobIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/WorkbasketControllerIntTest.java
> TSK-1772: Upgrade to Spring Boot 2.6.1.

- common/taskana-common/src/test/java/pro/taskana/common/internal/util/LogSanitizerTest.java
https://sonarcloud.io/summary/new_code?branch=TSK-1781&id=ryzheboka_taskana
---
> TSK-1781: replace tests in LogSanitizerTest by a test factory

- common/taskana-common/src/test/java/pro/taskana/common/api/WorkingTimeCalculatorTest.java
https://sonarcloud.io/summary/new_code?branch=TSK-1779&id=ryzheboka_taskana
---
> TSK-1779: replace tests in WorkingTimeCalculatorTest by a test factory

- ci/change_version.sh
- ci/commitPoms.sh
- ci/update_taskana_dependency_for_wildfly.sh
- ci/verify_docs_alive.sh
- ci/verify_docs_jar.sh
- pom.xml
- rest/taskana-rest-spring-example-wildfly/pom.xml
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/common/test/rest/RestHelper.java
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/common/test/rest/TaskanaSpringBootTest.java
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/common/test/rest/TestConfiguration.java
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/example/wildfly/AbstractAccTest.java
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/example/wildfly/TaskanaWildflyWithHistoryLoggerEnabledTest.java
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/example/wildfly/TaskanaWildflyWithSimpleHistoryAndHistoryLoggerEnabledTest.java
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/example/wildfly/TaskanaWildflyWithSimpleHistoryEnabledTest.java
- rest/taskana-rest-spring-example-wildfly/src/test/resources/module.xml
- rest/taskana-rest-spring-example-wildfly/src/test/resources/taskana-test.ldif
https://sonarcloud.io/summary/new_code?branch=TSK-1689&id=SebastianRoseneck_taskana
---
> TSK-1689: Updated wildfly example to execute tests

- history/taskana-simplehistory-rest-spring/src/docs/asciidoc/simplehistory-rest-api.adoc
- rest/taskana-rest-spring/src/docs/asciidoc/rest-api.adoc
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/JsonPropertyEditorRegistrator.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskQueryFilterParameter.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
- routing/taskana-routing-rest/src/docs/asciidoc/routing-rest-api.adoc
https://sonarcloud.io/summary/new_code?branch=TSK-1665&id=ryzheboka_taskana
---
> TSK-1665: primary object reference can be used as complex parameter in a task query.

- common/taskana-common-test/src/main/java/pro/taskana/common/test/DockerContainerCreator.java
- common/taskana-common-test/src/main/java/pro/taskana/common/test/config/DataSourceGenerator.java
- docker-databases/db2_11-1/README.md
- docker-databases/db2_11-5/Dockerfile
- docker-databases/db2_11-5/README.md
- docker-databases/db2_11-5/db2server.rsp
- docker-databases/db2_11-5/entrypoint.sh
- docker-databases/docker-compose.yml
- docker-databases/prepare_db.bat
- docker-databases/prepare_db.sh
- lib/taskana-core/src/test/resources/container-license-acceptance.txt
> TSK-1768: replaced DB2 11.1 with DB2 11.5 for integration testing

- web/src/app/administration/components/tree/tree.component.ts
- web/src/app/shared/services/obtain-message/message-by-error-code.ts
> TSK-1786: Show notification when classification filter returns empty

- .github/workflows/continuous-integration.yml
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/example/wildfly/AbstractAccTest.java
> TSK-1788: Release CI committing taskana version updates for wildfly integration tests

- .github/workflows/continuous-integration.yml
- web/cypress-standalone.json
- web/cypress.json
- web/cypress/integration/monitor/monitor.spec.js
- web/cypress/support/commands.js
- web/src/app/app-routing.module.ts
> TSK-1785: Changed landing page to administration/workbaskets

- .github/workflows/continuous-integration.yml
- web/pom.xml
Also sneakily improved CI by splitting E2E and web tests
---
> TSK-1789: Updated Node version

- web/src/app/monitor/components/task-priority-report/task-priority-report.component.html
- web/src/app/workplace/components/task-list-toolbar/task-list-toolbar.component.html
- web/src/app/workplace/components/task-list-toolbar/task-list-toolbar.component.ts
> TSK-1792,TSK-1793: Improved Error message for priority-report and fixed routing issue in workplace

- web/src/app/shared/components/nav-bar/nav-bar.component.spec.ts
- web/src/app/shared/components/nav-bar/nav-bar.component.ts
- web/src/app/shared/services/access-ids/access-ids.service.spec.ts
- web/src/app/shared/services/selected-route/selected-route.ts
> TSK-1629: Corrected nav-bar for workplace

- common/taskana-common-test/pom.xml
- pom.xml
Closed rejected PR by mistake, so I created a new PR (see old PR: https://github.com/Taskana/taskana/pull/1813).
Sonarcloud: https://sonarcloud.io/summary/new_code?branch=TSK-1795&id=ensarevlideveloper_taskana
---
> TSK-1795: Updated Spring Boot version to version 2.6.3

- web/src/app/administration/services/classification-definition.service.ts
> TSK-1797: Fixed export of Classifications by domain

- web/src/app/administration/components/workbasket-list/workbasket-list.component.html
- web/src/app/administration/components/workbasket-list/workbasket-list.component.ts
- web/src/app/shared/components/pagination/pagination.component.ts
> TSK-1804: Workbasket list now resets to page 1 when filtering

- web/.prettierignore
- web/src/app/administration/components/tree/tree.component.html
- web/src/app/administration/components/tree/tree.component.ts
- web/src/app/shared/services/obtain-message/message-by-error-code.ts
- web/yarn.lock
Now display a message inline, instead of a popup notification
Also updated dependencies
---
> TSK-1786: Changed notification for empty classification filtering

- .run/Db2.run.xml
> TSK-1813: Fix DB2 run command for IntelliJ

- web/src/app/administration/components/tree/tree.component.ts
- web/src/app/administration/components/workbasket-distribution-targets-list/workbasket-distribution-targets-list.component.html
- web/src/app/administration/components/workbasket-distribution-targets-list/workbasket-distribution-targets-list.component.ts
- web/src/app/app.component.html
- web/src/app/app.component.scss
- web/src/app/monitor/components/classification-report/classification-report.component.ts
- web/src/app/monitor/components/monitor/monitor.component.ts
- web/src/app/monitor/components/task-priority-report/task-priority-report.component.spec.ts
- web/src/app/monitor/components/task-priority-report/task-priority-report.component.ts
- web/src/app/monitor/components/task-report/task-report.component.ts
- web/src/app/monitor/components/timestamp-report/timestamp-report.component.ts
- web/src/app/monitor/components/workbasket-report-due-date/workbasket-report-due-date.component.ts
- web/src/app/monitor/components/workbasket-report-planned-date/workbasket-report-planned-date.component.ts
- web/src/app/monitor/monitor-routing.module.ts
- web/src/app/settings/components/Settings/settings.component.scss
- web/src/app/settings/components/Settings/settings.component.spec.ts
- web/src/app/settings/components/Settings/settings.component.ts
- web/src/app/shared/components/sidenav-list/sidenav-list.component.html
- web/src/app/shared/components/sidenav-list/sidenav-list.component.spec.ts
- web/src/app/shared/components/sidenav-list/sidenav-list.component.ts
- web/src/app/workplace/components/task-list-toolbar/task-list-toolbar.component.ts
- web/src/app/workplace/components/task-master/task-master.component.ts
Loading bar is now a more intense color and is larger
Also made sure the loading bar is shown when loading components
---
> TSK-1805: Made loading more obvious

- web/src/app/administration/components/workbasket-distribution-targets/workbasket-distribution-targets.component.ts
- web/src/app/app.component.ts
- web/src/app/shared/components/nav-bar/nav-bar.component.spec.ts
- web/src/app/shared/components/nav-bar/nav-bar.component.ts
- web/src/app/shared/services/selected-route/selected-route.ts
> TSK-1815: Merged administration titles

- lib/taskana-core/src/main/java/pro/taskana/classification/internal/models/ClassificationImpl.java
- lib/taskana-core/src/main/java/pro/taskana/classification/internal/models/ClassificationSummaryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/models/ObjectReferenceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/models/TaskSummaryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/models/WorkbasketImpl.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/models/WorkbasketSummaryImpl.java
- web/src/app/administration/components/classification-details/classification-details.component.ts
- web/src/app/administration/components/workbasket-information/workbasket-information.component.ts
- web/src/app/shared/util/form-trimmer.ts
- web/src/app/workplace/components/task-details/task-details.component.ts
https://sonarcloud.io/summary/new_code?branch=TSK-1796&id=Tristan2357_taskana
---
> TSK-1796: Whitespace trimming for Front- and Backend

- lib/taskana-core/src/main/java/pro/taskana/task/internal/models/TaskSummaryImpl.java
- lib/taskana-core/src/test/java/acceptance/CreateTaskModelHelper.java
https://sonarcloud.io/summary/new_code?id=ensarevlideveloper_taskana&branch=TSK-1817
---
> TSK-1817: Added received to TaskSummaryImpl constructor.

- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/TaskanaRestExceptionHandler.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-1822
---
> TSK-1822: fix error message for wrong order parameter

- lib/taskana-core/src/test/java/acceptance/task/QueryTasksWithSortingAccTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-1827
---
> TSK-1827: add sorting by ownerLongName

- common/taskana-common-data/src/main/java/pro/taskana/sampledata/SampleDataGenerator.java
- pom.xml
- rest/pom.xml
- rest/taskana-rest-spring-example-wildfly/pom.xml
- rest/taskana-rest-spring-example-wildfly/src/main/java/pro/taskana/example/wildfly/TaskanaWildflyConfiguration.java
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/example/wildfly/AbstractAccTest.java
- rest/taskana-rest-spring-example-wildfly/src/test/resources/application-h2.properties
- rest/taskana-rest-spring-example-wildfly/src/test/resources/application.properties
- rest/taskana-rest-spring-example-wildfly/src/test/resources/arquillian.xml
- rest/taskana-rest-spring-example-wildfly/src/test/resources/int-test-standalone.xml
- rest/taskana-rest-spring-example-wildfly/src/test/resources/int-test-web.xml
- rest/taskana-rest-spring-example-wildfly/src/test/resources/module.xml
> TSK-1826: Update to Wildfly 15.0.1

- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/ldap/LdapClient.java
> TSK-1833: distinguish between ldap user and group by objectClass

- .github/workflows/continuous-integration.yml
due to deprecation warning
https://sonarcloud.io/summary/new_code?id=mustaphazorgati_taskana&branch=task%2F1842
---
> TSK-1842: replaced workflow-run-cleanup-action with new concurrency cmd

- web/src/app/app-routing.module.ts
- web/src/app/shared/guards/business-admin.guard.ts
- web/src/app/shared/guards/history.guard.ts
- web/src/app/shared/guards/monitor.guard.ts
- web/src/app/shared/guards/task-routing.guard.ts
- web/src/app/shared/guards/user.guard.ts
> TSK-1848: Fixed a bug where the UI would freeze with insufficient user permissions

- CODE_OF_CONDUCT.md
from https://www.contributor-covenant.org/
---
> TSK-1849: updated Code of conduct to version 2.1

- qa/intellij/taskana_formatter_intellij.xml
> TSK-1851: update IDE formatter so that classes mentioned in Java-doc are imported automatically

- lib/taskana-core/src/test/java/testapi/tests/TestContainerExtensionTest.java
> TSK-1835: expanded test api test showing that @CleanTaskanaContext works

- web/yarn.lock
> TSK-1850: Update dependencies to fix Prototype Pollution in async Package

- ci/ibm_cf_manifest.yml
Co-authored-by: knht <43456808+knht@users.noreply.github.com>
---
> TSK-1869: updated demo app environment to JDK 11

- .github/workflows/continuous-integration.yml
> TSK-1856: fixed release of artifacts introduced my missing comma

- lib/taskana-core/src/main/java/pro/taskana/classification/api/ClassificationService.java
> TSK-1867: Refactor Java-doc in ClassificationService

- common/taskana-common/src/main/java/pro/taskana/common/api/TaskanaRole.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/WorkbasketServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/config/TaskanaRoleConfigAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/complete/CancelTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/complete/CompleteTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/complete/TerminateTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/create/CreateTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/delete/DeleteTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/get/GetTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/query/QueryTasksByRoleAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/transfer/TransferTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/update/UpdateTaskAccTest.java
- lib/taskana-core/src/test/resources/taskana.properties
Sonarcloud:  https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-1889
---
> TSK-1889: create TASK_ROUTER role

- lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-1736
---
> TSK-1736: fix TaskQuery in db2 for admin user and no workbasketAccessItems

- web/src/app/administration/components/workbasket-distribution-targets-list/workbasket-distribution-targets-list.component.html
Co-authored-by: ryzheboka <25465835+ryzheboka@users.noreply.github.com>
---
> TSK-1895: Fixed a bug where a spinner timeout causes an error message

- lib/taskana-core/src/main/java/pro/taskana/classification/api/ClassificationService.java
New ordering follows CRUD principles for better readability.
---
> TSK-1865: Reorder methods in ClassificationService

- history/taskana-simplehistory-provider/src/test/java/acceptance/events/task/CreateHistoryEventOnTaskCancelClaimAccTest.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/events/task/CreateHistoryEventOnTaskClaimAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/spi/history/api/events/task/TaskClaimCancelledEvent.java
- lib/taskana-core/src/main/java/pro/taskana/spi/history/api/events/task/TaskClaimedEvent.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
https://sonarcloud.io/summary/new_code?id=ensarevlideveloper_taskana&branch=TSK-1812
---
> TSK-1812: Added details in task-history for claim/cancel

- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java
> TSK-1852: refactor JavaDoc in TaskService

- lib/taskana-core/src/main/java/pro/taskana/common/api/ConfigurationService.java
- lib/taskana-core/src/main/java/pro/taskana/user/api/UserService.java
New ordering follows CRUD principles for better readability.
---
> TSK-1888: Restructure method order of ConfigurationService, UserService

- lib/taskana-core-test/src/test/java/acceptance/classification/create/CreateClassificationAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/common/api/SharedConstants.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/WorkbasketServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/CreateTaskModelHelper.java
- lib/taskana-core/src/test/java/acceptance/classification/delete/DeleteClassificationAccTest.java
- lib/taskana-core/src/test/java/acceptance/classification/get/GetClassificationAccTest.java
- lib/taskana-core/src/test/java/acceptance/classification/query/QueryClassificationAccTest.java
- lib/taskana-core/src/test/java/acceptance/persistence/UpdateObjectsUseUtcTimeStampsAccTest.java
- lib/taskana-core/src/test/resources/simplelogger.properties
- rest/taskana-rest-spring/src/main/java/pro/taskana/classification/rest/ClassificationQueryFilterParameter.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/classification/rest/ClassificationControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/classification/rest/ClassificationDefinitionControllerIntTest.java
> TSK-1886: add MASTER_DOMAIN into the SharedConstants class

- common/taskana-common/src/main/java/pro/taskana/common/api/WorkingDaysToDaysConverter.java
- lib/taskana-core/src/test/java/acceptance/task/update/UpdateTaskAccTest.java
> TSK-1902: fix wrong time conversion

- history/taskana-simplehistory-provider/src/test/java/acceptance/query/QueryWorkbasketHistoryAccTest.java
Co-Authored-By: Mustapha Zorgati <15628173+mustaphazorgati@users.noreply.github.com>
---
Release Notes:
```
```
> TSK-1910: Fix QueryWorkbasketHistoryAccTest

- lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java
Sonarcloud: https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-1909
Both codesmells are unavoidable
---
> TSK-1909: optimize authorization in db2 query

- lib/taskana-test-api/src/main/java/pro/taskana/testapi/extensions/TestContainerExtension.java
- lib/taskana-test-api/src/test/java/pro/taskana/testapi/tests/TestContainerExtensionTest.java
Co-authored-by: ryzheboka <25465835+ryzheboka@users.noreply.github.com>
Sonar: https://sonarcloud.io/summary/new_code?id=mustaphazorgati_taskana&branch=task%2F1882
---
Release Notes:
```
```
> TSK-1882: test-api now uses one database with different schema names

- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/TaskHistoryQueryImpl.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/classification/ClassificationHistoryQuery.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/task/TaskHistoryQuery.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/workbasket/WorkbasketHistoryQuery.java
- lib/taskana-core/src/main/java/pro/taskana/classification/api/ClassificationQuery.java
- lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/api/AbstractWorkbasketAccessItemQuery.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/api/WorkbasketAccessItemQuery.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/api/WorkbasketQuery.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/WorkbasketQueryImpl.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/models/TaskSummaryRepresentationModel.java
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-1923
---
Release Notes:
```
```
> TSK-1923: clean parameter names in Query entities

- .run/Run ArchitectureTest.run.xml
- lib/taskana-core-test/src/test/java/acceptance/ArchitectureTest.java
- lib/taskana-core-test/src/test/java/acceptance/classification/get/GetClassificationAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/requestchanges/RequestChangesAccTest.java
---
Release Notes:
```
* Re-enabled ArchUnit Tests
* Added Dependency Hierarchy Tests
* Fixed some Coding Guideline Violations
```
> TSK-1924 ArchUnit dependency hierarchy tests

- common/taskana-common/src/main/java/pro/taskana/common/internal/util/ReflectionUtil.java
- common/taskana-common/src/test/java/pro/taskana/common/internal/util/ReflectionUtilTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/complete/CompleteTaskWithSpiAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/requestchanges/RequestChangesWithSpiAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/requestreview/RequestReviewWithSpiAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/taskrouting/TaskRoutingAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/InternalTaskanaEngine.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/TaskanaEngineImpl.java
- lib/taskana-core/src/main/java/pro/taskana/spi/task/api/ReviewRequiredProvider.java
- lib/taskana-core/src/main/java/pro/taskana/spi/task/internal/ReviewRequiredManager.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-test-api/src/main/java/pro/taskana/testapi/extensions/TaskanaInitializationExtension.java
- lib/taskana-test-api/src/main/java/pro/taskana/testapi/util/ServiceProviderExtractor.java
- lib/taskana-test-api/src/test/java/pro/taskana/testapi/util/ServiceProviderExtractorTest.java
sonar: https://sonarcloud.io/summary/new_code?id=mustaphazorgati_taskana&branch=task%2F1941
---
Release Notes:
```
**NEW**
* TSK-1941: implemented ReviewRequiredProvider SPI
```
> TSK-1941: implemented ReviewRequired SPI

- web/package.json
- web/yarn.lock
> TSK-1921: Updated Angular to fix ReDoS vulnerability within Terser

- routing/taskana-routing-rest/src/main/java/pro/taskana/routing/dmn/service/DmnConverterService.java
- routing/taskana-routing-rest/src/main/java/pro/taskana/routing/dmn/service/XlsxConverter.java
- routing/taskana-routing-rest/src/main/java/pro/taskana/routing/dmn/service/XlsxWorksheetConverter.java
> TSK-1942: optimized generation of DMN model during upload

- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java
New ordering follows CRUD principles for better readability.
---
> TSK-1864: Reorder methods in TaskService

- lib/taskana-core-test/src/test/java/acceptance/ArchitectureTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/ServiceLevelOfAllTasksAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/ServiceLevelPriorityAccTest.java
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-1829
---
> TSK-1829: refactor testSetPlannedPropertyOnAllTasks

- lib/taskana-core-test/src/test/java/acceptance/task/requestreview/RequestReviewWithAfterSpiAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/requestreview/RequestReviewWithBeforeSpiAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/InternalTaskanaEngine.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/TaskanaEngineImpl.java
- lib/taskana-core/src/main/java/pro/taskana/spi/task/api/BeforeRequestReviewProvider.java
- lib/taskana-core/src/main/java/pro/taskana/spi/task/internal/AfterRequestChangesManager.java
- lib/taskana-core/src/main/java/pro/taskana/spi/task/internal/AfterRequestReviewManager.java
- lib/taskana-core/src/main/java/pro/taskana/spi/task/internal/BeforeRequestReviewManager.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskMapper.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-test-api/src/main/java/pro/taskana/testapi/util/ServiceProviderExtractor.java
sonar: https://sonarcloud.io/summary/new_code?id=mustaphazorgati_taskana&branch=task%2F1945
---
Release Notes:
```
**NEW**
* TSK-1945: added BeforeRequestReviewProvider which allows customized behavior before a review has been requested on a given Task.
```
> TSK-1945: implemented BeforeRequestReview SPI

- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-1926
---
Release Notes:
```
```
> TSK-1926: Remove duplicate from TaskServiceImpl

- lib/taskana-core/src/main/java/pro/taskana/monitor/api/reports/TimeIntervalReportBuilder.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/api/reports/WorkbasketPriorityReport.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/MonitorMapperSqlProvider.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/reports/TimeIntervalReportBuilderImpl.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/reports/WorkbasketPriorityReportBuilderImpl.java
- lib/taskana-core/src/test/java/acceptance/report/ProvideWorkbasketPriorityReportAccTest.java
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-1951
---
Release Notes:
```
TSK-1951: add support for custom-int fields in reports
```
> TSK-1951: Extend WorkbasketPriorityReport for customInt

- lib/taskana-core/src/test/java/acceptance/report/GetTaskIdsOfTaskCustomFieldValueReportAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/complete/TerminateTaskAccTest.java
- rest/taskana-rest-spring-example-wildfly/src/main/java/pro/taskana/example/wildfly/security/ElytronToJaasFilter.java
> TSK-1954: Clean up codesmells

- lib/taskana-core/src/main/java/pro/taskana/spi/priority/api/PriorityServiceProvider.java
- lib/taskana-core/src/main/java/pro/taskana/spi/routing/api/TaskRoutingProvider.java
- lib/taskana-core/src/main/java/pro/taskana/spi/task/api/CreateTaskPreprocessor.java
> TSK-1955: Add javadoc for two SPIs

- web/src/app/shared/components/type-ahead/type-ahead.component.ts
> TSK-1956: Meldung bei Owner: Access ID is not valid

- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskTransferrer.java
- lib/taskana-core/src/test/java/acceptance/task/transfer/TransferTaskAccTest.java
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-1958
---
Release Notes:
```
TSK-1958: fix status changes for Task transfer involving status IN_REVIEW and READY_FOR_REVIEW
```
> TSK-1958: fix status changes for Task transfer

- lib/taskana-core-test/src/test/java/acceptance/task/complete/CompleteTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-1925
---
Release Notes:
```
```
> TSK-1925: clean up claimTaskAccTest

- lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplAccTest.java
- lib/taskana-test-api/src/main/java/pro/taskana/testapi/DefaultTestEntities.java
- lib/taskana-test-api/src/main/java/pro/taskana/testapi/builder/ClassificationBuilder.java
- lib/taskana-test-api/src/main/java/pro/taskana/testapi/builder/EntityBuilder.java
- lib/taskana-test-api/src/main/java/pro/taskana/testapi/builder/TaskBuilder.java
- lib/taskana-test-api/src/main/java/pro/taskana/testapi/builder/TaskCommentBuilder.java
- lib/taskana-test-api/src/main/java/pro/taskana/testapi/builder/UserBuilder.java
- lib/taskana-test-api/src/main/java/pro/taskana/testapi/builder/WorkbasketAccessItemBuilder.java
- lib/taskana-test-api/src/main/java/pro/taskana/testapi/builder/WorkbasketBuilder.java
- lib/taskana-test-api/src/main/java/pro/taskana/testapi/extensions/TaskanaInitializationExtension.java
- lib/taskana-test-api/src/test/java/pro/taskana/testapi/TaskanaDependencyInjectionExtensionTest.java
- lib/taskana-test-api/src/test/java/pro/taskana/testapi/builder/UserBuilderTest.java
sonar: https://sonarcloud.io/summary/new_code?id=mustaphazorgati_taskana&branch=task%2F1964
---
Release Notes:
```
```
> TSK-1964: added UserBuilder to test-api

- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java
- rest/taskana-rest-spring/src/docs/asciidoc/rest-api.adoc
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/RestEndpoints.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/models/IsReadRepresentationModel.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerRestDocTest.java
---
Release Notes:
```
**New**
* 4 new REST endpoints:
API_V1 + "tasks/{taskId}/claim/force"
API_V1 + "tasks/{taskId}/complete/force"
API_V1 + "tasks/{taskId}/terminate"
API_V1 + "tasks/{taskId}/{isRead}
**Breaking Changes**
* until now the REST endpoint to delete a Task: DELETE Request on API_V1 + tasks/{taskId} has used the forceDelete method of the taskService --> this is now split into two endpoints:
DELETE Request on API_V1 + tasks/{taskId} to delete a task normaly
DELETE Request on API_V1 + tasks/{taskId}/force to force delete a task
```
https://sonarcloud.io/summary/new_code?id=norman-schmidt_taskana&branch=TSK-1965
> TSK-1965: create endpoints for all state transitions

- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/jobs/HistoryCleanupJob.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/jobs/HistoryCleanupJobAccTest.java
---
Release Notes:
```
Add check to avoid nullpointer
```
> TSK-1973: Check CREATED events to avoid null pointer

- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/InitBinderControllerAdvice.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/WorkbasketAccessItemControllerIntTest.java
[Sonar](https://sonarcloud.io/summary/new_code?id=ensarevlideveloper_taskana&branch=TSK-1981)
- [ X I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
> TSK-1981: Fixed code smells

- .github/workflows/continuous-integration.yml
- rest/taskana-rest-spring-test-lib/src/main/java/pro/taskana/rest/test/SpringSecurityToJaasFilter.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/SpringSecurityToJaasFilter.java
> TSK-1946: fix release job due to missing dependencies

- rest/taskana-rest-spring/src/test/java/pro/taskana/user/jobs/UserInfoRefreshJobIntTest.java
https://sonarcloud.io/summary/new_code?id=arolfes_taskana&branch=TSK-1957-testcase-userinforefreshjob
---
Release Notes:
```
```
> TSK-1957 extend TestCase with comparison for groups

- lib/taskana-cdi/pom.xml
- lib/taskana-cdi/src/main/java/pro/taskana/common/internal/TaskanaProducers.java
- lib/taskana-cdi/src/test/java/pro/taskana/TaskanaCdiTestRestController.java
- lib/taskana-cdi/src/test/java/pro/taskana/TaskanaEjb.java
- lib/taskana-cdi/src/test/java/pro/taskana/common/internal/TaskanaProducersTest.java
- lib/taskana-cdi/src/test/resources/taskana.properties
- pom.xml
- rest/taskana-rest-spring-example-wildfly/pom.xml
https://sonarcloud.io/summary/new_code?id=arolfes_taskana&branch=TSK-1828-remove-resteasy-client
---
Release Notes:
```
TSK-1828 remove resteasy-client dependency
```
> TSK-1828 remove resteasy-client dependency

- lib/taskana-core-test/src/test/java/acceptance/task/complete/CompleteTaskWithSpiAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/requestreview/RequestReviewAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/requestreview/RequestReviewWithAfterSpiAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/requestreview/RequestReviewWithBeforeSpiAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
Sonarcloud: https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-1983
---
Release Notes:
```
```
> fix resquestReview for an IN_REVIEW Task

- lib/taskana-core-test/src/test/java/acceptance/task/complete/CompleteTaskAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
Sonarcloud: https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-1977
---
Release Notes:
```
```
> TSK-1977: fix setting ownerLongName while claiming

- lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskQueryFilterParameter.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
Sonarcloud: https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-2000
---
Release Notes:
```
Add filtering by the key of the parent Classification of the Classification of the Task.
```
> add filtering by classification parent key

- history/taskana-simplehistory-provider/src/test/java/acceptance/AbstractAccTest.java
- history/taskana-simplehistory-provider/src/test/java/configuration/TaskanaEngineConfigurationTest.java
- lib/taskana-cdi/src/main/java/pro/taskana/common/internal/TaskanaProducers.java
- lib/taskana-core-test/src/test/java/acceptance/TaskanaConfigurationTest.java
- lib/taskana-core/src/main/java/pro/taskana/TaskanaConfiguration.java
- lib/taskana-core/src/test/java/acceptance/AbstractAccTest.java
- lib/taskana-core/src/test/java/acceptance/config/TaskanaConfigAccTest.java
- lib/taskana-core/src/test/java/acceptance/config/TaskanaEngineConfigTest.java
- lib/taskana-core/src/test/java/acceptance/config/TaskanaRoleConfigAccTest.java
- lib/taskana-core/src/test/java/acceptance/config/TaskanaSecurityConfigAccTest.java
- lib/taskana-core/src/test/java/acceptance/report/AbstractReportAccTest.java
- lib/taskana-spring-example/src/main/java/pro/taskana/example/TaskanaConfig.java
- lib/taskana-test-api/src/main/java/pro/taskana/testapi/extensions/TaskanaInitializationExtension.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/RestConfiguration.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/properties/MyTaskanaConfigurationIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/properties/MyTaskanaTestConfiguration.java
- rest/taskana-rest-spring/src/test/resources/mytaskana.properties
- routing/taskana-routing-rest/src/test/java/pro/taskana/routing/dmn/service/DmnConverterServiceAccTest.java
- routing/taskana-spi-routing-dmn-router/src/test/java/pro/taskana/AbstractAccTest.java
[SonarCloud](https://sonarcloud.io/summary/new_code?id=arolfes_taskana&branch=TSK-1996-taskana-properties-file-is-optional)
Diesen PR erst reviewn und integrieren wenn der PR https://github.com/Taskana/taskana/pull/2083 durch ist
---
Release Notes:
```
TSK-1996 taskana.properties file is optional when creating configuration
```
> Tsk 1996 taskana properties file is optional

- lib/taskana-core/src/main/java/pro/taskana/task/internal/jobs/helper/SqlConnectionRunner.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/WorkbasketServiceImpl.java
- lib/taskana-core/src/test/java/acceptance/jobs/helper/SqlConnectionRunnerAccTest.java
> TSK-2003: removed reset of schema name in SqlConRunner#runWithConnection

- common/taskana-common/src/main/java/pro/taskana/common/api/exceptions/InvalidArgumentException.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskTransferrer.java
- lib/taskana-core/src/test/java/acceptance/task/transfer/TransferTaskAccTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/TaskanaRestExceptionHandler.java
[SonarCloud](https://sonarcloud.io/summary/new_code?id=arolfes_taskana&branch=TSK-1993-InvalidArgumentException-TaskanaRuntimeException)
Must be reviewed and integrated after [TSK-1992 remove unnecessary ParentExceptions](https://github.com/Taskana/taskana/pull/2086)
---
Release Notes:
```
Tsk-1993 InvalidArgumentException becomes TaskanaRuntimeException
```
> Tsk-1993 InvalidArgumentException becomes TaskanaRuntimeException

- common/taskana-common/src/main/java/pro/taskana/common/api/IntInterval.java
- common/taskana-common/src/main/java/pro/taskana/common/api/TimeInterval.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/Interval.java
- common/taskana-common/src/test/java/pro/taskana/common/api/IntIntervalTest.java
- common/taskana-common/src/test/java/pro/taskana/common/api/TimeIntervalTest.java
- lib/taskana-core-test/src/test/java/acceptance/ArchitectureTest.java
> TSK-1994: introduce new Generic Interval

- common/taskana-common/src/main/java/pro/taskana/common/api/CustomHoliday.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/configuration/TaskanaConfigurationInitializer.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/util/FileLoaderUtil.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/jobs/HistoryCleanupJob.java
- lib/taskana-core-test/src/test/java/acceptance/TaskanaConfigurationTest.java
- lib/taskana-core/src/main/java/pro/taskana/TaskanaConfiguration.java
- lib/taskana-core/src/main/java/pro/taskana/classification/internal/jobs/ClassificationChangedJob.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/TaskanaEngineImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/ServiceLevelHandler.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/jobs/TaskCleanupJob.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/jobs/WorkbasketCleanupJob.java
- lib/taskana-core/src/test/java/acceptance/config/TaskanaConfigAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/create/CreateTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/update/UpdateTaskAccTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/TaskanaEngineController.java
And refactoring of some components around the TaskanaConfiguration
---
Release Notes:
```
```
> TSK-2004: JavaDoc 4 TaskanaConfiguration.Builder#initTaskanaProperties

- lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskQueryFilterParameter.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-2001
---
Release Notes:
```
Add filtering by intervals of priority (priorityWithin and priorityNotWithin)
```
> add filtering by priorityWithin and notWithin

- common/taskana-common-data/src/main/java/pro/taskana/sampledata/SampleDataGenerator.java
- common/taskana-common-data/src/main/java/pro/taskana/sampledata/SqlReplacer.java
- common/taskana-common-test/src/main/java/pro/taskana/common/test/config/DataSourceGenerator.java
- common/taskana-common/src/main/java/pro/taskana/common/api/exceptions/ConnectionNotSetException.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/configuration/DB.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/configuration/DbSchemaCreator.java
- common/taskana-common/src/test/java/pro/taskana/common/api/LocalTimeIntervalTest.java
- common/taskana-common/src/test/java/pro/taskana/common/internal/workingtime/WorkingTimeScheduleTest.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/TaskanaHistoryEngineImpl.java
- history/taskana-simplehistory-provider/src/test/java/acceptance/AbstractAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/common/TaskanaEngineExplicitTest.java
- lib/taskana-core/src/main/java/pro/taskana/TaskanaConfiguration.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/TaskanaEngineImpl.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/jobs/JobRunner.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java
- lib/taskana-core/src/test/java/acceptance/config/TaskanaSecurityConfigAccTest.java
- lib/taskana-test-api/src/main/java/pro/taskana/testapi/extensions/TestContainerExtension.java
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/common/test/rest/TestConfiguration.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/common/rest/SchemaNameCustomizableTest.java
[SonarCloud](https://sonarcloud.io/summary/new_code?id=arolfes_taskana&branch=TSK-1997-refactore-DB-Enum)
---
Release Notes:
```
TSK-1995 refactoring DB Enum
```
> TSK-1995 refactoring DB Enum

- lib/taskana-core-test/src/test/java/acceptance/ArchitectureTest.java
- lib/taskana-core-test/src/test/java/acceptance/TaskanaConfigurationTest.java
- lib/taskana-core/src/main/java/pro/taskana/TaskanaConfiguration.java
- lib/taskana-core/src/test/java/acceptance/jobs/TaskCleanupJobAccTest.java
- lib/taskana-core/src/test/java/acceptance/jobs/TaskUpdatePriorityJobAccTest.java
- lib/taskana-core/src/test/java/acceptance/jobs/helper/SqlConnectionRunnerAccTest.java
- lib/taskana-spring-example/src/main/resources/taskana.properties
[SonarCloud](https://sonarcloud.io/summary/new_code?id=arolfes_taskana&branch=TSK-2005-validate-TaskanaConfiguration)
Must be reviewed after [Tsk 1995 lombok](https://github.com/Taskana/taskana/pull/2099)
---
Release Notes:
```
Tsk-2005 validate taskana configuration
```
> Tsk-2005 validate taskana configuration

- lib/taskana-core/src/main/java/pro/taskana/TaskanaConfiguration.java
> TSK-1988: cleanup of TaskanaConfiguration

- common/taskana-common/src/main/java/pro/taskana/common/internal/configuration/TaskanaConfigurationInitializer.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/workingtime/WorkingTimeCalculatorImpl.java
- common/taskana-common/src/test/java/pro/taskana/common/internal/workingtime/WorkingTimeCalculatorImplTest.java
- history/taskana-simplehistory-provider/src/test/resources/taskana.properties
- lib/taskana-core-test/src/test/java/acceptance/TaskanaConfigurationTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/ServiceLevelOfAllTasksAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/TaskanaConfiguration.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/TaskanaEngineImpl.java
- lib/taskana-core/src/test/java/acceptance/report/WorkingDaysToDaysReportConverterTest.java
- lib/taskana-core/src/test/resources/taskana.properties
> Workingtime with configurable timezone

- lib/taskana-core-test/src/test/java/acceptance/classification/update/UpdateClassificationAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/ServiceLevelOfAllTasksAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/servicelevel/ServiceLevelCalculationAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/models/Task.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/models/TaskSummary.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/ServiceLevelHandler.java
- lib/taskana-core/src/test/java/acceptance/persistence/UpdateObjectsUseUtcTimeStampsAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/ServiceLevelPriorityAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/create/CreateTaskAccTest.java
- lib/taskana-core/src/test/java/acceptance/task/update/UpdateTaskAttachmentsAccTest.java
> TSK-1972: Task.due is inclusive

- ci/verify_docs_alive.sh
- ci/verify_docs_jar.sh
- lib/taskana-core/src/main/java/pro/taskana/spi/history/api/TaskanaHistory.java
> fixed documentation smoke tests

- lib/taskana-core-test/src/test/java/acceptance/TaskanaConfigurationTest.java
- lib/taskana-core-test/src/test/resources/fullTaskana.properties
- lib/taskana-core/src/main/java/pro/taskana/TaskanaConfiguration.java
and restructured TaskanaConfigurationTest for better readability / maintainability.
**DISCLAIMER**: This is just a test improvement and therefore not relevant for TASKANA v6.0.0
Since the diff is horrible here is a list of changes:
* tests in TaskanaConfigurationTest have been reorganized in 5 nested classes (and are unchanged otherwise)
* Functionality
* Structure
* Immutability
* Validation
* Adjustments 
*  TaskanaConfigurationTest$Immutability#should_SaveUnmodifiableCollections was modified and now instantiates the builder with mutable collections (to make sure that mutable collections are converted to immutable collections during TaskanaConfiguration.Builder#build)
* TaskanaConfigurationTest$Immutability#should_SaveUnmodifiableMaps: Same thing, just with mutable maps
* …
> TSK-1991: verify immutability for TaskanaConf Map<?, Collection<?>>

- lib/taskana-core-test/src/test/java/acceptance/TaskanEngineInitalizationTest.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/TaskanaEngineImpl.java
- lib/taskana-core/src/main/java/pro/taskana/spi/priority/internal/PriorityServiceManager.java
Closes #2181.
---
Release Notes:
```
```
> #2181: init PriorityServiceProviders  during TaskanaEngine init

- .run/Postgres.run.xml
- common/taskana-common-test/src/main/java/pro/taskana/common/test/DockerContainerCreator.java
- docker-databases/docker-compose.yml
- docker-databases/postgres_14/Dockerfile
- docker-databases/prepare_db.bat
- docker-databases/prepare_db.sh
- lib/taskana-test-api/src/main/java/pro/taskana/testapi/DockerContainerCreator.java
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/example/wildfly/AbstractAccTest.java
Edited documentation: 
https://taskana.atlassian.net/wiki/spaces/TAS/pages/698286081/Using+multiple+databases+for+taskana-core+unit+tests
https://taskana.atlassian.net/wiki/spaces/TAS/pages/1758593073/Supported+Environments
Sonarcloud: https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-2185
Issue Link: #2185
---
Release Notes:
```
```
> TSK-2185: upgrade postgres to version 14.7

- lib/taskana-cdi/pom.xml
- lib/taskana-cdi/src/test/resources/arquillian.xml
- lib/taskana-cdi/src/test/resources/int-test-standalone.xml
- pom.xml
- rest/taskana-rest-spring-example-wildfly/pom.xml
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/example/wildfly/AbstractAccTest.java
- rest/taskana-rest-spring-example-wildfly/src/test/resources/arquillian.xml
- rest/taskana-rest-spring-example-wildfly/src/test/resources/int-test-standalone.xml
No source code changes, therefore no sonar cloud result
---
Release Notes:
```
#2206 migrate wildfly from 15.0.1 to 25.0.1
```
> Closes #2206:  Migrate to wildfly 25.0.1

- rest/taskana-rest-spring-example-common/src/main/java/pro/taskana/example/rest/ExampleWebSecurityConfig.java
- web/cypress/integration/monitor/monitor.spec.js
With a SpringBoot Upgrade the CorsConfiguration changed a bit. therefore we need to adjust our config.
[SonarCloud](https://sonarcloud.io/summary/new_code?id=arolfes_taskana&branch=2219-running-taskana-example-app-locally)
---
Release Notes:
```
#2219 fixes SpringBoot CORS Configuration to run example App locally
```
> Closes #2219 fixes exception when running taskana locally

- lib/taskana-core-test/src/test/java/acceptance/TaskanaConfigurationTest.java
- lib/taskana-core/src/main/java/pro/taskana/TaskanaConfiguration.java
- lib/taskana-core/src/test/java/acceptance/config/TaskanaConfigAccTest.java
- lib/taskana-test-api/src/test/java/pro/taskana/testapi/TaskanaInitializationExtensionTest.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/TaskanaEngineController.java
[SonarCloud](https://sonarcloud.io/summary/new_code?id=arolfes_taskana&branch=2201-add-masterDomain-always)
---
Release Notes:
```
#2201 add master domain always to configured domains
```
> Closes #2201 add master domain always

- .github/workflows/continuous-integration.yml
- .mvn/wrapper/maven-wrapper.properties
- common/taskana-common-security/src/main/java/pro/taskana/common/internal/security/CurrentUserContextImpl.java
- common/taskana-common/src/main/java/pro/taskana/common/internal/configuration/parser/PropertyParser.java
- history/taskana-simplehistory-rest-spring/pom.xml
- lib/taskana-cdi/src/test/resources/arquillian.xml
- mvnw
- mvnw.cmd
- pom.xml
- rest/taskana-rest-spring-example-wildfly/src/main/java/pro/taskana/example/wildfly/security/ElytronToJaasFilter.java
- rest/taskana-rest-spring-example-wildfly/src/test/resources/arquillian.xml
- rest/taskana-rest-spring-example-wildfly/src/test/resources/int-test-standalone.xml
- rest/taskana-rest-spring-test-lib/src/main/java/pro/taskana/rest/test/SpringSecurityToJaasFilter.java
- rest/taskana-rest-spring/pom.xml
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/SpringSecurityToJaasFilter.java
- routing/taskana-routing-rest/pom.xml
https://sonarcloud.io/summary/new_code?id=arolfes_taskana&branch=2131-java-17
---
Release Notes:
```
#2131 Java 17 Migration
```
> Closes #2131 Upgrade to java 17

- lib/taskana-core-test/src/test/java/acceptance/jobs/AbstractTaskanaJobAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/common/internal/jobs/AbstractTaskanaJob.java
instead of using always the first constructor, load the constructor with correct parameters
[SonarCloud](https://sonarcloud.io/summary/new_code?id=arolfes_taskana&branch=2229-jobrunner)
---
Release Notes:
```
#2229 load correct constructor to init TaskanaJob
```
> Closes #2229 load correct constructor to init TaskanaJob

- common/taskana-common/src/main/java/pro/taskana/common/api/BaseQuery.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/ClassificationHistoryQueryImpl.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/TaskHistoryQueryImpl.java
- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/WorkbasketHistoryQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/reports/TimeIntervalReportBuilderImpl.java
- lib/taskana-core/src/main/java/pro/taskana/monitor/internal/reports/WorkbasketPriorityReportBuilderImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskCommentQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/WorkbasketAccessItemQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/WorkbasketQueryImpl.java
https://sonarcloud.io/summary/new_code?id=DanielNovaSchreider_taskana&branch=2172-reuse-basequery
---
Release Notes:
```
```
> Closes #2171 - Refactor toLowerCopy

- .github/workflows/continuous-integration.yml
---
Release Notes:
```
Deploy Demo App to Microsoft Azure instead of IBM Bluemix
```
> Closes #2270: Deploy Demo App on Microsoft Azure

- .github/pull_request_template.md
- qa/hooks/commit-msg
---
Release Notes:
```
fixed the commit hooks for github
```
> Closes #2271: fix hooks for github

- rest/taskana-rest-spring-example-wildfly/src/main/java/pro/taskana/example/wildfly/AdditionalUserProperties.java
- rest/taskana-rest-spring-example-wildfly/src/main/java/pro/taskana/example/wildfly/TaskanaWildflyConfiguration.java
- rest/taskana-rest-spring-example-wildfly/src/main/java/pro/taskana/example/wildfly/security/ElytronToJaasFilter.java
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/example/wildfly/TaskanaWildflyWithHistoryLoggerEnabledTest.java
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/example/wildfly/TaskanaWildflyWithSimpleHistoryAndHistoryLoggerEnabledTest.java
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/example/wildfly/TaskanaWildflyWithSimpleHistoryEnabledTest.java
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/example/wildfly/TaskanaWildflyWithUserConfigTest.java
- rest/taskana-rest-spring-example-wildfly/src/test/resources/application-with-additional-user-config.properties
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-2187
---
Release Notes:
```
Extend wildfly example with additional user properties. These make it possible to change the current user to the one specified in an additional header.
```
> TSK-2187: Add additional user configuration in wildfly

- rest/taskana-rest-spring/src/main/java/pro/taskana/workbasket/rest/assembler/WorkbasketAccessItemRepresentationModelAssembler.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/workbasket/rest/models/WorkbasketAccessItemRepresentationModel.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/workbasket/rest/assembler/WorkbasketAccessItemRepresentationModelAssemblerTest.java
Sonarcloud: https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-2286
---
Release Notes:
```
```
> Closes #2286 - adjust REST with READTASKS and EDITTASKS

- lib/taskana-core-test/src/test/java/acceptance/task/update/UpdateTaskAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-2296
---
Release Notes:
```
```
> Closes #2296 - add ownerLongName during update

- routing/taskana-spi-routing-dmn-router/pom.xml
- routing/taskana-spi-routing-dmn-router/src/test/java/pro/taskana/routing/dmn/DmnTaskRouterAccTest.java
- routing/taskana-spi-routing-dmn-router/src/test/resources/empty.dmn
- routing/taskana-spi-routing-dmn-router/src/test/resources/taskana.properties
https://sonarcloud.io/summary/new_code?id=jamesrdi_taskana&branch=TSK-2316
---
Release Notes:
```
```
> Closes #2316 - refactor DmnTaskRouterAccTest to use test-api

- lib/taskana-core-test/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
> Closes #2322 - set ownerLongName to null during cancelClaim

- rest/taskana-rest-spring/src/main/java/pro/taskana/monitor/rest/TimeIntervalReportFilterParameter.java
---
Release Notes:
```
```
- [x ] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [x ] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [x ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [x ] I put the ticket in review
> #Closes 2310 Default TimeIntervalColumnHeader Ranges are incorrect

- ci/verify_docs_alive.sh
> Closes #2326: fixed documentation smoketest (azure)

- .github/workflows/continuous-integration.yml
> Fix smoketest

- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.html
- web/src/app/administration/components/workbasket-access-items/workbasket-access-items.component.scss
- web/src/app/shared/directives/resizable-width.directive.spec.ts
- web/src/app/shared/directives/resizable-width.directive.ts
- web/src/app/shared/shared.module.ts
Link to SonarCloud: https://sonarcloud.io/summary/new_code?id=SebastianRoseneck_taskana&branch=TSK-2334
---
Release Notes:
```
```
> Closes #2334 - Make column width of AccessID dynamic under Workbasket Access Overview

- web/src/app/monitor/monitor-routing.module.ts
Fixes issue #2223 
---
Release Notes:
```
Fixes issue with monitoring page not loading when opening it the first time
```
> Fixes issue with monitoring page not loading directly in the web app

- lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/user/internal/UserServiceImpl.java
- lib/taskana-core/src/main/java/pro/taskana/workbasket/internal/WorkbasketServiceImpl.java
- lib/taskana-spring-example/src/main/java/pro/taskana/example/TaskanaTestController.java
- rest/taskana-rest-spring-example-common/src/main/resources/templates/login.html
- rest/taskana-rest-spring-example-wildfly/src/main/resources/templates/login.html
- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/ldap/LdapClient.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/monitor/rest/assembler/ReportRepresentationModelAssembler.java
Sonarcloud: https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-2289
---
Release Notes:
```
```
> Closes #2289 - fix Sonarcloud vulnerabilities and bugs

- history/taskana-simplehistory-provider/src/test/resources/taskana.properties
- lib/taskana-cdi/src/test/resources/taskana.properties
- lib/taskana-core-test/src/test/java/acceptance/TaskanaConfigurationTest.java
- lib/taskana-core-test/src/test/resources/taskana.properties
- lib/taskana-core/src/main/java/pro/taskana/TaskanaConfiguration.java
- lib/taskana-core/src/test/resources/taskana.properties
- lib/taskana-spring-example/src/main/resources/taskana.properties
- lib/taskana-spring-example/src/test/resources/taskana.properties
- lib/taskana-test-api/src/test/resources/taskana.properties
- rest/taskana-rest-spring-example-boot/src/main/resources/taskana.properties
- rest/taskana-rest-spring-example-common/src/test/resources/taskana.properties
- rest/taskana-rest-spring-example-wildfly/src/test/resources/taskana.properties
- rest/taskana-rest-spring/src/test/resources/mytaskana.properties
- rest/taskana-rest-spring/src/test/resources/taskana.properties
- routing/taskana-routing-rest/src/test/resources/taskana.properties
- routing/taskana-spi-routing-dmn-router/src/test/resources/taskana.properties
> Closes #2375 - fix description of initial start delay

- lib/taskana-core/src/test/resources/taskana.properties
> Closes #2412 - Fix flaky job tests by disabling scheduler in tests

- lib/taskana-core-test/src/test/java/acceptance/TaskanaConfigurationTest.java
- lib/taskana-core/src/main/java/pro/taskana/TaskanaConfiguration.java
Link SonarCloud: https://sonarcloud.io/summary/new_code?id=SebastianRoseneck_taskana&branch=TSK-2339
---
Release Notes:
```
```
> Closes #2339 - sort classificationCategoriesByType according to type order

- .github/workflows/continuous-integration.yml
https://sonarcloud.io/summary/new_code?id=jamesrdi_taskana&branch=TSK-2483
Release Notes:
```
```
> Closes #2483: Update actions/download and upload artifact from 3 to 4

- rest/taskana-rest-spring-example-boot/src/main/java/pro/taskana/example/boot/security/BootWebSecurityConfigurer.java
- rest/taskana-rest-spring-example-boot/src/main/java/pro/taskana/example/boot/security/CsrfCookieFilter.java
- rest/taskana-rest-spring-example-boot/src/main/java/pro/taskana/example/boot/security/SpaCsrfTokenRequestHandler.java
- rest/taskana-rest-spring-example-common/src/main/java/pro/taskana/example/rest/ExampleWebSecurityConfig.java
- rest/taskana-rest-spring-example-wildfly/src/main/java/pro/taskana/example/wildfly/security/WildflyWebSecurityConfigurer.java
> Closes #2510 - fixed csrf handling without disabling it

- history/taskana-simplehistory-provider/src/main/java/pro/taskana/simplehistory/impl/jobs/HistoryCleanupJob.java
- lib/taskana-core-test/src/test/java/acceptance/jobs/HistoryCleanupJobAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/taskcomment/delete/DeleteTaskCommentAccTest.java
https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-2506
---
Release Notes:
```
```
> Closes #2506 - fix deleting DELETED history events by the cleanup job

- lib/taskana-core/src/main/java/pro/taskana/classification/internal/ClassificationServiceImpl.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/classification/rest/ClassificationController.java
> Closes #2555 - Fix deleteClassification

- .github/workflows/continuous-integration.yml
> Closes #2581: Deploy Demo App to Azure Fails in Pipeline

- .github/workflows/continuous-integration.yml
- ci/verify_docs_alive.sh
> Tsk 2581 2

- pom.xml
> Update maven gpg plugin - trigger upload to sonatype

- lib/taskana-core-test/src/test/java/acceptance/classification/delete/DeleteClassificationAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/claim/ClaimTaskAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/claim/SetOwnerAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/complete/CancelTaskAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/complete/CompleteTaskAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/complete/TerminateTaskAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/create/CreateTaskAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/delete/DeleteTaskAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/get/GetTaskAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/requestchanges/RequestChangesAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/requestchanges/RequestChangesWithBeforeSpiAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/requestreview/RequestReviewAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/requestreview/RequestReviewWithBeforeSpiAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/task/update/UpdateTaskAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/taskcomment/create/CreateTaskCommentAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/taskcomment/delete/DeleteTaskCommentAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/taskcomment/get/GetTaskCommentAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/user/UserServiceAccTest.java
- lib/taskana-core-test/src/test/java/acceptance/workbasket/get/GetWorkbasketAccTest.java
- pom.xml
> Closes #2604 - updated assertJ code to remove deprecation notices

- pom.xml
> Closes #2610 - fixed encoding configuration for checkstyle plugin

- rest/taskana-rest-spring-example-boot/src/main/java/pro/taskana/example/boot/OpenApiConfiguration.java
- rest/taskana-rest-spring-example-boot/src/main/java/pro/taskana/example/boot/security/BootWebSecurityConfigurer.java
- rest/taskana-rest-spring-example-boot/src/main/resources/application.properties
> Closes #2616 - Make OpenAPI/Swagger UI docs public

- .github/pull_request_template.md
Sonarcloud: https://sonarcloud.io/summary/new_code?id=ryzheboka_taskana&branch=TSK-2446
---
Release Notes:
```
```
> Closes #2446 - change the pull request template

- docker-databases/docker-compose.yml
- docker-databases/prepare_db.bat
- docker-databases/prepare_db.sh
- rest/taskana-rest-spring-example-wildfly/src/test/java/pro/taskana/example/wildfly/AbstractAccTest.java
> Closes #2638: Use "docker compose" instead of "docker-compose"

- pom.xml
- rest/taskana-rest-spring-example-wildfly/src/test/resources/module.xml
> Closes #2624 SpringBoot 3.3.1

- rest/taskana-rest-spring/src/main/java/pro/taskana/common/rest/util/QueryParamsValidator.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskController.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/task/rest/TaskQueryFilterParameter.java
- rest/taskana-rest-spring/src/main/java/pro/taskana/user/rest/UserController.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/task/rest/TaskControllerIntTest.java
- rest/taskana-rest-spring/src/test/java/pro/taskana/user/rest/UserControllerIntTest.java
> Closes #2635: Make owner-is-null=owner-is-null not valid

- lib/taskana-core-test/pom.xml
- lib/taskana-core-test/src/test/java/acceptance/task/query/TaskQueryImplAccTest.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskQuery.java
- lib/taskana-core/src/main/java/pro/taskana/task/api/TaskService.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQueryImpl.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskQuerySqlProvider.java
- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
> Closes #2599 - add locking to Query to enable adapter clustering

- lib/taskana-core/src/main/java/pro/taskana/task/internal/TaskServiceImpl.java
- pom.xml
> Closes Taskana#2648: Bump com.puppycrawl.tools:checkstyle from 10.14.0 to 10.17.0

- ci/verify_docs_alive.sh
- ci/verify_docs_jar.sh
> Closes #2650: Adapt verify docs scripts to OpenAPI/Swagger

- ci/mvnsettings.xml
> Closes #2657: fixed sonatype config

- pom.xml
> Closes #2664 SpringBoot 3.3.2
